// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/matlab/matlab-mcp-core-server/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockInstallationSteps creates a new instance of MockInstallationSteps. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInstallationSteps(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInstallationSteps {
	mock := &MockInstallationSteps{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInstallationSteps is an autogenerated mock type for the InstallationSteps type
type MockInstallationSteps struct {
	mock.Mock
}

type MockInstallationSteps_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInstallationSteps) EXPECT() *MockInstallationSteps_Expecter {
	return &MockInstallationSteps_Expecter{mock: &_m.Mock}
}

// InstallMLTBX provides a mock function for the type MockInstallationSteps
func (_mock *MockInstallationSteps) InstallMLTBX(ctx context.Context, logger entities.Logger, client entities.MATLABSessionClient) error {
	ret := _mock.Called(ctx, logger, client)

	if len(ret) == 0 {
		panic("no return value specified for InstallMLTBX")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Logger, entities.MATLABSessionClient) error); ok {
		r0 = returnFunc(ctx, logger, client)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInstallationSteps_InstallMLTBX_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstallMLTBX'
type MockInstallationSteps_InstallMLTBX_Call struct {
	*mock.Call
}

// InstallMLTBX is a helper method to define mock.On call
//   - ctx context.Context
//   - logger entities.Logger
//   - client entities.MATLABSessionClient
func (_e *MockInstallationSteps_Expecter) InstallMLTBX(ctx interface{}, logger interface{}, client interface{}) *MockInstallationSteps_InstallMLTBX_Call {
	return &MockInstallationSteps_InstallMLTBX_Call{Call: _e.mock.On("InstallMLTBX", ctx, logger, client)}
}

func (_c *MockInstallationSteps_InstallMLTBX_Call) Run(run func(ctx context.Context, logger entities.Logger, client entities.MATLABSessionClient)) *MockInstallationSteps_InstallMLTBX_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Logger
		if args[1] != nil {
			arg1 = args[1].(entities.Logger)
		}
		var arg2 entities.MATLABSessionClient
		if args[2] != nil {
			arg2 = args[2].(entities.MATLABSessionClient)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockInstallationSteps_InstallMLTBX_Call) Return(err error) *MockInstallationSteps_InstallMLTBX_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInstallationSteps_InstallMLTBX_Call) RunAndReturn(run func(ctx context.Context, logger entities.Logger, client entities.MATLABSessionClient) error) *MockInstallationSteps_InstallMLTBX_Call {
	_c.Call.Return(run)
	return _c
}

// UploadMLTBX provides a mock function for the type MockInstallationSteps
func (_mock *MockInstallationSteps) UploadMLTBX(ctx context.Context, logger entities.Logger, client entities.MATLABSessionClient) (func(), error) {
	ret := _mock.Called(ctx, logger, client)

	if len(ret) == 0 {
		panic("no return value specified for UploadMLTBX")
	}

	var r0 func()
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Logger, entities.MATLABSessionClient) (func(), error)); ok {
		return returnFunc(ctx, logger, client)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Logger, entities.MATLABSessionClient) func()); ok {
		r0 = returnFunc(ctx, logger, client)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func())
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.Logger, entities.MATLABSessionClient) error); ok {
		r1 = returnFunc(ctx, logger, client)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInstallationSteps_UploadMLTBX_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadMLTBX'
type MockInstallationSteps_UploadMLTBX_Call struct {
	*mock.Call
}

// UploadMLTBX is a helper method to define mock.On call
//   - ctx context.Context
//   - logger entities.Logger
//   - client entities.MATLABSessionClient
func (_e *MockInstallationSteps_Expecter) UploadMLTBX(ctx interface{}, logger interface{}, client interface{}) *MockInstallationSteps_UploadMLTBX_Call {
	return &MockInstallationSteps_UploadMLTBX_Call{Call: _e.mock.On("UploadMLTBX", ctx, logger, client)}
}

func (_c *MockInstallationSteps_UploadMLTBX_Call) Run(run func(ctx context.Context, logger entities.Logger, client entities.MATLABSessionClient)) *MockInstallationSteps_UploadMLTBX_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Logger
		if args[1] != nil {
			arg1 = args[1].(entities.Logger)
		}
		var arg2 entities.MATLABSessionClient
		if args[2] != nil {
			arg2 = args[2].(entities.MATLABSessionClient)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockInstallationSteps_UploadMLTBX_Call) Return(fn func(), err error) *MockInstallationSteps_UploadMLTBX_Call {
	_c.Call.Return(fn, err)
	return _c
}

func (_c *MockInstallationSteps_UploadMLTBX_Call) RunAndReturn(run func(ctx context.Context, logger entities.Logger, client entities.MATLABSessionClient) (func(), error)) *MockInstallationSteps_UploadMLTBX_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyMLTBXInstallationFile provides a mock function for the type MockInstallationSteps
func (_mock *MockInstallationSteps) VerifyMLTBXInstallationFile(ctx context.Context, logger entities.Logger, client entities.MATLABSessionClient) error {
	ret := _mock.Called(ctx, logger, client)

	if len(ret) == 0 {
		panic("no return value specified for VerifyMLTBXInstallationFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Logger, entities.MATLABSessionClient) error); ok {
		r0 = returnFunc(ctx, logger, client)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInstallationSteps_VerifyMLTBXInstallationFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyMLTBXInstallationFile'
type MockInstallationSteps_VerifyMLTBXInstallationFile_Call struct {
	*mock.Call
}

// VerifyMLTBXInstallationFile is a helper method to define mock.On call
//   - ctx context.Context
//   - logger entities.Logger
//   - client entities.MATLABSessionClient
func (_e *MockInstallationSteps_Expecter) VerifyMLTBXInstallationFile(ctx interface{}, logger interface{}, client interface{}) *MockInstallationSteps_VerifyMLTBXInstallationFile_Call {
	return &MockInstallationSteps_VerifyMLTBXInstallationFile_Call{Call: _e.mock.On("VerifyMLTBXInstallationFile", ctx, logger, client)}
}

func (_c *MockInstallationSteps_VerifyMLTBXInstallationFile_Call) Run(run func(ctx context.Context, logger entities.Logger, client entities.MATLABSessionClient)) *MockInstallationSteps_VerifyMLTBXInstallationFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Logger
		if args[1] != nil {
			arg1 = args[1].(entities.Logger)
		}
		var arg2 entities.MATLABSessionClient
		if args[2] != nil {
			arg2 = args[2].(entities.MATLABSessionClient)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockInstallationSteps_VerifyMLTBXInstallationFile_Call) Return(err error) *MockInstallationSteps_VerifyMLTBXInstallationFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInstallationSteps_VerifyMLTBXInstallationFile_Call) RunAndReturn(run func(ctx context.Context, logger entities.Logger, client entities.MATLABSessionClient) error) *MockInstallationSteps_VerifyMLTBXInstallationFile_Call {
	_c.Call.Return(run)
	return _c
}
