// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/matlab/matlab-mcp-core-server/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAddonManager creates a new instance of MockAddonManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAddonManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAddonManager {
	mock := &MockAddonManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAddonManager is an autogenerated mock type for the AddonManager type
type MockAddonManager struct {
	mock.Mock
}

type MockAddonManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAddonManager) EXPECT() *MockAddonManager_Expecter {
	return &MockAddonManager_Expecter{mock: &_m.Mock}
}

// Install provides a mock function for the type MockAddonManager
func (_mock *MockAddonManager) Install(ctx context.Context, logger entities.Logger, client entities.MATLABSessionClient) error {
	ret := _mock.Called(ctx, logger, client)

	if len(ret) == 0 {
		panic("no return value specified for Install")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Logger, entities.MATLABSessionClient) error); ok {
		r0 = returnFunc(ctx, logger, client)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAddonManager_Install_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Install'
type MockAddonManager_Install_Call struct {
	*mock.Call
}

// Install is a helper method to define mock.On call
//   - ctx context.Context
//   - logger entities.Logger
//   - client entities.MATLABSessionClient
func (_e *MockAddonManager_Expecter) Install(ctx interface{}, logger interface{}, client interface{}) *MockAddonManager_Install_Call {
	return &MockAddonManager_Install_Call{Call: _e.mock.On("Install", ctx, logger, client)}
}

func (_c *MockAddonManager_Install_Call) Run(run func(ctx context.Context, logger entities.Logger, client entities.MATLABSessionClient)) *MockAddonManager_Install_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Logger
		if args[1] != nil {
			arg1 = args[1].(entities.Logger)
		}
		var arg2 entities.MATLABSessionClient
		if args[2] != nil {
			arg2 = args[2].(entities.MATLABSessionClient)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAddonManager_Install_Call) Return(err error) *MockAddonManager_Install_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAddonManager_Install_Call) RunAndReturn(run func(ctx context.Context, logger entities.Logger, client entities.MATLABSessionClient) error) *MockAddonManager_Install_Call {
	_c.Call.Return(run)
	return _c
}
