// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/application/directory"
	"github.com/matlab/matlab-mcp-core-server/internal/messages"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDirectoryFactory creates a new instance of MockDirectoryFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDirectoryFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDirectoryFactory {
	mock := &MockDirectoryFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDirectoryFactory is an autogenerated mock type for the DirectoryFactory type
type MockDirectoryFactory struct {
	mock.Mock
}

type MockDirectoryFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDirectoryFactory) EXPECT() *MockDirectoryFactory_Expecter {
	return &MockDirectoryFactory_Expecter{mock: &_m.Mock}
}

// Directory provides a mock function for the type MockDirectoryFactory
func (_mock *MockDirectoryFactory) Directory() (directory.Directory, messages.Error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Directory")
	}

	var r0 directory.Directory
	var r1 messages.Error
	if returnFunc, ok := ret.Get(0).(func() (directory.Directory, messages.Error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() directory.Directory); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(directory.Directory)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() messages.Error); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(messages.Error)
		}
	}
	return r0, r1
}

// MockDirectoryFactory_Directory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Directory'
type MockDirectoryFactory_Directory_Call struct {
	*mock.Call
}

// Directory is a helper method to define mock.On call
func (_e *MockDirectoryFactory_Expecter) Directory() *MockDirectoryFactory_Directory_Call {
	return &MockDirectoryFactory_Directory_Call{Call: _e.mock.On("Directory")}
}

func (_c *MockDirectoryFactory_Directory_Call) Run(run func()) *MockDirectoryFactory_Directory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDirectoryFactory_Directory_Call) Return(directory1 directory.Directory, error messages.Error) *MockDirectoryFactory_Directory_Call {
	_c.Call.Return(directory1, error)
	return _c
}

func (_c *MockDirectoryFactory_Directory_Call) RunAndReturn(run func() (directory.Directory, messages.Error)) *MockDirectoryFactory_Directory_Call {
	_c.Call.Return(run)
	return _c
}
