// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockWatchdogClient creates a new instance of MockWatchdogClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWatchdogClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWatchdogClient {
	mock := &MockWatchdogClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWatchdogClient is an autogenerated mock type for the WatchdogClient type
type MockWatchdogClient struct {
	mock.Mock
}

type MockWatchdogClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWatchdogClient) EXPECT() *MockWatchdogClient_Expecter {
	return &MockWatchdogClient_Expecter{mock: &_m.Mock}
}

// Start provides a mock function for the type MockWatchdogClient
func (_mock *MockWatchdogClient) Start() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWatchdogClient_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockWatchdogClient_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockWatchdogClient_Expecter) Start() *MockWatchdogClient_Start_Call {
	return &MockWatchdogClient_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockWatchdogClient_Start_Call) Run(run func()) *MockWatchdogClient_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWatchdogClient_Start_Call) Return(err error) *MockWatchdogClient_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWatchdogClient_Start_Call) RunAndReturn(run func() error) *MockWatchdogClient_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockWatchdogClient
func (_mock *MockWatchdogClient) Stop() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWatchdogClient_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockWatchdogClient_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockWatchdogClient_Expecter) Stop() *MockWatchdogClient_Stop_Call {
	return &MockWatchdogClient_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockWatchdogClient_Stop_Call) Run(run func()) *MockWatchdogClient_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWatchdogClient_Stop_Call) Return(err error) *MockWatchdogClient_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWatchdogClient_Stop_Call) RunAndReturn(run func() error) *MockWatchdogClient_Stop_Call {
	_c.Call.Return(run)
	return _c
}
