classdef DefaultFSAdaptorTest < matlab.mock.TestCase
    %DefaultFSAdaptorTest Tests for DefaultFSAdaptor
    %   This test class verifies that DefaultFSAdaptor correctly manages
    %   secure folder and file operations.

    % Copyright 2026 The MathWorks, Inc.

    methods (Test)
        function testDefaultFSAdaptor_Constructor_HappyPath(testCase)
            % Arrange
            [mockFSFacade, ~] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockPermissionManager, ~] = testCase.createMock( ...
                ?mcpcoreserver.internal.fs.internal.permissionmanager.PermissionManager, ...
                Strict=true ...
            );

            % Act
            adaptor = mcpcoreserver.internal.fs.DefaultFSAdaptor( ...
                FSFacade=mockFSFacade, ...
                PermissionManager=mockPermissionManager ...
            );

            % Assert
            testCase.verifyInstanceOf( ...
                adaptor, ...
                ?mcpcoreserver.internal.fs.FSAdaptor, ...
                "DefaultFSAdaptor should be an FSAdaptor" ...
            );
        end

        function testDefaultFSAdaptor_EnsureSecureFolder_HappyPath_FolderExists(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockFSFacade, fsBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockPermissionManager, permBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.fs.internal.permissionmanager.PermissionManager, ...
                Strict=true ...
            );

            expectedFolderPath = fullfile("home", "user", "test-folder");

            when( ...
                fsBehavior.isfolder(expectedFolderPath), ...
                AssignOutputs(true) ...
            );
            when( ...
                permBehavior.checkPermissionsIsUserOnly(expectedFolderPath), ...
                AssignOutputs(true) ...
            );

            adaptor = mcpcoreserver.internal.fs.DefaultFSAdaptor( ...
                FSFacade=mockFSFacade, ...
                PermissionManager=mockPermissionManager ...
            );

            % Act
            adaptor.ensureSecureFolder(expectedFolderPath);

            % Assert
            testCase.verifyCalled( ...
                fsBehavior.isfolder(expectedFolderPath), ...
                "isfolder should be called" ...
            );
            testCase.verifyCalled( ...
                permBehavior.checkPermissionsIsUserOnly(expectedFolderPath), ...
                "checkPermissionsIsUserOnly should be called" ...
            );
        end

        function testDefaultFSAdaptor_EnsureSecureFolder_FolderExists_InsecurePermissions(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockFSFacade, fsBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockPermissionManager, permBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.fs.internal.permissionmanager.PermissionManager, ...
                Strict=true ...
            );

            expectedFolderPath = fullfile("home", "user", "test-folder");
            expectedError = mcpcoreserver.internal.error.Errors.InsecurePermissions(expectedFolderPath);

            when( ...
                fsBehavior.isfolder(expectedFolderPath), ...
                AssignOutputs(true) ...
            );
            when( ...
                permBehavior.checkPermissionsIsUserOnly(expectedFolderPath), ...
                AssignOutputs(false) ...
            );

            adaptor = mcpcoreserver.internal.fs.DefaultFSAdaptor( ...
                FSFacade=mockFSFacade, ...
                PermissionManager=mockPermissionManager ...
            );

            % Act & Assert
            testCase.verifyError( ...
                @() adaptor.ensureSecureFolder(expectedFolderPath), ...
                expectedError.identifier, ...
                "Should throw InsecurePermissions when folder has insecure permissions" ...
            );
        end

        function testDefaultFSAdaptor_EnsureSecureFolder_HappyPath_FolderDoesNotExist(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.DoNothing

            [mockFSFacade, fsBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockPermissionManager, permBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.fs.internal.permissionmanager.PermissionManager, ...
                Strict=true ...
            );

            expectedFolderPath = fullfile("home", "user", "test-folder");

            when( ...
                fsBehavior.isfolder(expectedFolderPath), ...
                AssignOutputs(false) ...
            );
            when( ...
                fsBehavior.isfile(expectedFolderPath), ...
                AssignOutputs(false) ...
            );
            when( ...
                fsBehavior.mkdir(expectedFolderPath), ...
                AssignOutputs(true, "") ...
            );
            when( ...
                permBehavior.setPermissionsToUserOnly(expectedFolderPath), ...
                DoNothing ...
            );

            adaptor = mcpcoreserver.internal.fs.DefaultFSAdaptor( ...
                FSFacade=mockFSFacade, ...
                PermissionManager=mockPermissionManager ...
            );

            % Act
            adaptor.ensureSecureFolder(expectedFolderPath);

            % Assert
            testCase.verifyCalled( ...
                fsBehavior.mkdir(expectedFolderPath), ...
                "mkdir should be called" ...
            );
            testCase.verifyCalled( ...
                permBehavior.setPermissionsToUserOnly(expectedFolderPath), ...
                "setPermissionsToUserOnly should be called" ...
            );
        end

        function testDefaultFSAdaptor_EnsureSecureFolder_FolderDoesNotExist_FileExistsAtPath(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockFSFacade, fsBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockPermissionManager, ~] = testCase.createMock( ...
                ?mcpcoreserver.internal.fs.internal.permissionmanager.PermissionManager, ...
                Strict=true ...
            );

            expectedFolderPath = fullfile("home", "user", "test-folder");
            expectedError = mcpcoreserver.internal.error.Errors.FileExistsAtFolderPath(expectedFolderPath);

            when( ...
                fsBehavior.isfolder(expectedFolderPath), ...
                AssignOutputs(false) ...
            );
            when( ...
                fsBehavior.isfile(expectedFolderPath), ...
                AssignOutputs(true) ...
            );

            adaptor = mcpcoreserver.internal.fs.DefaultFSAdaptor( ...
                FSFacade=mockFSFacade, ...
                PermissionManager=mockPermissionManager ...
            );

            % Act & Assert
            testCase.verifyError( ...
                @() adaptor.ensureSecureFolder(expectedFolderPath), ...
                expectedError.identifier, ...
                "Should throw FileExistsAtFolderPath when a file exists at the folder path" ...
            );
        end

        function testDefaultFSAdaptor_EnsureSecureFolder_FolderDoesNotExist_MkdirFails(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockFSFacade, fsBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockPermissionManager, ~] = testCase.createMock( ...
                ?mcpcoreserver.internal.fs.internal.permissionmanager.PermissionManager, ...
                Strict=true ...
            );

            expectedFolderPath = fullfile("home", "user", "test-folder");
            expectedMsg = "Permission denied";
            expectedError = mcpcoreserver.internal.error.Errors.FailedToCreateDirectory( ...
                expectedFolderPath, ...
                expectedMsg ...
            );

            when( ...
                fsBehavior.isfolder(expectedFolderPath), ...
                AssignOutputs(false) ...
            );
            when( ...
                fsBehavior.isfile(expectedFolderPath), ...
                AssignOutputs(false) ...
            );
            when( ...
                fsBehavior.mkdir(expectedFolderPath), ...
                AssignOutputs(false, expectedMsg) ...
            );

            adaptor = mcpcoreserver.internal.fs.DefaultFSAdaptor( ...
                FSFacade=mockFSFacade, ...
                PermissionManager=mockPermissionManager ...
            );

            % Act & Assert
            testCase.verifyError( ...
                @() adaptor.ensureSecureFolder(expectedFolderPath), ...
                expectedError.identifier, ...
                "Should throw FailedToCreateDirectory when mkdir fails" ...
            );
        end

        function testDefaultFSAdaptor_EnsureSecureFile_HappyPath_FileExists(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockFSFacade, fsBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockPermissionManager, permBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.fs.internal.permissionmanager.PermissionManager, ...
                Strict=true ...
            );

            expectedFilePath = fullfile("home", "user", "test-file.json");

            when( ...
                fsBehavior.isfile(expectedFilePath), ...
                AssignOutputs(true) ...
            );
            when( ...
                permBehavior.checkPermissionsIsUserOnly(expectedFilePath), ...
                AssignOutputs(true) ...
            );

            adaptor = mcpcoreserver.internal.fs.DefaultFSAdaptor( ...
                FSFacade=mockFSFacade, ...
                PermissionManager=mockPermissionManager ...
            );

            % Act
            adaptor.ensureSecureFile(expectedFilePath);

            % Assert
            testCase.verifyCalled( ...
                fsBehavior.isfile(expectedFilePath), ...
                "isfile should be called" ...
            );
            testCase.verifyCalled( ...
                permBehavior.checkPermissionsIsUserOnly(expectedFilePath), ...
                "checkPermissionsIsUserOnly should be called" ...
            );
        end

        function testDefaultFSAdaptor_EnsureSecureFile_FileExists_InsecurePermissions(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockFSFacade, fsBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockPermissionManager, permBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.fs.internal.permissionmanager.PermissionManager, ...
                Strict=true ...
            );

            expectedFilePath = fullfile("home", "user", "test-file.json");
            expectedError = mcpcoreserver.internal.error.Errors.InsecurePermissions(expectedFilePath);

            when( ...
                fsBehavior.isfile(expectedFilePath), ...
                AssignOutputs(true) ...
            );
            when( ...
                permBehavior.checkPermissionsIsUserOnly(expectedFilePath), ...
                AssignOutputs(false) ...
            );

            adaptor = mcpcoreserver.internal.fs.DefaultFSAdaptor( ...
                FSFacade=mockFSFacade, ...
                PermissionManager=mockPermissionManager ...
            );

            % Act & Assert
            testCase.verifyError( ...
                @() adaptor.ensureSecureFile(expectedFilePath), ...
                expectedError.identifier, ...
                "Should throw InsecurePermissions when file has insecure permissions" ...
            );
        end

        function testDefaultFSAdaptor_EnsureSecureFile_HappyPath_FileDoesNotExist(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.DoNothing

            [mockFSFacade, fsBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockPermissionManager, permBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.fs.internal.permissionmanager.PermissionManager, ...
                Strict=true ...
            );

            expectedFilePath = fullfile("home", "user", "test-file.json");

            when( ...
                fsBehavior.isfile(expectedFilePath), ...
                AssignOutputs(false) ...
            );
            when( ...
                fsBehavior.isfolder(expectedFilePath), ...
                AssignOutputs(false) ...
            );
            when( ...
                fsBehavior.writelines("", expectedFilePath), ...
                DoNothing ...
            );
            when( ...
                permBehavior.setPermissionsToUserOnly(expectedFilePath), ...
                DoNothing ...
            );

            adaptor = mcpcoreserver.internal.fs.DefaultFSAdaptor( ...
                FSFacade=mockFSFacade, ...
                PermissionManager=mockPermissionManager ...
            );

            % Act
            adaptor.ensureSecureFile(expectedFilePath);

            % Assert
            testCase.verifyCalled( ...
                fsBehavior.writelines("", expectedFilePath), ...
                "writelines should be called to create empty file" ...
            );
            testCase.verifyCalled( ...
                permBehavior.setPermissionsToUserOnly(expectedFilePath), ...
                "setPermissionsToUserOnly should be called" ...
            );
        end

        function testDefaultFSAdaptor_EnsureSecureFile_FileDoesNotExist_FolderExistsAtPath(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockFSFacade, fsBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockPermissionManager, ~] = testCase.createMock( ...
                ?mcpcoreserver.internal.fs.internal.permissionmanager.PermissionManager, ...
                Strict=true ...
            );

            expectedFilePath = fullfile("home", "user", "test-file.json");
            expectedError = mcpcoreserver.internal.error.Errors.FolderExistsAtFilePath(expectedFilePath);

            when( ...
                fsBehavior.isfile(expectedFilePath), ...
                AssignOutputs(false) ...
            );
            when( ...
                fsBehavior.isfolder(expectedFilePath), ...
                AssignOutputs(true) ...
            );

            adaptor = mcpcoreserver.internal.fs.DefaultFSAdaptor( ...
                FSFacade=mockFSFacade, ...
                PermissionManager=mockPermissionManager ...
            );

            % Act & Assert
            testCase.verifyError( ...
                @() adaptor.ensureSecureFile(expectedFilePath), ...
                expectedError.identifier, ...
                "Should throw FolderExistsAtFilePath when a folder exists at the file path" ...
            );
        end

        function testDefaultFSAdaptor_EnsureSecureFile_FileDoesNotExist_WriteFails(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.ThrowException

            [mockFSFacade, fsBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockPermissionManager, ~] = testCase.createMock( ...
                ?mcpcoreserver.internal.fs.internal.permissionmanager.PermissionManager, ...
                Strict=true ...
            );

            expectedFilePath = fullfile("home", "user", "test-file.json");
            expectedException = MException("MATLAB:writelines:UnableToCreate", ...
                "Unable to create file");

            when( ...
                fsBehavior.isfile(expectedFilePath), ...
                AssignOutputs(false) ...
            );
            when( ...
                fsBehavior.isfolder(expectedFilePath), ...
                AssignOutputs(false) ...
            );
            when( ...
                fsBehavior.writelines("", expectedFilePath), ...
                ThrowException(expectedException) ...
            );

            adaptor = mcpcoreserver.internal.fs.DefaultFSAdaptor( ...
                FSFacade=mockFSFacade, ...
                PermissionManager=mockPermissionManager ...
            );

            % Act & Assert
            testCase.verifyError( ...
                @() adaptor.ensureSecureFile(expectedFilePath), ...
                expectedException.identifier, ...
                "Should propagate error when writelines fails" ...
            );
        end
    end

end
