// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/matlab/matlab-mcp-core-server/internal/messages"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSetupMATLAB creates a new instance of MockSetupMATLAB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSetupMATLAB(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSetupMATLAB {
	mock := &MockSetupMATLAB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSetupMATLAB is an autogenerated mock type for the SetupMATLAB type
type MockSetupMATLAB struct {
	mock.Mock
}

type MockSetupMATLAB_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSetupMATLAB) EXPECT() *MockSetupMATLAB_Expecter {
	return &MockSetupMATLAB_Expecter{mock: &_m.Mock}
}

// StartAndWaitForCompletion provides a mock function for the type MockSetupMATLAB
func (_mock *MockSetupMATLAB) StartAndWaitForCompletion(ctx context.Context) messages.Error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for StartAndWaitForCompletion")
	}

	var r0 messages.Error
	if returnFunc, ok := ret.Get(0).(func(context.Context) messages.Error); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(messages.Error)
		}
	}
	return r0
}

// MockSetupMATLAB_StartAndWaitForCompletion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartAndWaitForCompletion'
type MockSetupMATLAB_StartAndWaitForCompletion_Call struct {
	*mock.Call
}

// StartAndWaitForCompletion is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSetupMATLAB_Expecter) StartAndWaitForCompletion(ctx interface{}) *MockSetupMATLAB_StartAndWaitForCompletion_Call {
	return &MockSetupMATLAB_StartAndWaitForCompletion_Call{Call: _e.mock.On("StartAndWaitForCompletion", ctx)}
}

func (_c *MockSetupMATLAB_StartAndWaitForCompletion_Call) Run(run func(ctx context.Context)) *MockSetupMATLAB_StartAndWaitForCompletion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSetupMATLAB_StartAndWaitForCompletion_Call) Return(error messages.Error) *MockSetupMATLAB_StartAndWaitForCompletion_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *MockSetupMATLAB_StartAndWaitForCompletion_Call) RunAndReturn(run func(ctx context.Context) messages.Error) *MockSetupMATLAB_StartAndWaitForCompletion_Call {
	_c.Call.Return(run)
	return _c
}
