// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/facades/osfacade"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOSLayer creates a new instance of MockOSLayer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOSLayer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOSLayer {
	mock := &MockOSLayer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOSLayer is an autogenerated mock type for the OSLayer type
type MockOSLayer struct {
	mock.Mock
}

type MockOSLayer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOSLayer) EXPECT() *MockOSLayer_Expecter {
	return &MockOSLayer_Expecter{mock: &_m.Mock}
}

// GOOS provides a mock function for the type MockOSLayer
func (_mock *MockOSLayer) GOOS() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GOOS")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockOSLayer_GOOS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GOOS'
type MockOSLayer_GOOS_Call struct {
	*mock.Call
}

// GOOS is a helper method to define mock.On call
func (_e *MockOSLayer_Expecter) GOOS() *MockOSLayer_GOOS_Call {
	return &MockOSLayer_GOOS_Call{Call: _e.mock.On("GOOS")}
}

func (_c *MockOSLayer_GOOS_Call) Run(run func()) *MockOSLayer_GOOS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOSLayer_GOOS_Call) Return(s string) *MockOSLayer_GOOS_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockOSLayer_GOOS_Call) RunAndReturn(run func() string) *MockOSLayer_GOOS_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function for the type MockOSLayer
func (_mock *MockOSLayer) Stat(path string) (osfacade.FileInfo, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 osfacade.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (osfacade.FileInfo, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) osfacade.FileInfo); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(osfacade.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOSLayer_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type MockOSLayer_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - path string
func (_e *MockOSLayer_Expecter) Stat(path interface{}) *MockOSLayer_Stat_Call {
	return &MockOSLayer_Stat_Call{Call: _e.mock.On("Stat", path)}
}

func (_c *MockOSLayer_Stat_Call) Run(run func(path string)) *MockOSLayer_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOSLayer_Stat_Call) Return(fileInfo osfacade.FileInfo, err error) *MockOSLayer_Stat_Call {
	_c.Call.Return(fileInfo, err)
	return _c
}

func (_c *MockOSLayer_Stat_Call) RunAndReturn(run func(path string) (osfacade.FileInfo, error)) *MockOSLayer_Stat_Call {
	_c.Call.Return(run)
	return _c
}

// UserHomeDir provides a mock function for the type MockOSLayer
func (_mock *MockOSLayer) UserHomeDir() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UserHomeDir")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOSLayer_UserHomeDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserHomeDir'
type MockOSLayer_UserHomeDir_Call struct {
	*mock.Call
}

// UserHomeDir is a helper method to define mock.On call
func (_e *MockOSLayer_Expecter) UserHomeDir() *MockOSLayer_UserHomeDir_Call {
	return &MockOSLayer_UserHomeDir_Call{Call: _e.mock.On("UserHomeDir")}
}

func (_c *MockOSLayer_UserHomeDir_Call) Run(run func()) *MockOSLayer_UserHomeDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOSLayer_UserHomeDir_Call) Return(s string, err error) *MockOSLayer_UserHomeDir_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockOSLayer_UserHomeDir_Call) RunAndReturn(run func() (string, error)) *MockOSLayer_UserHomeDir_Call {
	_c.Call.Return(run)
	return _c
}
