// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRootPathResolver creates a new instance of MockRootPathResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRootPathResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRootPathResolver {
	mock := &MockRootPathResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRootPathResolver is an autogenerated mock type for the RootPathResolver type
type MockRootPathResolver struct {
	mock.Mock
}

type MockRootPathResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRootPathResolver) EXPECT() *MockRootPathResolver_Expecter {
	return &MockRootPathResolver_Expecter{mock: &_m.Mock}
}

// Resolve provides a mock function for the type MockRootPathResolver
func (_mock *MockRootPathResolver) Resolve(root entities.MCPRoot) (string, error) {
	ret := _mock.Called(root)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(entities.MCPRoot) (string, error)); ok {
		return returnFunc(root)
	}
	if returnFunc, ok := ret.Get(0).(func(entities.MCPRoot) string); ok {
		r0 = returnFunc(root)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(entities.MCPRoot) error); ok {
		r1 = returnFunc(root)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRootPathResolver_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockRootPathResolver_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - root entities.MCPRoot
func (_e *MockRootPathResolver_Expecter) Resolve(root interface{}) *MockRootPathResolver_Resolve_Call {
	return &MockRootPathResolver_Resolve_Call{Call: _e.mock.On("Resolve", root)}
}

func (_c *MockRootPathResolver_Resolve_Call) Run(run func(root entities.MCPRoot)) *MockRootPathResolver_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 entities.MCPRoot
		if args[0] != nil {
			arg0 = args[0].(entities.MCPRoot)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRootPathResolver_Resolve_Call) Return(s string, err error) *MockRootPathResolver_Resolve_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockRootPathResolver_Resolve_Call) RunAndReturn(run func(root entities.MCPRoot) (string, error)) *MockRootPathResolver_Resolve_Call {
	_c.Call.Return(run)
	return _c
}
