// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRootStore creates a new instance of MockRootStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRootStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRootStore {
	mock := &MockRootStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRootStore is an autogenerated mock type for the RootStore type
type MockRootStore struct {
	mock.Mock
}

type MockRootStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRootStore) EXPECT() *MockRootStore_Expecter {
	return &MockRootStore_Expecter{mock: &_m.Mock}
}

// GetRoots provides a mock function for the type MockRootStore
func (_mock *MockRootStore) GetRoots() []entities.MCPRoot {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRoots")
	}

	var r0 []entities.MCPRoot
	if returnFunc, ok := ret.Get(0).(func() []entities.MCPRoot); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.MCPRoot)
		}
	}
	return r0
}

// MockRootStore_GetRoots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoots'
type MockRootStore_GetRoots_Call struct {
	*mock.Call
}

// GetRoots is a helper method to define mock.On call
func (_e *MockRootStore_Expecter) GetRoots() *MockRootStore_GetRoots_Call {
	return &MockRootStore_GetRoots_Call{Call: _e.mock.On("GetRoots")}
}

func (_c *MockRootStore_GetRoots_Call) Run(run func()) *MockRootStore_GetRoots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRootStore_GetRoots_Call) Return(mCPRoots []entities.MCPRoot) *MockRootStore_GetRoots_Call {
	_c.Call.Return(mCPRoots)
	return _c
}

func (_c *MockRootStore_GetRoots_Call) RunAndReturn(run func() []entities.MCPRoot) *MockRootStore_GetRoots_Call {
	_c.Call.Return(run)
	return _c
}
