// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/application/config"
	"github.com/matlab/matlab-mcp-core-server/internal/messages"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConfigFactory creates a new instance of MockConfigFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigFactory {
	mock := &MockConfigFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfigFactory is an autogenerated mock type for the ConfigFactory type
type MockConfigFactory struct {
	mock.Mock
}

type MockConfigFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigFactory) EXPECT() *MockConfigFactory_Expecter {
	return &MockConfigFactory_Expecter{mock: &_m.Mock}
}

// Config provides a mock function for the type MockConfigFactory
func (_mock *MockConfigFactory) Config() (config.Config, messages.Error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 config.Config
	var r1 messages.Error
	if returnFunc, ok := ret.Get(0).(func() (config.Config, messages.Error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() config.Config); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.Config)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() messages.Error); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(messages.Error)
		}
	}
	return r0, r1
}

// MockConfigFactory_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockConfigFactory_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockConfigFactory_Expecter) Config() *MockConfigFactory_Config_Call {
	return &MockConfigFactory_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockConfigFactory_Config_Call) Run(run func()) *MockConfigFactory_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigFactory_Config_Call) Return(config1 config.Config, error messages.Error) *MockConfigFactory_Config_Call {
	_c.Call.Return(config1, error)
	return _c
}

func (_c *MockConfigFactory_Config_Call) RunAndReturn(run func() (config.Config, messages.Error)) *MockConfigFactory_Config_Call {
	_c.Call.Return(run)
	return _c
}
