// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/matlabmanager/matlabsessionclient/embeddedconnector"
	"github.com/matlab/matlab-mcp-core-server/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionSelector creates a new instance of MockSessionSelector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionSelector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionSelector {
	mock := &MockSessionSelector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionSelector is an autogenerated mock type for the SessionSelector type
type MockSessionSelector struct {
	mock.Mock
}

type MockSessionSelector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionSelector) EXPECT() *MockSessionSelector_Expecter {
	return &MockSessionSelector_Expecter{mock: &_m.Mock}
}

// SelectSessionToAttachTo provides a mock function for the type MockSessionSelector
func (_mock *MockSessionSelector) SelectSessionToAttachTo(logger entities.Logger) (embeddedconnector.ConnectionDetails, error) {
	ret := _mock.Called(logger)

	if len(ret) == 0 {
		panic("no return value specified for SelectSessionToAttachTo")
	}

	var r0 embeddedconnector.ConnectionDetails
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(entities.Logger) (embeddedconnector.ConnectionDetails, error)); ok {
		return returnFunc(logger)
	}
	if returnFunc, ok := ret.Get(0).(func(entities.Logger) embeddedconnector.ConnectionDetails); ok {
		r0 = returnFunc(logger)
	} else {
		r0 = ret.Get(0).(embeddedconnector.ConnectionDetails)
	}
	if returnFunc, ok := ret.Get(1).(func(entities.Logger) error); ok {
		r1 = returnFunc(logger)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionSelector_SelectSessionToAttachTo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectSessionToAttachTo'
type MockSessionSelector_SelectSessionToAttachTo_Call struct {
	*mock.Call
}

// SelectSessionToAttachTo is a helper method to define mock.On call
//   - logger entities.Logger
func (_e *MockSessionSelector_Expecter) SelectSessionToAttachTo(logger interface{}) *MockSessionSelector_SelectSessionToAttachTo_Call {
	return &MockSessionSelector_SelectSessionToAttachTo_Call{Call: _e.mock.On("SelectSessionToAttachTo", logger)}
}

func (_c *MockSessionSelector_SelectSessionToAttachTo_Call) Run(run func(logger entities.Logger)) *MockSessionSelector_SelectSessionToAttachTo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 entities.Logger
		if args[0] != nil {
			arg0 = args[0].(entities.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSessionSelector_SelectSessionToAttachTo_Call) Return(connectionDetails embeddedconnector.ConnectionDetails, err error) *MockSessionSelector_SelectSessionToAttachTo_Call {
	_c.Call.Return(connectionDetails, err)
	return _c
}

func (_c *MockSessionSelector_SelectSessionToAttachTo_Call) RunAndReturn(run func(logger entities.Logger) (embeddedconnector.ConnectionDetails, error)) *MockSessionSelector_SelectSessionToAttachTo_Call {
	_c.Call.Return(run)
	return _c
}
