// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockBinaryBuilder creates a new instance of MockBinaryBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBinaryBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBinaryBuilder {
	mock := &MockBinaryBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBinaryBuilder is an autogenerated mock type for the BinaryBuilder type
type MockBinaryBuilder struct {
	mock.Mock
}

type MockBinaryBuilder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBinaryBuilder) EXPECT() *MockBinaryBuilder_Expecter {
	return &MockBinaryBuilder_Expecter{mock: &_m.Mock}
}

// BuildPlatformSpecificBinaries provides a mock function for the type MockBinaryBuilder
func (_mock *MockBinaryBuilder) BuildPlatformSpecificBinaries(moduleDir string, binDir string) error {
	ret := _mock.Called(moduleDir, binDir)

	if len(ret) == 0 {
		panic("no return value specified for BuildPlatformSpecificBinaries")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(moduleDir, binDir)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBinaryBuilder_BuildPlatformSpecificBinaries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildPlatformSpecificBinaries'
type MockBinaryBuilder_BuildPlatformSpecificBinaries_Call struct {
	*mock.Call
}

// BuildPlatformSpecificBinaries is a helper method to define mock.On call
//   - moduleDir string
//   - binDir string
func (_e *MockBinaryBuilder_Expecter) BuildPlatformSpecificBinaries(moduleDir interface{}, binDir interface{}) *MockBinaryBuilder_BuildPlatformSpecificBinaries_Call {
	return &MockBinaryBuilder_BuildPlatformSpecificBinaries_Call{Call: _e.mock.On("BuildPlatformSpecificBinaries", moduleDir, binDir)}
}

func (_c *MockBinaryBuilder_BuildPlatformSpecificBinaries_Call) Run(run func(moduleDir string, binDir string)) *MockBinaryBuilder_BuildPlatformSpecificBinaries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBinaryBuilder_BuildPlatformSpecificBinaries_Call) Return(err error) *MockBinaryBuilder_BuildPlatformSpecificBinaries_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBinaryBuilder_BuildPlatformSpecificBinaries_Call) RunAndReturn(run func(moduleDir string, binDir string) error) *MockBinaryBuilder_BuildPlatformSpecificBinaries_Call {
	_c.Call.Return(run)
	return _c
}
