// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockModuleRootFinder creates a new instance of MockModuleRootFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockModuleRootFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockModuleRootFinder {
	mock := &MockModuleRootFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockModuleRootFinder is an autogenerated mock type for the ModuleRootFinder type
type MockModuleRootFinder struct {
	mock.Mock
}

type MockModuleRootFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockModuleRootFinder) EXPECT() *MockModuleRootFinder_Expecter {
	return &MockModuleRootFinder_Expecter{mock: &_m.Mock}
}

// FindModuleRoot provides a mock function for the type MockModuleRootFinder
func (_mock *MockModuleRootFinder) FindModuleRoot() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindModuleRoot")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockModuleRootFinder_FindModuleRoot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindModuleRoot'
type MockModuleRootFinder_FindModuleRoot_Call struct {
	*mock.Call
}

// FindModuleRoot is a helper method to define mock.On call
func (_e *MockModuleRootFinder_Expecter) FindModuleRoot() *MockModuleRootFinder_FindModuleRoot_Call {
	return &MockModuleRootFinder_FindModuleRoot_Call{Call: _e.mock.On("FindModuleRoot")}
}

func (_c *MockModuleRootFinder_FindModuleRoot_Call) Run(run func()) *MockModuleRootFinder_FindModuleRoot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockModuleRootFinder_FindModuleRoot_Call) Return(s string, err error) *MockModuleRootFinder_FindModuleRoot_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockModuleRootFinder_FindModuleRoot_Call) RunAndReturn(run func() (string, error)) *MockModuleRootFinder_FindModuleRoot_Call {
	_c.Call.Return(run)
	return _c
}
