// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"io/fs"

	mock "github.com/stretchr/testify/mock"
)

// NewMockFileSystemProvider creates a new instance of MockFileSystemProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileSystemProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileSystemProvider {
	mock := &MockFileSystemProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileSystemProvider is an autogenerated mock type for the FileSystemProvider type
type MockFileSystemProvider struct {
	mock.Mock
}

type MockFileSystemProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileSystemProvider) EXPECT() *MockFileSystemProvider_Expecter {
	return &MockFileSystemProvider_Expecter{mock: &_m.Mock}
}

// DirFS provides a mock function for the type MockFileSystemProvider
func (_mock *MockFileSystemProvider) DirFS(path string) fs.FS {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for DirFS")
	}

	var r0 fs.FS
	if returnFunc, ok := ret.Get(0).(func(string) fs.FS); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fs.FS)
		}
	}
	return r0
}

// MockFileSystemProvider_DirFS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DirFS'
type MockFileSystemProvider_DirFS_Call struct {
	*mock.Call
}

// DirFS is a helper method to define mock.On call
//   - path string
func (_e *MockFileSystemProvider_Expecter) DirFS(path interface{}) *MockFileSystemProvider_DirFS_Call {
	return &MockFileSystemProvider_DirFS_Call{Call: _e.mock.On("DirFS", path)}
}

func (_c *MockFileSystemProvider_DirFS_Call) Run(run func(path string)) *MockFileSystemProvider_DirFS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileSystemProvider_DirFS_Call) Return(fS fs.FS) *MockFileSystemProvider_DirFS_Call {
	_c.Call.Return(fS)
	return _c
}

func (_c *MockFileSystemProvider_DirFS_Call) RunAndReturn(run func(path string) fs.FS) *MockFileSystemProvider_DirFS_Call {
	_c.Call.Return(run)
	return _c
}
