// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"io/fs"

	"github.com/matlab/matlab-mcp-core-server/tests/testutils/logs"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLogReader creates a new instance of MockLogReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogReader {
	mock := &MockLogReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLogReader is an autogenerated mock type for the LogReader type
type MockLogReader struct {
	mock.Mock
}

type MockLogReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogReader) EXPECT() *MockLogReader_Expecter {
	return &MockLogReader_Expecter{mock: &_m.Mock}
}

// ReadCombined provides a mock function for the type MockLogReader
func (_mock *MockLogReader) ReadCombined(logFS fs.FS, globPattern string) (string, error) {
	ret := _mock.Called(logFS, globPattern)

	if len(ret) == 0 {
		panic("no return value specified for ReadCombined")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(fs.FS, string) (string, error)); ok {
		return returnFunc(logFS, globPattern)
	}
	if returnFunc, ok := ret.Get(0).(func(fs.FS, string) string); ok {
		r0 = returnFunc(logFS, globPattern)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(fs.FS, string) error); ok {
		r1 = returnFunc(logFS, globPattern)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLogReader_ReadCombined_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadCombined'
type MockLogReader_ReadCombined_Call struct {
	*mock.Call
}

// ReadCombined is a helper method to define mock.On call
//   - logFS fs.FS
//   - globPattern string
func (_e *MockLogReader_Expecter) ReadCombined(logFS interface{}, globPattern interface{}) *MockLogReader_ReadCombined_Call {
	return &MockLogReader_ReadCombined_Call{Call: _e.mock.On("ReadCombined", logFS, globPattern)}
}

func (_c *MockLogReader_ReadCombined_Call) Run(run func(logFS fs.FS, globPattern string)) *MockLogReader_ReadCombined_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 fs.FS
		if args[0] != nil {
			arg0 = args[0].(fs.FS)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLogReader_ReadCombined_Call) Return(s string, err error) *MockLogReader_ReadCombined_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockLogReader_ReadCombined_Call) RunAndReturn(run func(logFS fs.FS, globPattern string) (string, error)) *MockLogReader_ReadCombined_Call {
	_c.Call.Return(run)
	return _c
}

// ReadEntries provides a mock function for the type MockLogReader
func (_mock *MockLogReader) ReadEntries(logFS fs.FS, dumpPatterns []logs.DumpPattern) ([]logs.DumpEntry, error) {
	ret := _mock.Called(logFS, dumpPatterns)

	if len(ret) == 0 {
		panic("no return value specified for ReadEntries")
	}

	var r0 []logs.DumpEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(fs.FS, []logs.DumpPattern) ([]logs.DumpEntry, error)); ok {
		return returnFunc(logFS, dumpPatterns)
	}
	if returnFunc, ok := ret.Get(0).(func(fs.FS, []logs.DumpPattern) []logs.DumpEntry); ok {
		r0 = returnFunc(logFS, dumpPatterns)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]logs.DumpEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(fs.FS, []logs.DumpPattern) error); ok {
		r1 = returnFunc(logFS, dumpPatterns)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLogReader_ReadEntries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadEntries'
type MockLogReader_ReadEntries_Call struct {
	*mock.Call
}

// ReadEntries is a helper method to define mock.On call
//   - logFS fs.FS
//   - dumpPatterns []logs.DumpPattern
func (_e *MockLogReader_Expecter) ReadEntries(logFS interface{}, dumpPatterns interface{}) *MockLogReader_ReadEntries_Call {
	return &MockLogReader_ReadEntries_Call{Call: _e.mock.On("ReadEntries", logFS, dumpPatterns)}
}

func (_c *MockLogReader_ReadEntries_Call) Run(run func(logFS fs.FS, dumpPatterns []logs.DumpPattern)) *MockLogReader_ReadEntries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 fs.FS
		if args[0] != nil {
			arg0 = args[0].(fs.FS)
		}
		var arg1 []logs.DumpPattern
		if args[1] != nil {
			arg1 = args[1].([]logs.DumpPattern)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLogReader_ReadEntries_Call) Return(dumpEntrys []logs.DumpEntry, err error) *MockLogReader_ReadEntries_Call {
	_c.Call.Return(dumpEntrys, err)
	return _c
}

func (_c *MockLogReader_ReadEntries_Call) RunAndReturn(run func(logFS fs.FS, dumpPatterns []logs.DumpPattern) ([]logs.DumpEntry, error)) *MockLogReader_ReadEntries_Call {
	_c.Call.Return(run)
	return _c
}
