// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockStderrProvider creates a new instance of MockStderrProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStderrProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStderrProvider {
	mock := &MockStderrProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStderrProvider is an autogenerated mock type for the StderrProvider type
type MockStderrProvider struct {
	mock.Mock
}

type MockStderrProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStderrProvider) EXPECT() *MockStderrProvider_Expecter {
	return &MockStderrProvider_Expecter{mock: &_m.Mock}
}

// Stderr provides a mock function for the type MockStderrProvider
func (_mock *MockStderrProvider) Stderr() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stderr")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockStderrProvider_Stderr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stderr'
type MockStderrProvider_Stderr_Call struct {
	*mock.Call
}

// Stderr is a helper method to define mock.On call
func (_e *MockStderrProvider_Expecter) Stderr() *MockStderrProvider_Stderr_Call {
	return &MockStderrProvider_Stderr_Call{Call: _e.mock.On("Stderr")}
}

func (_c *MockStderrProvider_Stderr_Call) Run(run func()) *MockStderrProvider_Stderr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStderrProvider_Stderr_Call) Return(s string) *MockStderrProvider_Stderr_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockStderrProvider_Stderr_Call) RunAndReturn(run func() string) *MockStderrProvider_Stderr_Call {
	_c.Call.Return(run)
	return _c
}
