// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMATLABStartingDirSelector creates a new instance of MockMATLABStartingDirSelector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMATLABStartingDirSelector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMATLABStartingDirSelector {
	mock := &MockMATLABStartingDirSelector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMATLABStartingDirSelector is an autogenerated mock type for the MATLABStartingDirSelector type
type MockMATLABStartingDirSelector struct {
	mock.Mock
}

type MockMATLABStartingDirSelector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMATLABStartingDirSelector) EXPECT() *MockMATLABStartingDirSelector_Expecter {
	return &MockMATLABStartingDirSelector_Expecter{mock: &_m.Mock}
}

// SelectMATLABStartingDir provides a mock function for the type MockMATLABStartingDirSelector
func (_mock *MockMATLABStartingDirSelector) SelectMATLABStartingDir(logger entities.Logger) (string, error) {
	ret := _mock.Called(logger)

	if len(ret) == 0 {
		panic("no return value specified for SelectMATLABStartingDir")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(entities.Logger) (string, error)); ok {
		return returnFunc(logger)
	}
	if returnFunc, ok := ret.Get(0).(func(entities.Logger) string); ok {
		r0 = returnFunc(logger)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(entities.Logger) error); ok {
		r1 = returnFunc(logger)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMATLABStartingDirSelector_SelectMATLABStartingDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectMATLABStartingDir'
type MockMATLABStartingDirSelector_SelectMATLABStartingDir_Call struct {
	*mock.Call
}

// SelectMATLABStartingDir is a helper method to define mock.On call
//   - logger entities.Logger
func (_e *MockMATLABStartingDirSelector_Expecter) SelectMATLABStartingDir(logger interface{}) *MockMATLABStartingDirSelector_SelectMATLABStartingDir_Call {
	return &MockMATLABStartingDirSelector_SelectMATLABStartingDir_Call{Call: _e.mock.On("SelectMATLABStartingDir", logger)}
}

func (_c *MockMATLABStartingDirSelector_SelectMATLABStartingDir_Call) Run(run func(logger entities.Logger)) *MockMATLABStartingDirSelector_SelectMATLABStartingDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 entities.Logger
		if args[0] != nil {
			arg0 = args[0].(entities.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMATLABStartingDirSelector_SelectMATLABStartingDir_Call) Return(s string, err error) *MockMATLABStartingDirSelector_SelectMATLABStartingDir_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockMATLABStartingDirSelector_SelectMATLABStartingDir_Call) RunAndReturn(run func(logger entities.Logger) (string, error)) *MockMATLABStartingDirSelector_SelectMATLABStartingDir_Call {
	_c.Call.Return(run)
	return _c
}
