// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/matlab/matlab-mcp-core-server/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMATLABRootSelector creates a new instance of MockMATLABRootSelector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMATLABRootSelector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMATLABRootSelector {
	mock := &MockMATLABRootSelector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMATLABRootSelector is an autogenerated mock type for the MATLABRootSelector type
type MockMATLABRootSelector struct {
	mock.Mock
}

type MockMATLABRootSelector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMATLABRootSelector) EXPECT() *MockMATLABRootSelector_Expecter {
	return &MockMATLABRootSelector_Expecter{mock: &_m.Mock}
}

// SelectMATLABRoot provides a mock function for the type MockMATLABRootSelector
func (_mock *MockMATLABRootSelector) SelectMATLABRoot(ctx context.Context, logger entities.Logger) (string, error) {
	ret := _mock.Called(ctx, logger)

	if len(ret) == 0 {
		panic("no return value specified for SelectMATLABRoot")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Logger) (string, error)); ok {
		return returnFunc(ctx, logger)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Logger) string); ok {
		r0 = returnFunc(ctx, logger)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.Logger) error); ok {
		r1 = returnFunc(ctx, logger)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMATLABRootSelector_SelectMATLABRoot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectMATLABRoot'
type MockMATLABRootSelector_SelectMATLABRoot_Call struct {
	*mock.Call
}

// SelectMATLABRoot is a helper method to define mock.On call
//   - ctx context.Context
//   - logger entities.Logger
func (_e *MockMATLABRootSelector_Expecter) SelectMATLABRoot(ctx interface{}, logger interface{}) *MockMATLABRootSelector_SelectMATLABRoot_Call {
	return &MockMATLABRootSelector_SelectMATLABRoot_Call{Call: _e.mock.On("SelectMATLABRoot", ctx, logger)}
}

func (_c *MockMATLABRootSelector_SelectMATLABRoot_Call) Run(run func(ctx context.Context, logger entities.Logger)) *MockMATLABRootSelector_SelectMATLABRoot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Logger
		if args[1] != nil {
			arg1 = args[1].(entities.Logger)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMATLABRootSelector_SelectMATLABRoot_Call) Return(s string, err error) *MockMATLABRootSelector_SelectMATLABRoot_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockMATLABRootSelector_SelectMATLABRoot_Call) RunAndReturn(run func(ctx context.Context, logger entities.Logger) (string, error)) *MockMATLABRootSelector_SelectMATLABRoot_Call {
	_c.Call.Return(run)
	return _c
}
