classdef DefaultConnectorAdaptorTest < matlab.mock.TestCase
    %DefaultConnectorAdaptorTest Tests for DefaultConnectorAdaptor
    %   This test class verifies that DefaultConnectorAdaptor correctly
    %   retrieves connection details.

    % Copyright 2026 The MathWorks, Inc.

    methods (Test)
        function testDefaultConnectorAdaptor_Constructor_HappyPath(testCase)
            % Arrange
            [mockConnectorFacade, ~] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.connector.ConnectorFacade, ...
                Strict=true ...
            );
            [mockAPIKeyManager, ~] = testCase.createMock( ...
                ?mcpcoreserver.internal.connector.internal.apikeymanager.APIKeyManager, ...
                Strict=true ...
            );
            [mockOSFacade, ~] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );

            % Act
            adaptor = mcpcoreserver.internal.connector.DefaultConnectorAdaptor( ...
                ConnectorFacade=mockConnectorFacade, ...
                APIKeyManager=mockAPIKeyManager, ...
                OSFacade=mockOSFacade ...
            );

            % Assert
            testCase.verifyInstanceOf( ...
                adaptor, ...
                ?mcpcoreserver.internal.connector.ConnectorAdaptor, ...
                "DefaultConnectorAdaptor should be a ConnectorAdaptor" ...
            );
        end

        function testDefaultConnectorAdaptor_GetConnectionDetails_HappyPath(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockConnectorFacade, connectorBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.connector.ConnectorFacade, ...
                Strict=true ...
            );
            [mockAPIKeyManager, apiKeyBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.connector.internal.apikeymanager.APIKeyManager, ...
                Strict=true ...
            );
            [mockOSFacade, osBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );

            expectedPort = 31415;
            expectedCert = fullfile("home", "user", ".matlab", "connector.pem");
            expectedApiKey = "test-api-key";
            expectedPid = 12345;

            when( ...
                connectorBehavior.securePort().withExactInputs(), ...
                AssignOutputs(expectedPort) ...
            );
            when( ...
                connectorBehavior.getCertificateLocation().withExactInputs(), ...
                AssignOutputs(expectedCert) ...
            );
            when( ...
                apiKeyBehavior.getAPIKey().withExactInputs(), ...
                AssignOutputs(expectedApiKey) ...
            );
            when( ...
                osBehavior.feature("getpid"), ...
                AssignOutputs(expectedPid) ...
            );

            adaptor = mcpcoreserver.internal.connector.DefaultConnectorAdaptor( ...
                ConnectorFacade=mockConnectorFacade, ...
                APIKeyManager=mockAPIKeyManager, ...
                OSFacade=mockOSFacade ...
            );

            % Act
            details = adaptor.getConnectionDetails();

            % Assert
            testCase.verifyEqual(details.port, expectedPort, ...
                "Port should match expected value");
            testCase.verifyEqual(details.certificate, expectedCert, ...
                "Certificate should match expected value");
            testCase.verifyEqual(details.apiKey, expectedApiKey, ...
                "API key should match expected value");
            testCase.verifyEqual(details.pid, expectedPid, ...
                "PID should match expected value");
        end
    end

end
