// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/matlab/matlab-mcp-core-server/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMATLABManager creates a new instance of MockMATLABManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMATLABManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMATLABManager {
	mock := &MockMATLABManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMATLABManager is an autogenerated mock type for the MATLABManager type
type MockMATLABManager struct {
	mock.Mock
}

type MockMATLABManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMATLABManager) EXPECT() *MockMATLABManager_Expecter {
	return &MockMATLABManager_Expecter{mock: &_m.Mock}
}

// ListEnvironments provides a mock function for the type MockMATLABManager
func (_mock *MockMATLABManager) ListEnvironments(ctx context.Context, sessionLogger entities.Logger) []entities.EnvironmentInfo {
	ret := _mock.Called(ctx, sessionLogger)

	if len(ret) == 0 {
		panic("no return value specified for ListEnvironments")
	}

	var r0 []entities.EnvironmentInfo
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Logger) []entities.EnvironmentInfo); ok {
		r0 = returnFunc(ctx, sessionLogger)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.EnvironmentInfo)
		}
	}
	return r0
}

// MockMATLABManager_ListEnvironments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEnvironments'
type MockMATLABManager_ListEnvironments_Call struct {
	*mock.Call
}

// ListEnvironments is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionLogger entities.Logger
func (_e *MockMATLABManager_Expecter) ListEnvironments(ctx interface{}, sessionLogger interface{}) *MockMATLABManager_ListEnvironments_Call {
	return &MockMATLABManager_ListEnvironments_Call{Call: _e.mock.On("ListEnvironments", ctx, sessionLogger)}
}

func (_c *MockMATLABManager_ListEnvironments_Call) Run(run func(ctx context.Context, sessionLogger entities.Logger)) *MockMATLABManager_ListEnvironments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Logger
		if args[1] != nil {
			arg1 = args[1].(entities.Logger)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMATLABManager_ListEnvironments_Call) Return(environmentInfos []entities.EnvironmentInfo) *MockMATLABManager_ListEnvironments_Call {
	_c.Call.Return(environmentInfos)
	return _c
}

func (_c *MockMATLABManager_ListEnvironments_Call) RunAndReturn(run func(ctx context.Context, sessionLogger entities.Logger) []entities.EnvironmentInfo) *MockMATLABManager_ListEnvironments_Call {
	_c.Call.Return(run)
	return _c
}
