// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/facades/unix"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSyscallLayer creates a new instance of MockSyscallLayer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSyscallLayer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSyscallLayer {
	mock := &MockSyscallLayer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSyscallLayer is an autogenerated mock type for the SyscallLayer type
type MockSyscallLayer struct {
	mock.Mock
}

type MockSyscallLayer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSyscallLayer) EXPECT() *MockSyscallLayer_Expecter {
	return &MockSyscallLayer_Expecter{mock: &_m.Mock}
}

// Getrlimit provides a mock function for the type MockSyscallLayer
func (_mock *MockSyscallLayer) Getrlimit(resource int, rlim *unix.Rlimit) error {
	ret := _mock.Called(resource, rlim)

	if len(ret) == 0 {
		panic("no return value specified for Getrlimit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int, *unix.Rlimit) error); ok {
		r0 = returnFunc(resource, rlim)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSyscallLayer_Getrlimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Getrlimit'
type MockSyscallLayer_Getrlimit_Call struct {
	*mock.Call
}

// Getrlimit is a helper method to define mock.On call
//   - resource int
//   - rlim *unix.Rlimit
func (_e *MockSyscallLayer_Expecter) Getrlimit(resource interface{}, rlim interface{}) *MockSyscallLayer_Getrlimit_Call {
	return &MockSyscallLayer_Getrlimit_Call{Call: _e.mock.On("Getrlimit", resource, rlim)}
}

func (_c *MockSyscallLayer_Getrlimit_Call) Run(run func(resource int, rlim *unix.Rlimit)) *MockSyscallLayer_Getrlimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 *unix.Rlimit
		if args[1] != nil {
			arg1 = args[1].(*unix.Rlimit)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSyscallLayer_Getrlimit_Call) Return(err error) *MockSyscallLayer_Getrlimit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSyscallLayer_Getrlimit_Call) RunAndReturn(run func(resource int, rlim *unix.Rlimit) error) *MockSyscallLayer_Getrlimit_Call {
	_c.Call.Return(run)
	return _c
}

// Setrlimit provides a mock function for the type MockSyscallLayer
func (_mock *MockSyscallLayer) Setrlimit(resource int, rlim *unix.Rlimit) error {
	ret := _mock.Called(resource, rlim)

	if len(ret) == 0 {
		panic("no return value specified for Setrlimit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int, *unix.Rlimit) error); ok {
		r0 = returnFunc(resource, rlim)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSyscallLayer_Setrlimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Setrlimit'
type MockSyscallLayer_Setrlimit_Call struct {
	*mock.Call
}

// Setrlimit is a helper method to define mock.On call
//   - resource int
//   - rlim *unix.Rlimit
func (_e *MockSyscallLayer_Expecter) Setrlimit(resource interface{}, rlim interface{}) *MockSyscallLayer_Setrlimit_Call {
	return &MockSyscallLayer_Setrlimit_Call{Call: _e.mock.On("Setrlimit", resource, rlim)}
}

func (_c *MockSyscallLayer_Setrlimit_Call) Run(run func(resource int, rlim *unix.Rlimit)) *MockSyscallLayer_Setrlimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 *unix.Rlimit
		if args[1] != nil {
			arg1 = args[1].(*unix.Rlimit)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSyscallLayer_Setrlimit_Call) Return(err error) *MockSyscallLayer_Setrlimit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSyscallLayer_Setrlimit_Call) RunAndReturn(run func(resource int, rlim *unix.Rlimit) error) *MockSyscallLayer_Setrlimit_Call {
	_c.Call.Return(run)
	return _c
}
