// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockEnvironment creates a new instance of MockEnvironment. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEnvironment(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEnvironment {
	mock := &MockEnvironment{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEnvironment is an autogenerated mock type for the Environment type
type MockEnvironment struct {
	mock.Mock
}

type MockEnvironment_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEnvironment) EXPECT() *MockEnvironment_Expecter {
	return &MockEnvironment_Expecter{mock: &_m.Mock}
}

// Getenv provides a mock function for the type MockEnvironment
func (_mock *MockEnvironment) Getenv(key string) string {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Getenv")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockEnvironment_Getenv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Getenv'
type MockEnvironment_Getenv_Call struct {
	*mock.Call
}

// Getenv is a helper method to define mock.On call
//   - key string
func (_e *MockEnvironment_Expecter) Getenv(key interface{}) *MockEnvironment_Getenv_Call {
	return &MockEnvironment_Getenv_Call{Call: _e.mock.On("Getenv", key)}
}

func (_c *MockEnvironment_Getenv_Call) Run(run func(key string)) *MockEnvironment_Getenv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEnvironment_Getenv_Call) Return(s string) *MockEnvironment_Getenv_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockEnvironment_Getenv_Call) RunAndReturn(run func(key string) string) *MockEnvironment_Getenv_Call {
	_c.Call.Return(run)
	return _c
}
