// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"crypto/tls"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTLSMaterialProvider creates a new instance of MockTLSMaterialProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTLSMaterialProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTLSMaterialProvider {
	mock := &MockTLSMaterialProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTLSMaterialProvider is an autogenerated mock type for the TLSMaterialProvider type
type MockTLSMaterialProvider struct {
	mock.Mock
}

type MockTLSMaterialProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTLSMaterialProvider) EXPECT() *MockTLSMaterialProvider_Expecter {
	return &MockTLSMaterialProvider_Expecter{mock: &_m.Mock}
}

// GeneratePEM provides a mock function for the type MockTLSMaterialProvider
func (_mock *MockTLSMaterialProvider) GeneratePEM() ([]byte, []byte, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GeneratePEM")
	}

	var r0 []byte
	var r1 []byte
	var r2 error
	if returnFunc, ok := ret.Get(0).(func() ([]byte, []byte, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() []byte); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(2).(func() error); ok {
		r2 = returnFunc()
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTLSMaterialProvider_GeneratePEM_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GeneratePEM'
type MockTLSMaterialProvider_GeneratePEM_Call struct {
	*mock.Call
}

// GeneratePEM is a helper method to define mock.On call
func (_e *MockTLSMaterialProvider_Expecter) GeneratePEM() *MockTLSMaterialProvider_GeneratePEM_Call {
	return &MockTLSMaterialProvider_GeneratePEM_Call{Call: _e.mock.On("GeneratePEM")}
}

func (_c *MockTLSMaterialProvider_GeneratePEM_Call) Run(run func()) *MockTLSMaterialProvider_GeneratePEM_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTLSMaterialProvider_GeneratePEM_Call) Return(certPEM []byte, keyPEM []byte, err error) *MockTLSMaterialProvider_GeneratePEM_Call {
	_c.Call.Return(certPEM, keyPEM, err)
	return _c
}

func (_c *MockTLSMaterialProvider_GeneratePEM_Call) RunAndReturn(run func() ([]byte, []byte, error)) *MockTLSMaterialProvider_GeneratePEM_Call {
	_c.Call.Return(run)
	return _c
}

// TLSConfig provides a mock function for the type MockTLSMaterialProvider
func (_mock *MockTLSMaterialProvider) TLSConfig(certPEM []byte, keyPEM []byte) (*tls.Config, error) {
	ret := _mock.Called(certPEM, keyPEM)

	if len(ret) == 0 {
		panic("no return value specified for TLSConfig")
	}

	var r0 *tls.Config
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte, []byte) (*tls.Config, error)); ok {
		return returnFunc(certPEM, keyPEM)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte, []byte) *tls.Config); ok {
		r0 = returnFunc(certPEM, keyPEM)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tls.Config)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte, []byte) error); ok {
		r1 = returnFunc(certPEM, keyPEM)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTLSMaterialProvider_TLSConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TLSConfig'
type MockTLSMaterialProvider_TLSConfig_Call struct {
	*mock.Call
}

// TLSConfig is a helper method to define mock.On call
//   - certPEM []byte
//   - keyPEM []byte
func (_e *MockTLSMaterialProvider_Expecter) TLSConfig(certPEM interface{}, keyPEM interface{}) *MockTLSMaterialProvider_TLSConfig_Call {
	return &MockTLSMaterialProvider_TLSConfig_Call{Call: _e.mock.On("TLSConfig", certPEM, keyPEM)}
}

func (_c *MockTLSMaterialProvider_TLSConfig_Call) Run(run func(certPEM []byte, keyPEM []byte)) *MockTLSMaterialProvider_TLSConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTLSMaterialProvider_TLSConfig_Call) Return(config *tls.Config, err error) *MockTLSMaterialProvider_TLSConfig_Call {
	_c.Call.Return(config, err)
	return _c
}

func (_c *MockTLSMaterialProvider_TLSConfig_Call) RunAndReturn(run func(certPEM []byte, keyPEM []byte) (*tls.Config, error)) *MockTLSMaterialProvider_TLSConfig_Call {
	_c.Call.Return(run)
	return _c
}
