// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/modelcontextprotocol/go-sdk/mcp"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTool creates a new instance of MockTool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTool(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTool {
	mock := &MockTool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTool is an autogenerated mock type for the Tool type
type MockTool struct {
	mock.Mock
}

type MockTool_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTool) EXPECT() *MockTool_Expecter {
	return &MockTool_Expecter{mock: &_m.Mock}
}

// AddToServer provides a mock function for the type MockTool
func (_mock *MockTool) AddToServer(server *mcp.Server) error {
	ret := _mock.Called(server)

	if len(ret) == 0 {
		panic("no return value specified for AddToServer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*mcp.Server) error); ok {
		r0 = returnFunc(server)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTool_AddToServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddToServer'
type MockTool_AddToServer_Call struct {
	*mock.Call
}

// AddToServer is a helper method to define mock.On call
//   - server *mcp.Server
func (_e *MockTool_Expecter) AddToServer(server interface{}) *MockTool_AddToServer_Call {
	return &MockTool_AddToServer_Call{Call: _e.mock.On("AddToServer", server)}
}

func (_c *MockTool_AddToServer_Call) Run(run func(server *mcp.Server)) *MockTool_AddToServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *mcp.Server
		if args[0] != nil {
			arg0 = args[0].(*mcp.Server)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTool_AddToServer_Call) Return(err error) *MockTool_AddToServer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTool_AddToServer_Call) RunAndReturn(run func(server *mcp.Server) error) *MockTool_AddToServer_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockTool
func (_mock *MockTool) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTool_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockTool_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockTool_Expecter) Name() *MockTool_Name_Call {
	return &MockTool_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockTool_Name_Call) Run(run func()) *MockTool_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTool_Name_Call) Return(s string) *MockTool_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTool_Name_Call) RunAndReturn(run func() string) *MockTool_Name_Call {
	_c.Call.Return(run)
	return _c
}
