// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/modelcontextprotocol/go-sdk/mcp"
	mock "github.com/stretchr/testify/mock"
)

// NewMockToolWithStructuredContentOutput creates a new instance of MockToolWithStructuredContentOutput. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockToolWithStructuredContentOutput[ToolInput any, ToolOutput any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockToolWithStructuredContentOutput[ToolInput, ToolOutput] {
	mock := &MockToolWithStructuredContentOutput[ToolInput, ToolOutput]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockToolWithStructuredContentOutput is an autogenerated mock type for the ToolWithStructuredContentOutput type
type MockToolWithStructuredContentOutput[ToolInput any, ToolOutput any] struct {
	mock.Mock
}

type MockToolWithStructuredContentOutput_Expecter[ToolInput any, ToolOutput any] struct {
	mock *mock.Mock
}

func (_m *MockToolWithStructuredContentOutput[ToolInput, ToolOutput]) EXPECT() *MockToolWithStructuredContentOutput_Expecter[ToolInput, ToolOutput] {
	return &MockToolWithStructuredContentOutput_Expecter[ToolInput, ToolOutput]{mock: &_m.Mock}
}

// AddToServer provides a mock function for the type MockToolWithStructuredContentOutput
func (_mock *MockToolWithStructuredContentOutput[ToolInput, ToolOutput]) AddToServer(server *mcp.Server) error {
	ret := _mock.Called(server)

	if len(ret) == 0 {
		panic("no return value specified for AddToServer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*mcp.Server) error); ok {
		r0 = returnFunc(server)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockToolWithStructuredContentOutput_AddToServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddToServer'
type MockToolWithStructuredContentOutput_AddToServer_Call[ToolInput any, ToolOutput any] struct {
	*mock.Call
}

// AddToServer is a helper method to define mock.On call
//   - server *mcp.Server
func (_e *MockToolWithStructuredContentOutput_Expecter[ToolInput, ToolOutput]) AddToServer(server interface{}) *MockToolWithStructuredContentOutput_AddToServer_Call[ToolInput, ToolOutput] {
	return &MockToolWithStructuredContentOutput_AddToServer_Call[ToolInput, ToolOutput]{Call: _e.mock.On("AddToServer", server)}
}

func (_c *MockToolWithStructuredContentOutput_AddToServer_Call[ToolInput, ToolOutput]) Run(run func(server *mcp.Server)) *MockToolWithStructuredContentOutput_AddToServer_Call[ToolInput, ToolOutput] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *mcp.Server
		if args[0] != nil {
			arg0 = args[0].(*mcp.Server)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockToolWithStructuredContentOutput_AddToServer_Call[ToolInput, ToolOutput]) Return(err error) *MockToolWithStructuredContentOutput_AddToServer_Call[ToolInput, ToolOutput] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockToolWithStructuredContentOutput_AddToServer_Call[ToolInput, ToolOutput]) RunAndReturn(run func(server *mcp.Server) error) *MockToolWithStructuredContentOutput_AddToServer_Call[ToolInput, ToolOutput] {
	_c.Call.Return(run)
	return _c
}

// Handler provides a mock function for the type MockToolWithStructuredContentOutput
func (_mock *MockToolWithStructuredContentOutput[ToolInput, ToolOutput]) Handler() mcp.ToolHandlerFor[ToolInput, ToolOutput] {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Handler")
	}

	var r0 mcp.ToolHandlerFor[ToolInput, ToolOutput]
	if returnFunc, ok := ret.Get(0).(func() mcp.ToolHandlerFor[ToolInput, ToolOutput]); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mcp.ToolHandlerFor[ToolInput, ToolOutput])
		}
	}
	return r0
}

// MockToolWithStructuredContentOutput_Handler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handler'
type MockToolWithStructuredContentOutput_Handler_Call[ToolInput any, ToolOutput any] struct {
	*mock.Call
}

// Handler is a helper method to define mock.On call
func (_e *MockToolWithStructuredContentOutput_Expecter[ToolInput, ToolOutput]) Handler() *MockToolWithStructuredContentOutput_Handler_Call[ToolInput, ToolOutput] {
	return &MockToolWithStructuredContentOutput_Handler_Call[ToolInput, ToolOutput]{Call: _e.mock.On("Handler")}
}

func (_c *MockToolWithStructuredContentOutput_Handler_Call[ToolInput, ToolOutput]) Run(run func()) *MockToolWithStructuredContentOutput_Handler_Call[ToolInput, ToolOutput] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockToolWithStructuredContentOutput_Handler_Call[ToolInput, ToolOutput]) Return(toolHandlerFor mcp.ToolHandlerFor[ToolInput, ToolOutput]) *MockToolWithStructuredContentOutput_Handler_Call[ToolInput, ToolOutput] {
	_c.Call.Return(toolHandlerFor)
	return _c
}

func (_c *MockToolWithStructuredContentOutput_Handler_Call[ToolInput, ToolOutput]) RunAndReturn(run func() mcp.ToolHandlerFor[ToolInput, ToolOutput]) *MockToolWithStructuredContentOutput_Handler_Call[ToolInput, ToolOutput] {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockToolWithStructuredContentOutput
func (_mock *MockToolWithStructuredContentOutput[ToolInput, ToolOutput]) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockToolWithStructuredContentOutput_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockToolWithStructuredContentOutput_Name_Call[ToolInput any, ToolOutput any] struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockToolWithStructuredContentOutput_Expecter[ToolInput, ToolOutput]) Name() *MockToolWithStructuredContentOutput_Name_Call[ToolInput, ToolOutput] {
	return &MockToolWithStructuredContentOutput_Name_Call[ToolInput, ToolOutput]{Call: _e.mock.On("Name")}
}

func (_c *MockToolWithStructuredContentOutput_Name_Call[ToolInput, ToolOutput]) Run(run func()) *MockToolWithStructuredContentOutput_Name_Call[ToolInput, ToolOutput] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockToolWithStructuredContentOutput_Name_Call[ToolInput, ToolOutput]) Return(s string) *MockToolWithStructuredContentOutput_Name_Call[ToolInput, ToolOutput] {
	_c.Call.Return(s)
	return _c
}

func (_c *MockToolWithStructuredContentOutput_Name_Call[ToolInput, ToolOutput]) RunAndReturn(run func() string) *MockToolWithStructuredContentOutput_Name_Call[ToolInput, ToolOutput] {
	_c.Call.Return(run)
	return _c
}
