// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/modelcontextprotocol/go-sdk/mcp"
	mock "github.com/stretchr/testify/mock"
)

// NewMockToolWithUnstructuredContentOutput creates a new instance of MockToolWithUnstructuredContentOutput. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockToolWithUnstructuredContentOutput[ToolInput any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockToolWithUnstructuredContentOutput[ToolInput] {
	mock := &MockToolWithUnstructuredContentOutput[ToolInput]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockToolWithUnstructuredContentOutput is an autogenerated mock type for the ToolWithUnstructuredContentOutput type
type MockToolWithUnstructuredContentOutput[ToolInput any] struct {
	mock.Mock
}

type MockToolWithUnstructuredContentOutput_Expecter[ToolInput any] struct {
	mock *mock.Mock
}

func (_m *MockToolWithUnstructuredContentOutput[ToolInput]) EXPECT() *MockToolWithUnstructuredContentOutput_Expecter[ToolInput] {
	return &MockToolWithUnstructuredContentOutput_Expecter[ToolInput]{mock: &_m.Mock}
}

// AddToServer provides a mock function for the type MockToolWithUnstructuredContentOutput
func (_mock *MockToolWithUnstructuredContentOutput[ToolInput]) AddToServer(server *mcp.Server) error {
	ret := _mock.Called(server)

	if len(ret) == 0 {
		panic("no return value specified for AddToServer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*mcp.Server) error); ok {
		r0 = returnFunc(server)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockToolWithUnstructuredContentOutput_AddToServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddToServer'
type MockToolWithUnstructuredContentOutput_AddToServer_Call[ToolInput any] struct {
	*mock.Call
}

// AddToServer is a helper method to define mock.On call
//   - server *mcp.Server
func (_e *MockToolWithUnstructuredContentOutput_Expecter[ToolInput]) AddToServer(server interface{}) *MockToolWithUnstructuredContentOutput_AddToServer_Call[ToolInput] {
	return &MockToolWithUnstructuredContentOutput_AddToServer_Call[ToolInput]{Call: _e.mock.On("AddToServer", server)}
}

func (_c *MockToolWithUnstructuredContentOutput_AddToServer_Call[ToolInput]) Run(run func(server *mcp.Server)) *MockToolWithUnstructuredContentOutput_AddToServer_Call[ToolInput] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *mcp.Server
		if args[0] != nil {
			arg0 = args[0].(*mcp.Server)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockToolWithUnstructuredContentOutput_AddToServer_Call[ToolInput]) Return(err error) *MockToolWithUnstructuredContentOutput_AddToServer_Call[ToolInput] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockToolWithUnstructuredContentOutput_AddToServer_Call[ToolInput]) RunAndReturn(run func(server *mcp.Server) error) *MockToolWithUnstructuredContentOutput_AddToServer_Call[ToolInput] {
	_c.Call.Return(run)
	return _c
}

// Handler provides a mock function for the type MockToolWithUnstructuredContentOutput
func (_mock *MockToolWithUnstructuredContentOutput[ToolInput]) Handler() mcp.ToolHandlerFor[ToolInput, any] {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Handler")
	}

	var r0 mcp.ToolHandlerFor[ToolInput, any]
	if returnFunc, ok := ret.Get(0).(func() mcp.ToolHandlerFor[ToolInput, any]); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mcp.ToolHandlerFor[ToolInput, any])
		}
	}
	return r0
}

// MockToolWithUnstructuredContentOutput_Handler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handler'
type MockToolWithUnstructuredContentOutput_Handler_Call[ToolInput any] struct {
	*mock.Call
}

// Handler is a helper method to define mock.On call
func (_e *MockToolWithUnstructuredContentOutput_Expecter[ToolInput]) Handler() *MockToolWithUnstructuredContentOutput_Handler_Call[ToolInput] {
	return &MockToolWithUnstructuredContentOutput_Handler_Call[ToolInput]{Call: _e.mock.On("Handler")}
}

func (_c *MockToolWithUnstructuredContentOutput_Handler_Call[ToolInput]) Run(run func()) *MockToolWithUnstructuredContentOutput_Handler_Call[ToolInput] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockToolWithUnstructuredContentOutput_Handler_Call[ToolInput]) Return(toolHandlerFor mcp.ToolHandlerFor[ToolInput, any]) *MockToolWithUnstructuredContentOutput_Handler_Call[ToolInput] {
	_c.Call.Return(toolHandlerFor)
	return _c
}

func (_c *MockToolWithUnstructuredContentOutput_Handler_Call[ToolInput]) RunAndReturn(run func() mcp.ToolHandlerFor[ToolInput, any]) *MockToolWithUnstructuredContentOutput_Handler_Call[ToolInput] {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockToolWithUnstructuredContentOutput
func (_mock *MockToolWithUnstructuredContentOutput[ToolInput]) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockToolWithUnstructuredContentOutput_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockToolWithUnstructuredContentOutput_Name_Call[ToolInput any] struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockToolWithUnstructuredContentOutput_Expecter[ToolInput]) Name() *MockToolWithUnstructuredContentOutput_Name_Call[ToolInput] {
	return &MockToolWithUnstructuredContentOutput_Name_Call[ToolInput]{Call: _e.mock.On("Name")}
}

func (_c *MockToolWithUnstructuredContentOutput_Name_Call[ToolInput]) Run(run func()) *MockToolWithUnstructuredContentOutput_Name_Call[ToolInput] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockToolWithUnstructuredContentOutput_Name_Call[ToolInput]) Return(s string) *MockToolWithUnstructuredContentOutput_Name_Call[ToolInput] {
	_c.Call.Return(s)
	return _c
}

func (_c *MockToolWithUnstructuredContentOutput_Name_Call[ToolInput]) RunAndReturn(run func() string) *MockToolWithUnstructuredContentOutput_Name_Call[ToolInput] {
	_c.Call.Return(run)
	return _c
}
