// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/usecases/evalcustomtool/functioncall"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFunctionCallAssembler creates a new instance of MockFunctionCallAssembler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFunctionCallAssembler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFunctionCallAssembler {
	mock := &MockFunctionCallAssembler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFunctionCallAssembler is an autogenerated mock type for the FunctionCallAssembler type
type MockFunctionCallAssembler struct {
	mock.Mock
}

type MockFunctionCallAssembler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFunctionCallAssembler) EXPECT() *MockFunctionCallAssembler_Expecter {
	return &MockFunctionCallAssembler_Expecter{mock: &_m.Mock}
}

// Assemble provides a mock function for the type MockFunctionCallAssembler
func (_mock *MockFunctionCallAssembler) Assemble(args functioncall.Args) (string, error) {
	ret := _mock.Called(args)

	if len(ret) == 0 {
		panic("no return value specified for Assemble")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(functioncall.Args) (string, error)); ok {
		return returnFunc(args)
	}
	if returnFunc, ok := ret.Get(0).(func(functioncall.Args) string); ok {
		r0 = returnFunc(args)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(functioncall.Args) error); ok {
		r1 = returnFunc(args)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFunctionCallAssembler_Assemble_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Assemble'
type MockFunctionCallAssembler_Assemble_Call struct {
	*mock.Call
}

// Assemble is a helper method to define mock.On call
//   - args functioncall.Args
func (_e *MockFunctionCallAssembler_Expecter) Assemble(args interface{}) *MockFunctionCallAssembler_Assemble_Call {
	return &MockFunctionCallAssembler_Assemble_Call{Call: _e.mock.On("Assemble", args)}
}

func (_c *MockFunctionCallAssembler_Assemble_Call) Run(run func(args functioncall.Args)) *MockFunctionCallAssembler_Assemble_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 functioncall.Args
		if args[0] != nil {
			arg0 = args[0].(functioncall.Args)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFunctionCallAssembler_Assemble_Call) Return(s string, err error) *MockFunctionCallAssembler_Assemble_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockFunctionCallAssembler_Assemble_Call) RunAndReturn(run func(args functioncall.Args) (string, error)) *MockFunctionCallAssembler_Assemble_Call {
	_c.Call.Return(run)
	return _c
}
