// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"os"

	mock "github.com/stretchr/testify/mock"
)

// NewMockDirectoryFileSystem creates a new instance of MockDirectoryFileSystem. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDirectoryFileSystem(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDirectoryFileSystem {
	mock := &MockDirectoryFileSystem{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDirectoryFileSystem is an autogenerated mock type for the DirectoryFileSystem type
type MockDirectoryFileSystem struct {
	mock.Mock
}

type MockDirectoryFileSystem_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDirectoryFileSystem) EXPECT() *MockDirectoryFileSystem_Expecter {
	return &MockDirectoryFileSystem_Expecter{mock: &_m.Mock}
}

// MkdirAll provides a mock function for the type MockDirectoryFileSystem
func (_mock *MockDirectoryFileSystem) MkdirAll(path string, perm os.FileMode) error {
	ret := _mock.Called(path, perm)

	if len(ret) == 0 {
		panic("no return value specified for MkdirAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, os.FileMode) error); ok {
		r0 = returnFunc(path, perm)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDirectoryFileSystem_MkdirAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MkdirAll'
type MockDirectoryFileSystem_MkdirAll_Call struct {
	*mock.Call
}

// MkdirAll is a helper method to define mock.On call
//   - path string
//   - perm os.FileMode
func (_e *MockDirectoryFileSystem_Expecter) MkdirAll(path interface{}, perm interface{}) *MockDirectoryFileSystem_MkdirAll_Call {
	return &MockDirectoryFileSystem_MkdirAll_Call{Call: _e.mock.On("MkdirAll", path, perm)}
}

func (_c *MockDirectoryFileSystem_MkdirAll_Call) Run(run func(path string, perm os.FileMode)) *MockDirectoryFileSystem_MkdirAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 os.FileMode
		if args[1] != nil {
			arg1 = args[1].(os.FileMode)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDirectoryFileSystem_MkdirAll_Call) Return(err error) *MockDirectoryFileSystem_MkdirAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDirectoryFileSystem_MkdirAll_Call) RunAndReturn(run func(path string, perm os.FileMode) error) *MockDirectoryFileSystem_MkdirAll_Call {
	_c.Call.Return(run)
	return _c
}

// MkdirTemp provides a mock function for the type MockDirectoryFileSystem
func (_mock *MockDirectoryFileSystem) MkdirTemp(dir string, pattern string) (string, error) {
	ret := _mock.Called(dir, pattern)

	if len(ret) == 0 {
		panic("no return value specified for MkdirTemp")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return returnFunc(dir, pattern)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(dir, pattern)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(dir, pattern)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDirectoryFileSystem_MkdirTemp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MkdirTemp'
type MockDirectoryFileSystem_MkdirTemp_Call struct {
	*mock.Call
}

// MkdirTemp is a helper method to define mock.On call
//   - dir string
//   - pattern string
func (_e *MockDirectoryFileSystem_Expecter) MkdirTemp(dir interface{}, pattern interface{}) *MockDirectoryFileSystem_MkdirTemp_Call {
	return &MockDirectoryFileSystem_MkdirTemp_Call{Call: _e.mock.On("MkdirTemp", dir, pattern)}
}

func (_c *MockDirectoryFileSystem_MkdirTemp_Call) Run(run func(dir string, pattern string)) *MockDirectoryFileSystem_MkdirTemp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDirectoryFileSystem_MkdirTemp_Call) Return(s string, err error) *MockDirectoryFileSystem_MkdirTemp_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockDirectoryFileSystem_MkdirTemp_Call) RunAndReturn(run func(dir string, pattern string) (string, error)) *MockDirectoryFileSystem_MkdirTemp_Call {
	_c.Call.Return(run)
	return _c
}
