// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"io/fs"

	mock "github.com/stretchr/testify/mock"
)

// NewMockLogFileSystem creates a new instance of MockLogFileSystem. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogFileSystem(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogFileSystem {
	mock := &MockLogFileSystem{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLogFileSystem is an autogenerated mock type for the LogFileSystem type
type MockLogFileSystem struct {
	mock.Mock
}

type MockLogFileSystem_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogFileSystem) EXPECT() *MockLogFileSystem_Expecter {
	return &MockLogFileSystem_Expecter{mock: &_m.Mock}
}

// Glob provides a mock function for the type MockLogFileSystem
func (_mock *MockLogFileSystem) Glob(logFS fs.FS, globPattern string) ([]string, error) {
	ret := _mock.Called(logFS, globPattern)

	if len(ret) == 0 {
		panic("no return value specified for Glob")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(fs.FS, string) ([]string, error)); ok {
		return returnFunc(logFS, globPattern)
	}
	if returnFunc, ok := ret.Get(0).(func(fs.FS, string) []string); ok {
		r0 = returnFunc(logFS, globPattern)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(fs.FS, string) error); ok {
		r1 = returnFunc(logFS, globPattern)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLogFileSystem_Glob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Glob'
type MockLogFileSystem_Glob_Call struct {
	*mock.Call
}

// Glob is a helper method to define mock.On call
//   - logFS fs.FS
//   - globPattern string
func (_e *MockLogFileSystem_Expecter) Glob(logFS interface{}, globPattern interface{}) *MockLogFileSystem_Glob_Call {
	return &MockLogFileSystem_Glob_Call{Call: _e.mock.On("Glob", logFS, globPattern)}
}

func (_c *MockLogFileSystem_Glob_Call) Run(run func(logFS fs.FS, globPattern string)) *MockLogFileSystem_Glob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 fs.FS
		if args[0] != nil {
			arg0 = args[0].(fs.FS)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLogFileSystem_Glob_Call) Return(strings []string, err error) *MockLogFileSystem_Glob_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockLogFileSystem_Glob_Call) RunAndReturn(run func(logFS fs.FS, globPattern string) ([]string, error)) *MockLogFileSystem_Glob_Call {
	_c.Call.Return(run)
	return _c
}

// ReadFile provides a mock function for the type MockLogFileSystem
func (_mock *MockLogFileSystem) ReadFile(logFS fs.FS, logFile string) ([]byte, error) {
	ret := _mock.Called(logFS, logFile)

	if len(ret) == 0 {
		panic("no return value specified for ReadFile")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(fs.FS, string) ([]byte, error)); ok {
		return returnFunc(logFS, logFile)
	}
	if returnFunc, ok := ret.Get(0).(func(fs.FS, string) []byte); ok {
		r0 = returnFunc(logFS, logFile)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(fs.FS, string) error); ok {
		r1 = returnFunc(logFS, logFile)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLogFileSystem_ReadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadFile'
type MockLogFileSystem_ReadFile_Call struct {
	*mock.Call
}

// ReadFile is a helper method to define mock.On call
//   - logFS fs.FS
//   - logFile string
func (_e *MockLogFileSystem_Expecter) ReadFile(logFS interface{}, logFile interface{}) *MockLogFileSystem_ReadFile_Call {
	return &MockLogFileSystem_ReadFile_Call{Call: _e.mock.On("ReadFile", logFS, logFile)}
}

func (_c *MockLogFileSystem_ReadFile_Call) Run(run func(logFS fs.FS, logFile string)) *MockLogFileSystem_ReadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 fs.FS
		if args[0] != nil {
			arg0 = args[0].(fs.FS)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLogFileSystem_ReadFile_Call) Return(bytes []byte, err error) *MockLogFileSystem_ReadFile_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockLogFileSystem_ReadFile_Call) RunAndReturn(run func(logFS fs.FS, logFile string) ([]byte, error)) *MockLogFileSystem_ReadFile_Call {
	_c.Call.Return(run)
	return _c
}
