// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockPathValidator creates a new instance of MockPathValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPathValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPathValidator {
	mock := &MockPathValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPathValidator is an autogenerated mock type for the PathValidator type
type MockPathValidator struct {
	mock.Mock
}

type MockPathValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPathValidator) EXPECT() *MockPathValidator_Expecter {
	return &MockPathValidator_Expecter{mock: &_m.Mock}
}

// ValidateFolderPath provides a mock function for the type MockPathValidator
func (_mock *MockPathValidator) ValidateFolderPath(filePath string) (string, error) {
	ret := _mock.Called(filePath)

	if len(ret) == 0 {
		panic("no return value specified for ValidateFolderPath")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(filePath)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(filePath)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(filePath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPathValidator_ValidateFolderPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateFolderPath'
type MockPathValidator_ValidateFolderPath_Call struct {
	*mock.Call
}

// ValidateFolderPath is a helper method to define mock.On call
//   - filePath string
func (_e *MockPathValidator_Expecter) ValidateFolderPath(filePath interface{}) *MockPathValidator_ValidateFolderPath_Call {
	return &MockPathValidator_ValidateFolderPath_Call{Call: _e.mock.On("ValidateFolderPath", filePath)}
}

func (_c *MockPathValidator_ValidateFolderPath_Call) Run(run func(filePath string)) *MockPathValidator_ValidateFolderPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPathValidator_ValidateFolderPath_Call) Return(s string, err error) *MockPathValidator_ValidateFolderPath_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPathValidator_ValidateFolderPath_Call) RunAndReturn(run func(filePath string) (string, error)) *MockPathValidator_ValidateFolderPath_Call {
	_c.Call.Return(run)
	return _c
}
