// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	"github.com/matlab/matlab-mcp-core-server/internal/entities"
	"github.com/matlab/matlab-mcp-core-server/internal/messages"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConfig creates a new instance of MockConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfig {
	mock := &MockConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfig is an autogenerated mock type for the Config type
type MockConfig struct {
	mock.Mock
}

type MockConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfig) EXPECT() *MockConfig_Expecter {
	return &MockConfig_Expecter{mock: &_m.Mock}
}

// AsPIISafeJSONString provides a mock function for the type MockConfig
func (_mock *MockConfig) AsPIISafeJSONString() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AsPIISafeJSONString")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConfig_AsPIISafeJSONString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsPIISafeJSONString'
type MockConfig_AsPIISafeJSONString_Call struct {
	*mock.Call
}

// AsPIISafeJSONString is a helper method to define mock.On call
func (_e *MockConfig_Expecter) AsPIISafeJSONString() *MockConfig_AsPIISafeJSONString_Call {
	return &MockConfig_AsPIISafeJSONString_Call{Call: _e.mock.On("AsPIISafeJSONString")}
}

func (_c *MockConfig_AsPIISafeJSONString_Call) Run(run func()) *MockConfig_AsPIISafeJSONString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_AsPIISafeJSONString_Call) Return(s string) *MockConfig_AsPIISafeJSONString_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockConfig_AsPIISafeJSONString_Call) RunAndReturn(run func() string) *MockConfig_AsPIISafeJSONString_Call {
	_c.Call.Return(run)
	return _c
}

// BaseDir provides a mock function for the type MockConfig
func (_mock *MockConfig) BaseDir() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BaseDir")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConfig_BaseDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BaseDir'
type MockConfig_BaseDir_Call struct {
	*mock.Call
}

// BaseDir is a helper method to define mock.On call
func (_e *MockConfig_Expecter) BaseDir() *MockConfig_BaseDir_Call {
	return &MockConfig_BaseDir_Call{Call: _e.mock.On("BaseDir")}
}

func (_c *MockConfig_BaseDir_Call) Run(run func()) *MockConfig_BaseDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_BaseDir_Call) Return(s string) *MockConfig_BaseDir_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockConfig_BaseDir_Call) RunAndReturn(run func() string) *MockConfig_BaseDir_Call {
	_c.Call.Return(run)
	return _c
}

// DisableTelemetry provides a mock function for the type MockConfig
func (_mock *MockConfig) DisableTelemetry() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DisableTelemetry")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockConfig_DisableTelemetry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisableTelemetry'
type MockConfig_DisableTelemetry_Call struct {
	*mock.Call
}

// DisableTelemetry is a helper method to define mock.On call
func (_e *MockConfig_Expecter) DisableTelemetry() *MockConfig_DisableTelemetry_Call {
	return &MockConfig_DisableTelemetry_Call{Call: _e.mock.On("DisableTelemetry")}
}

func (_c *MockConfig_DisableTelemetry_Call) Run(run func()) *MockConfig_DisableTelemetry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_DisableTelemetry_Call) Return(b bool) *MockConfig_DisableTelemetry_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockConfig_DisableTelemetry_Call) RunAndReturn(run func() bool) *MockConfig_DisableTelemetry_Call {
	_c.Call.Return(run)
	return _c
}

// DuplicateLogsToStderr provides a mock function for the type MockConfig
func (_mock *MockConfig) DuplicateLogsToStderr() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DuplicateLogsToStderr")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockConfig_DuplicateLogsToStderr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DuplicateLogsToStderr'
type MockConfig_DuplicateLogsToStderr_Call struct {
	*mock.Call
}

// DuplicateLogsToStderr is a helper method to define mock.On call
func (_e *MockConfig_Expecter) DuplicateLogsToStderr() *MockConfig_DuplicateLogsToStderr_Call {
	return &MockConfig_DuplicateLogsToStderr_Call{Call: _e.mock.On("DuplicateLogsToStderr")}
}

func (_c *MockConfig_DuplicateLogsToStderr_Call) Run(run func()) *MockConfig_DuplicateLogsToStderr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_DuplicateLogsToStderr_Call) Return(b bool) *MockConfig_DuplicateLogsToStderr_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockConfig_DuplicateLogsToStderr_Call) RunAndReturn(run func() bool) *MockConfig_DuplicateLogsToStderr_Call {
	_c.Call.Return(run)
	return _c
}

// EmbeddedConnectorDetailsTimeout provides a mock function for the type MockConfig
func (_mock *MockConfig) EmbeddedConnectorDetailsTimeout() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for EmbeddedConnectorDetailsTimeout")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockConfig_EmbeddedConnectorDetailsTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EmbeddedConnectorDetailsTimeout'
type MockConfig_EmbeddedConnectorDetailsTimeout_Call struct {
	*mock.Call
}

// EmbeddedConnectorDetailsTimeout is a helper method to define mock.On call
func (_e *MockConfig_Expecter) EmbeddedConnectorDetailsTimeout() *MockConfig_EmbeddedConnectorDetailsTimeout_Call {
	return &MockConfig_EmbeddedConnectorDetailsTimeout_Call{Call: _e.mock.On("EmbeddedConnectorDetailsTimeout")}
}

func (_c *MockConfig_EmbeddedConnectorDetailsTimeout_Call) Run(run func()) *MockConfig_EmbeddedConnectorDetailsTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_EmbeddedConnectorDetailsTimeout_Call) Return(duration time.Duration) *MockConfig_EmbeddedConnectorDetailsTimeout_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockConfig_EmbeddedConnectorDetailsTimeout_Call) RunAndReturn(run func() time.Duration) *MockConfig_EmbeddedConnectorDetailsTimeout_Call {
	_c.Call.Return(run)
	return _c
}

// ExtensionFiles provides a mock function for the type MockConfig
func (_mock *MockConfig) ExtensionFiles() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ExtensionFiles")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockConfig_ExtensionFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtensionFiles'
type MockConfig_ExtensionFiles_Call struct {
	*mock.Call
}

// ExtensionFiles is a helper method to define mock.On call
func (_e *MockConfig_Expecter) ExtensionFiles() *MockConfig_ExtensionFiles_Call {
	return &MockConfig_ExtensionFiles_Call{Call: _e.mock.On("ExtensionFiles")}
}

func (_c *MockConfig_ExtensionFiles_Call) Run(run func()) *MockConfig_ExtensionFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_ExtensionFiles_Call) Return(strings []string) *MockConfig_ExtensionFiles_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockConfig_ExtensionFiles_Call) RunAndReturn(run func() []string) *MockConfig_ExtensionFiles_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockConfig
func (_mock *MockConfig) Get(key string) (any, messages.Error) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 any
	var r1 messages.Error
	if returnFunc, ok := ret.Get(0).(func(string) (any, messages.Error)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) any); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) messages.Error); ok {
		r1 = returnFunc(key)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(messages.Error)
		}
	}
	return r0, r1
}

// MockConfig_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockConfig_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *MockConfig_Expecter) Get(key interface{}) *MockConfig_Get_Call {
	return &MockConfig_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *MockConfig_Get_Call) Run(run func(key string)) *MockConfig_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfig_Get_Call) Return(v any, error messages.Error) *MockConfig_Get_Call {
	_c.Call.Return(v, error)
	return _c
}

func (_c *MockConfig_Get_Call) RunAndReturn(run func(key string) (any, messages.Error)) *MockConfig_Get_Call {
	_c.Call.Return(run)
	return _c
}

// HelpMode provides a mock function for the type MockConfig
func (_mock *MockConfig) HelpMode() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HelpMode")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockConfig_HelpMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HelpMode'
type MockConfig_HelpMode_Call struct {
	*mock.Call
}

// HelpMode is a helper method to define mock.On call
func (_e *MockConfig_Expecter) HelpMode() *MockConfig_HelpMode_Call {
	return &MockConfig_HelpMode_Call{Call: _e.mock.On("HelpMode")}
}

func (_c *MockConfig_HelpMode_Call) Run(run func()) *MockConfig_HelpMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_HelpMode_Call) Return(b bool) *MockConfig_HelpMode_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockConfig_HelpMode_Call) RunAndReturn(run func() bool) *MockConfig_HelpMode_Call {
	_c.Call.Return(run)
	return _c
}

// InitializeMATLABOnStartup provides a mock function for the type MockConfig
func (_mock *MockConfig) InitializeMATLABOnStartup() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for InitializeMATLABOnStartup")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockConfig_InitializeMATLABOnStartup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitializeMATLABOnStartup'
type MockConfig_InitializeMATLABOnStartup_Call struct {
	*mock.Call
}

// InitializeMATLABOnStartup is a helper method to define mock.On call
func (_e *MockConfig_Expecter) InitializeMATLABOnStartup() *MockConfig_InitializeMATLABOnStartup_Call {
	return &MockConfig_InitializeMATLABOnStartup_Call{Call: _e.mock.On("InitializeMATLABOnStartup")}
}

func (_c *MockConfig_InitializeMATLABOnStartup_Call) Run(run func()) *MockConfig_InitializeMATLABOnStartup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_InitializeMATLABOnStartup_Call) Return(b bool) *MockConfig_InitializeMATLABOnStartup_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockConfig_InitializeMATLABOnStartup_Call) RunAndReturn(run func() bool) *MockConfig_InitializeMATLABOnStartup_Call {
	_c.Call.Return(run)
	return _c
}

// LogLevel provides a mock function for the type MockConfig
func (_mock *MockConfig) LogLevel() entities.LogLevel {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for LogLevel")
	}

	var r0 entities.LogLevel
	if returnFunc, ok := ret.Get(0).(func() entities.LogLevel); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(entities.LogLevel)
	}
	return r0
}

// MockConfig_LogLevel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogLevel'
type MockConfig_LogLevel_Call struct {
	*mock.Call
}

// LogLevel is a helper method to define mock.On call
func (_e *MockConfig_Expecter) LogLevel() *MockConfig_LogLevel_Call {
	return &MockConfig_LogLevel_Call{Call: _e.mock.On("LogLevel")}
}

func (_c *MockConfig_LogLevel_Call) Run(run func()) *MockConfig_LogLevel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_LogLevel_Call) Return(logLevel entities.LogLevel) *MockConfig_LogLevel_Call {
	_c.Call.Return(logLevel)
	return _c
}

func (_c *MockConfig_LogLevel_Call) RunAndReturn(run func() entities.LogLevel) *MockConfig_LogLevel_Call {
	_c.Call.Return(run)
	return _c
}

// MATLABSessionConnectionDetails provides a mock function for the type MockConfig
func (_mock *MockConfig) MATLABSessionConnectionDetails() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MATLABSessionConnectionDetails")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConfig_MATLABSessionConnectionDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MATLABSessionConnectionDetails'
type MockConfig_MATLABSessionConnectionDetails_Call struct {
	*mock.Call
}

// MATLABSessionConnectionDetails is a helper method to define mock.On call
func (_e *MockConfig_Expecter) MATLABSessionConnectionDetails() *MockConfig_MATLABSessionConnectionDetails_Call {
	return &MockConfig_MATLABSessionConnectionDetails_Call{Call: _e.mock.On("MATLABSessionConnectionDetails")}
}

func (_c *MockConfig_MATLABSessionConnectionDetails_Call) Run(run func()) *MockConfig_MATLABSessionConnectionDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_MATLABSessionConnectionDetails_Call) Return(s string) *MockConfig_MATLABSessionConnectionDetails_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockConfig_MATLABSessionConnectionDetails_Call) RunAndReturn(run func() string) *MockConfig_MATLABSessionConnectionDetails_Call {
	_c.Call.Return(run)
	return _c
}

// MATLABSessionConnectionTimeout provides a mock function for the type MockConfig
func (_mock *MockConfig) MATLABSessionConnectionTimeout() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MATLABSessionConnectionTimeout")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockConfig_MATLABSessionConnectionTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MATLABSessionConnectionTimeout'
type MockConfig_MATLABSessionConnectionTimeout_Call struct {
	*mock.Call
}

// MATLABSessionConnectionTimeout is a helper method to define mock.On call
func (_e *MockConfig_Expecter) MATLABSessionConnectionTimeout() *MockConfig_MATLABSessionConnectionTimeout_Call {
	return &MockConfig_MATLABSessionConnectionTimeout_Call{Call: _e.mock.On("MATLABSessionConnectionTimeout")}
}

func (_c *MockConfig_MATLABSessionConnectionTimeout_Call) Run(run func()) *MockConfig_MATLABSessionConnectionTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_MATLABSessionConnectionTimeout_Call) Return(duration time.Duration) *MockConfig_MATLABSessionConnectionTimeout_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockConfig_MATLABSessionConnectionTimeout_Call) RunAndReturn(run func() time.Duration) *MockConfig_MATLABSessionConnectionTimeout_Call {
	_c.Call.Return(run)
	return _c
}

// MATLABSessionDiscoveryTimeout provides a mock function for the type MockConfig
func (_mock *MockConfig) MATLABSessionDiscoveryTimeout() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MATLABSessionDiscoveryTimeout")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockConfig_MATLABSessionDiscoveryTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MATLABSessionDiscoveryTimeout'
type MockConfig_MATLABSessionDiscoveryTimeout_Call struct {
	*mock.Call
}

// MATLABSessionDiscoveryTimeout is a helper method to define mock.On call
func (_e *MockConfig_Expecter) MATLABSessionDiscoveryTimeout() *MockConfig_MATLABSessionDiscoveryTimeout_Call {
	return &MockConfig_MATLABSessionDiscoveryTimeout_Call{Call: _e.mock.On("MATLABSessionDiscoveryTimeout")}
}

func (_c *MockConfig_MATLABSessionDiscoveryTimeout_Call) Run(run func()) *MockConfig_MATLABSessionDiscoveryTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_MATLABSessionDiscoveryTimeout_Call) Return(duration time.Duration) *MockConfig_MATLABSessionDiscoveryTimeout_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockConfig_MATLABSessionDiscoveryTimeout_Call) RunAndReturn(run func() time.Duration) *MockConfig_MATLABSessionDiscoveryTimeout_Call {
	_c.Call.Return(run)
	return _c
}

// MATLABSessionMode provides a mock function for the type MockConfig
func (_mock *MockConfig) MATLABSessionMode() entities.MATLABSessionMode {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MATLABSessionMode")
	}

	var r0 entities.MATLABSessionMode
	if returnFunc, ok := ret.Get(0).(func() entities.MATLABSessionMode); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(entities.MATLABSessionMode)
	}
	return r0
}

// MockConfig_MATLABSessionMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MATLABSessionMode'
type MockConfig_MATLABSessionMode_Call struct {
	*mock.Call
}

// MATLABSessionMode is a helper method to define mock.On call
func (_e *MockConfig_Expecter) MATLABSessionMode() *MockConfig_MATLABSessionMode_Call {
	return &MockConfig_MATLABSessionMode_Call{Call: _e.mock.On("MATLABSessionMode")}
}

func (_c *MockConfig_MATLABSessionMode_Call) Run(run func()) *MockConfig_MATLABSessionMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_MATLABSessionMode_Call) Return(mATLABSessionMode entities.MATLABSessionMode) *MockConfig_MATLABSessionMode_Call {
	_c.Call.Return(mATLABSessionMode)
	return _c
}

func (_c *MockConfig_MATLABSessionMode_Call) RunAndReturn(run func() entities.MATLABSessionMode) *MockConfig_MATLABSessionMode_Call {
	_c.Call.Return(run)
	return _c
}

// PreferredLocalMATLABRoot provides a mock function for the type MockConfig
func (_mock *MockConfig) PreferredLocalMATLABRoot() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PreferredLocalMATLABRoot")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConfig_PreferredLocalMATLABRoot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PreferredLocalMATLABRoot'
type MockConfig_PreferredLocalMATLABRoot_Call struct {
	*mock.Call
}

// PreferredLocalMATLABRoot is a helper method to define mock.On call
func (_e *MockConfig_Expecter) PreferredLocalMATLABRoot() *MockConfig_PreferredLocalMATLABRoot_Call {
	return &MockConfig_PreferredLocalMATLABRoot_Call{Call: _e.mock.On("PreferredLocalMATLABRoot")}
}

func (_c *MockConfig_PreferredLocalMATLABRoot_Call) Run(run func()) *MockConfig_PreferredLocalMATLABRoot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_PreferredLocalMATLABRoot_Call) Return(s string) *MockConfig_PreferredLocalMATLABRoot_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockConfig_PreferredLocalMATLABRoot_Call) RunAndReturn(run func() string) *MockConfig_PreferredLocalMATLABRoot_Call {
	_c.Call.Return(run)
	return _c
}

// PreferredMATLABStartingDirectory provides a mock function for the type MockConfig
func (_mock *MockConfig) PreferredMATLABStartingDirectory() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PreferredMATLABStartingDirectory")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConfig_PreferredMATLABStartingDirectory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PreferredMATLABStartingDirectory'
type MockConfig_PreferredMATLABStartingDirectory_Call struct {
	*mock.Call
}

// PreferredMATLABStartingDirectory is a helper method to define mock.On call
func (_e *MockConfig_Expecter) PreferredMATLABStartingDirectory() *MockConfig_PreferredMATLABStartingDirectory_Call {
	return &MockConfig_PreferredMATLABStartingDirectory_Call{Call: _e.mock.On("PreferredMATLABStartingDirectory")}
}

func (_c *MockConfig_PreferredMATLABStartingDirectory_Call) Run(run func()) *MockConfig_PreferredMATLABStartingDirectory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_PreferredMATLABStartingDirectory_Call) Return(s string) *MockConfig_PreferredMATLABStartingDirectory_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockConfig_PreferredMATLABStartingDirectory_Call) RunAndReturn(run func() string) *MockConfig_PreferredMATLABStartingDirectory_Call {
	_c.Call.Return(run)
	return _c
}

// RecordToLogger provides a mock function for the type MockConfig
func (_mock *MockConfig) RecordToLogger(logger entities.Logger) {
	_mock.Called(logger)
	return
}

// MockConfig_RecordToLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordToLogger'
type MockConfig_RecordToLogger_Call struct {
	*mock.Call
}

// RecordToLogger is a helper method to define mock.On call
//   - logger entities.Logger
func (_e *MockConfig_Expecter) RecordToLogger(logger interface{}) *MockConfig_RecordToLogger_Call {
	return &MockConfig_RecordToLogger_Call{Call: _e.mock.On("RecordToLogger", logger)}
}

func (_c *MockConfig_RecordToLogger_Call) Run(run func(logger entities.Logger)) *MockConfig_RecordToLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 entities.Logger
		if args[0] != nil {
			arg0 = args[0].(entities.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfig_RecordToLogger_Call) Return() *MockConfig_RecordToLogger_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConfig_RecordToLogger_Call) RunAndReturn(run func(logger entities.Logger)) *MockConfig_RecordToLogger_Call {
	_c.Run(run)
	return _c
}

// ServerInstanceID provides a mock function for the type MockConfig
func (_mock *MockConfig) ServerInstanceID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ServerInstanceID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConfig_ServerInstanceID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServerInstanceID'
type MockConfig_ServerInstanceID_Call struct {
	*mock.Call
}

// ServerInstanceID is a helper method to define mock.On call
func (_e *MockConfig_Expecter) ServerInstanceID() *MockConfig_ServerInstanceID_Call {
	return &MockConfig_ServerInstanceID_Call{Call: _e.mock.On("ServerInstanceID")}
}

func (_c *MockConfig_ServerInstanceID_Call) Run(run func()) *MockConfig_ServerInstanceID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_ServerInstanceID_Call) Return(s string) *MockConfig_ServerInstanceID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockConfig_ServerInstanceID_Call) RunAndReturn(run func() string) *MockConfig_ServerInstanceID_Call {
	_c.Call.Return(run)
	return _c
}

// SetupMATLABMode provides a mock function for the type MockConfig
func (_mock *MockConfig) SetupMATLABMode() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SetupMATLABMode")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockConfig_SetupMATLABMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetupMATLABMode'
type MockConfig_SetupMATLABMode_Call struct {
	*mock.Call
}

// SetupMATLABMode is a helper method to define mock.On call
func (_e *MockConfig_Expecter) SetupMATLABMode() *MockConfig_SetupMATLABMode_Call {
	return &MockConfig_SetupMATLABMode_Call{Call: _e.mock.On("SetupMATLABMode")}
}

func (_c *MockConfig_SetupMATLABMode_Call) Run(run func()) *MockConfig_SetupMATLABMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_SetupMATLABMode_Call) Return(b bool) *MockConfig_SetupMATLABMode_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockConfig_SetupMATLABMode_Call) RunAndReturn(run func() bool) *MockConfig_SetupMATLABMode_Call {
	_c.Call.Return(run)
	return _c
}

// ShouldShowMATLABDesktop provides a mock function for the type MockConfig
func (_mock *MockConfig) ShouldShowMATLABDesktop() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ShouldShowMATLABDesktop")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockConfig_ShouldShowMATLABDesktop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShouldShowMATLABDesktop'
type MockConfig_ShouldShowMATLABDesktop_Call struct {
	*mock.Call
}

// ShouldShowMATLABDesktop is a helper method to define mock.On call
func (_e *MockConfig_Expecter) ShouldShowMATLABDesktop() *MockConfig_ShouldShowMATLABDesktop_Call {
	return &MockConfig_ShouldShowMATLABDesktop_Call{Call: _e.mock.On("ShouldShowMATLABDesktop")}
}

func (_c *MockConfig_ShouldShowMATLABDesktop_Call) Run(run func()) *MockConfig_ShouldShowMATLABDesktop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_ShouldShowMATLABDesktop_Call) Return(b bool) *MockConfig_ShouldShowMATLABDesktop_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockConfig_ShouldShowMATLABDesktop_Call) RunAndReturn(run func() bool) *MockConfig_ShouldShowMATLABDesktop_Call {
	_c.Call.Return(run)
	return _c
}

// SpecifiedParameters provides a mock function for the type MockConfig
func (_mock *MockConfig) SpecifiedParameters() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SpecifiedParameters")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockConfig_SpecifiedParameters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SpecifiedParameters'
type MockConfig_SpecifiedParameters_Call struct {
	*mock.Call
}

// SpecifiedParameters is a helper method to define mock.On call
func (_e *MockConfig_Expecter) SpecifiedParameters() *MockConfig_SpecifiedParameters_Call {
	return &MockConfig_SpecifiedParameters_Call{Call: _e.mock.On("SpecifiedParameters")}
}

func (_c *MockConfig_SpecifiedParameters_Call) Run(run func()) *MockConfig_SpecifiedParameters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_SpecifiedParameters_Call) Return(strings []string) *MockConfig_SpecifiedParameters_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockConfig_SpecifiedParameters_Call) RunAndReturn(run func() []string) *MockConfig_SpecifiedParameters_Call {
	_c.Call.Return(run)
	return _c
}

// TelemetryCollectionInterval provides a mock function for the type MockConfig
func (_mock *MockConfig) TelemetryCollectionInterval() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TelemetryCollectionInterval")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockConfig_TelemetryCollectionInterval_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TelemetryCollectionInterval'
type MockConfig_TelemetryCollectionInterval_Call struct {
	*mock.Call
}

// TelemetryCollectionInterval is a helper method to define mock.On call
func (_e *MockConfig_Expecter) TelemetryCollectionInterval() *MockConfig_TelemetryCollectionInterval_Call {
	return &MockConfig_TelemetryCollectionInterval_Call{Call: _e.mock.On("TelemetryCollectionInterval")}
}

func (_c *MockConfig_TelemetryCollectionInterval_Call) Run(run func()) *MockConfig_TelemetryCollectionInterval_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_TelemetryCollectionInterval_Call) Return(duration time.Duration) *MockConfig_TelemetryCollectionInterval_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockConfig_TelemetryCollectionInterval_Call) RunAndReturn(run func() time.Duration) *MockConfig_TelemetryCollectionInterval_Call {
	_c.Call.Return(run)
	return _c
}

// TelemetryCollectorEndpoint provides a mock function for the type MockConfig
func (_mock *MockConfig) TelemetryCollectorEndpoint() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TelemetryCollectorEndpoint")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConfig_TelemetryCollectorEndpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TelemetryCollectorEndpoint'
type MockConfig_TelemetryCollectorEndpoint_Call struct {
	*mock.Call
}

// TelemetryCollectorEndpoint is a helper method to define mock.On call
func (_e *MockConfig_Expecter) TelemetryCollectorEndpoint() *MockConfig_TelemetryCollectorEndpoint_Call {
	return &MockConfig_TelemetryCollectorEndpoint_Call{Call: _e.mock.On("TelemetryCollectorEndpoint")}
}

func (_c *MockConfig_TelemetryCollectorEndpoint_Call) Run(run func()) *MockConfig_TelemetryCollectorEndpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_TelemetryCollectorEndpoint_Call) Return(s string) *MockConfig_TelemetryCollectorEndpoint_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockConfig_TelemetryCollectorEndpoint_Call) RunAndReturn(run func() string) *MockConfig_TelemetryCollectorEndpoint_Call {
	_c.Call.Return(run)
	return _c
}

// TelemetryCollectorEndpointInsecure provides a mock function for the type MockConfig
func (_mock *MockConfig) TelemetryCollectorEndpointInsecure() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TelemetryCollectorEndpointInsecure")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockConfig_TelemetryCollectorEndpointInsecure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TelemetryCollectorEndpointInsecure'
type MockConfig_TelemetryCollectorEndpointInsecure_Call struct {
	*mock.Call
}

// TelemetryCollectorEndpointInsecure is a helper method to define mock.On call
func (_e *MockConfig_Expecter) TelemetryCollectorEndpointInsecure() *MockConfig_TelemetryCollectorEndpointInsecure_Call {
	return &MockConfig_TelemetryCollectorEndpointInsecure_Call{Call: _e.mock.On("TelemetryCollectorEndpointInsecure")}
}

func (_c *MockConfig_TelemetryCollectorEndpointInsecure_Call) Run(run func()) *MockConfig_TelemetryCollectorEndpointInsecure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_TelemetryCollectorEndpointInsecure_Call) Return(b bool) *MockConfig_TelemetryCollectorEndpointInsecure_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockConfig_TelemetryCollectorEndpointInsecure_Call) RunAndReturn(run func() bool) *MockConfig_TelemetryCollectorEndpointInsecure_Call {
	_c.Call.Return(run)
	return _c
}

// UseSingleMATLABSession provides a mock function for the type MockConfig
func (_mock *MockConfig) UseSingleMATLABSession() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UseSingleMATLABSession")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockConfig_UseSingleMATLABSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UseSingleMATLABSession'
type MockConfig_UseSingleMATLABSession_Call struct {
	*mock.Call
}

// UseSingleMATLABSession is a helper method to define mock.On call
func (_e *MockConfig_Expecter) UseSingleMATLABSession() *MockConfig_UseSingleMATLABSession_Call {
	return &MockConfig_UseSingleMATLABSession_Call{Call: _e.mock.On("UseSingleMATLABSession")}
}

func (_c *MockConfig_UseSingleMATLABSession_Call) Run(run func()) *MockConfig_UseSingleMATLABSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_UseSingleMATLABSession_Call) Return(b bool) *MockConfig_UseSingleMATLABSession_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockConfig_UseSingleMATLABSession_Call) RunAndReturn(run func() bool) *MockConfig_UseSingleMATLABSession_Call {
	_c.Call.Return(run)
	return _c
}

// Version provides a mock function for the type MockConfig
func (_mock *MockConfig) Version() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Version")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConfig_Version_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Version'
type MockConfig_Version_Call struct {
	*mock.Call
}

// Version is a helper method to define mock.On call
func (_e *MockConfig_Expecter) Version() *MockConfig_Version_Call {
	return &MockConfig_Version_Call{Call: _e.mock.On("Version")}
}

func (_c *MockConfig_Version_Call) Run(run func()) *MockConfig_Version_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_Version_Call) Return(s string) *MockConfig_Version_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockConfig_Version_Call) RunAndReturn(run func() string) *MockConfig_Version_Call {
	_c.Call.Return(run)
	return _c
}

// VersionMode provides a mock function for the type MockConfig
func (_mock *MockConfig) VersionMode() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for VersionMode")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockConfig_VersionMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VersionMode'
type MockConfig_VersionMode_Call struct {
	*mock.Call
}

// VersionMode is a helper method to define mock.On call
func (_e *MockConfig_Expecter) VersionMode() *MockConfig_VersionMode_Call {
	return &MockConfig_VersionMode_Call{Call: _e.mock.On("VersionMode")}
}

func (_c *MockConfig_VersionMode_Call) Run(run func()) *MockConfig_VersionMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_VersionMode_Call) Return(b bool) *MockConfig_VersionMode_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockConfig_VersionMode_Call) RunAndReturn(run func() bool) *MockConfig_VersionMode_Call {
	_c.Call.Return(run)
	return _c
}

// WatchdogMode provides a mock function for the type MockConfig
func (_mock *MockConfig) WatchdogMode() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for WatchdogMode")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockConfig_WatchdogMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WatchdogMode'
type MockConfig_WatchdogMode_Call struct {
	*mock.Call
}

// WatchdogMode is a helper method to define mock.On call
func (_e *MockConfig_Expecter) WatchdogMode() *MockConfig_WatchdogMode_Call {
	return &MockConfig_WatchdogMode_Call{Call: _e.mock.On("WatchdogMode")}
}

func (_c *MockConfig_WatchdogMode_Call) Run(run func()) *MockConfig_WatchdogMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_WatchdogMode_Call) Return(b bool) *MockConfig_WatchdogMode_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockConfig_WatchdogMode_Call) RunAndReturn(run func() bool) *MockConfig_WatchdogMode_Call {
	_c.Call.Return(run)
	return _c
}
