// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/tools/singlesession/custom/definition"
	"github.com/matlab/matlab-mcp-core-server/internal/messages"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLoader creates a new instance of MockLoader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoader {
	mock := &MockLoader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLoader is an autogenerated mock type for the Loader type
type MockLoader struct {
	mock.Mock
}

type MockLoader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoader) EXPECT() *MockLoader_Expecter {
	return &MockLoader_Expecter{mock: &_m.Mock}
}

// Load provides a mock function for the type MockLoader
func (_mock *MockLoader) Load(filePath string) ([]definition.ValidatedTool, messages.Error) {
	ret := _mock.Called(filePath)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 []definition.ValidatedTool
	var r1 messages.Error
	if returnFunc, ok := ret.Get(0).(func(string) ([]definition.ValidatedTool, messages.Error)); ok {
		return returnFunc(filePath)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []definition.ValidatedTool); ok {
		r0 = returnFunc(filePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]definition.ValidatedTool)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) messages.Error); ok {
		r1 = returnFunc(filePath)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(messages.Error)
		}
	}
	return r0, r1
}

// MockLoader_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockLoader_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - filePath string
func (_e *MockLoader_Expecter) Load(filePath interface{}) *MockLoader_Load_Call {
	return &MockLoader_Load_Call{Call: _e.mock.On("Load", filePath)}
}

func (_c *MockLoader_Load_Call) Run(run func(filePath string)) *MockLoader_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLoader_Load_Call) Return(validatedTools []definition.ValidatedTool, error messages.Error) *MockLoader_Load_Call {
	_c.Call.Return(validatedTools, error)
	return _c
}

func (_c *MockLoader_Load_Call) RunAndReturn(run func(filePath string) ([]definition.ValidatedTool, messages.Error)) *MockLoader_Load_Call {
	_c.Call.Return(run)
	return _c
}
