// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/tools/singlesession/custom/definition"
	mock "github.com/stretchr/testify/mock"
)

// NewMockToolValidator creates a new instance of MockToolValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockToolValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockToolValidator {
	mock := &MockToolValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockToolValidator is an autogenerated mock type for the ToolValidator type
type MockToolValidator struct {
	mock.Mock
}

type MockToolValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockToolValidator) EXPECT() *MockToolValidator_Expecter {
	return &MockToolValidator_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function for the type MockToolValidator
func (_mock *MockToolValidator) Validate(toolDefinition definition.Tool, signatures map[string]definition.Signature) (definition.ValidatedTool, error) {
	ret := _mock.Called(toolDefinition, signatures)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 definition.ValidatedTool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(definition.Tool, map[string]definition.Signature) (definition.ValidatedTool, error)); ok {
		return returnFunc(toolDefinition, signatures)
	}
	if returnFunc, ok := ret.Get(0).(func(definition.Tool, map[string]definition.Signature) definition.ValidatedTool); ok {
		r0 = returnFunc(toolDefinition, signatures)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(definition.ValidatedTool)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(definition.Tool, map[string]definition.Signature) error); ok {
		r1 = returnFunc(toolDefinition, signatures)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockToolValidator_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockToolValidator_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - toolDefinition definition.Tool
//   - signatures map[string]definition.Signature
func (_e *MockToolValidator_Expecter) Validate(toolDefinition interface{}, signatures interface{}) *MockToolValidator_Validate_Call {
	return &MockToolValidator_Validate_Call{Call: _e.mock.On("Validate", toolDefinition, signatures)}
}

func (_c *MockToolValidator_Validate_Call) Run(run func(toolDefinition definition.Tool, signatures map[string]definition.Signature)) *MockToolValidator_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 definition.Tool
		if args[0] != nil {
			arg0 = args[0].(definition.Tool)
		}
		var arg1 map[string]definition.Signature
		if args[1] != nil {
			arg1 = args[1].(map[string]definition.Signature)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockToolValidator_Validate_Call) Return(validatedTool definition.ValidatedTool, err error) *MockToolValidator_Validate_Call {
	_c.Call.Return(validatedTool, err)
	return _c
}

func (_c *MockToolValidator_Validate_Call) RunAndReturn(run func(toolDefinition definition.Tool, signatures map[string]definition.Signature) (definition.ValidatedTool, error)) *MockToolValidator_Validate_Call {
	_c.Call.Return(run)
	return _c
}
