classdef shareMATLABSessionTest < matlab.mock.TestCase
    %shareMATLABSessionTest Tests for mcpcoreserver.internal.shareMATLABSession
    %   This test class verifies that shareMATLABSession correctly
    %   manages the application data folder and its permissions.

    % Copyright 2026 The MathWorks, Inc.

    methods (Test)
        function testShareMATLABSession_HappyPath(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.DoNothing

            [mockAppData, appDataBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.appdata.AppDataLocator, ...
                Strict=true ...
            );
            [mockFSAdaptor, FSAdaptorBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.fs.FSAdaptor, ...
                Strict=true ...
            );
            [mockConnector, connectorBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.connector.ConnectorAdaptor, ...
                Strict=true ...
            );
            [mockFSFacade, FSFacadeBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockConnectorFacade, connectorFacadeBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.connector.ConnectorFacade, ...
                Strict=true ...
            );

            expectedAppDataFolder = fullfile("home", "user", ".MathWorks", "MATLABMCPCoreServer");
            expectedV1Folder = fullfile(expectedAppDataFolder, "v1");
            expectedSessionDetailsPath = fullfile(expectedV1Folder, "sessionDetails.json");
            expectedPort = 31415;
            expectedCert = fullfile("home", "user", ".matlab", "connector.pem");
            expectedApiKey = "test-api-key";
            expectedPid = 12345;
            expectedSessionDetails = struct( ...
                "port", expectedPort, ...
                "certificate", expectedCert, ...
                "apiKey", expectedApiKey, ...
                "pid", expectedPid ...
            );
            expectedJson = jsonencode(expectedSessionDetails, PrettyPrint=true);

            when( ...
                connectorFacadeBehavior.ensureServiceOn().withExactInputs(), ...
                DoNothing ...
            );
            when( ...
                appDataBehavior.getAppDataFolder().withExactInputs(), ...
                AssignOutputs(expectedAppDataFolder) ...
            );
            when( ...
                FSAdaptorBehavior.ensureSecureFolder(expectedAppDataFolder), ...
                DoNothing ...
            );
            when( ...
                FSAdaptorBehavior.ensureSecureFolder(expectedV1Folder), ...
                DoNothing ...
            );
            when( ...
                connectorBehavior.getConnectionDetails().withAnyInputs(), ...
                AssignOutputs(expectedSessionDetails) ...
            );
            when( ...
                FSAdaptorBehavior.ensureSecureFile(expectedSessionDetailsPath), ...
                DoNothing ...
            );
            when( ...
                FSFacadeBehavior.writelines(expectedJson, expectedSessionDetailsPath), ...
                DoNothing ...
            );

            % Act
            mcpcoreserver.internal.shareMATLABSession( ...
                AppDataLocator=mockAppData, ...
                FSAdaptor=mockFSAdaptor, ...
                FSFacade=mockFSFacade, ...
                ConnectorAdaptor=mockConnector, ...
                ConnectorFacade=mockConnectorFacade ...
            );

            % Assert
            testCase.verifyCalled( ...
                connectorFacadeBehavior.ensureServiceOn().withExactInputs(), ...
                "ensureServiceOn should be called to start the connector" ...
            );
            testCase.verifyCalled( ...
                FSAdaptorBehavior.ensureSecureFolder(expectedAppDataFolder), ...
                "ensureSecureFolder should be called with the app data folder path" ...
            );
            testCase.verifyCalled( ...
                FSAdaptorBehavior.ensureSecureFolder(expectedV1Folder), ...
                "ensureSecureFolder should be called with the v1 folder path" ...
            );
            testCase.verifyCalled( ...
                FSAdaptorBehavior.ensureSecureFile(expectedSessionDetailsPath), ...
                "ensureSecureFile should be called for sessionDetails.json" ...
            );
            testCase.verifyCalled( ...
                FSFacadeBehavior.writelines(expectedJson, expectedSessionDetailsPath), ...
                "writelines should be called to write JSON content" ...
            );
        end
    end

end
