// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockAppDataDirGetter creates a new instance of MockAppDataDirGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAppDataDirGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAppDataDirGetter {
	mock := &MockAppDataDirGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAppDataDirGetter is an autogenerated mock type for the AppDataDirGetter type
type MockAppDataDirGetter struct {
	mock.Mock
}

type MockAppDataDirGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAppDataDirGetter) EXPECT() *MockAppDataDirGetter_Expecter {
	return &MockAppDataDirGetter_Expecter{mock: &_m.Mock}
}

// AppDataDir provides a mock function for the type MockAppDataDirGetter
func (_mock *MockAppDataDirGetter) AppDataDir() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AppDataDir")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAppDataDirGetter_AppDataDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppDataDir'
type MockAppDataDirGetter_AppDataDir_Call struct {
	*mock.Call
}

// AppDataDir is a helper method to define mock.On call
func (_e *MockAppDataDirGetter_Expecter) AppDataDir() *MockAppDataDirGetter_AppDataDir_Call {
	return &MockAppDataDirGetter_AppDataDir_Call{Call: _e.mock.On("AppDataDir")}
}

func (_c *MockAppDataDirGetter_AppDataDir_Call) Run(run func()) *MockAppDataDirGetter_AppDataDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAppDataDirGetter_AppDataDir_Call) Return(s string, err error) *MockAppDataDirGetter_AppDataDir_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAppDataDirGetter_AppDataDir_Call) RunAndReturn(run func() (string, error)) *MockAppDataDirGetter_AppDataDir_Call {
	_c.Call.Return(run)
	return _c
}
