classdef DefaultSecureGeneratorTest < matlab.mock.TestCase
    %DefaultSecureGeneratorTest Tests for DefaultSecureGenerator
    %   This test class verifies that DefaultSecureGenerator correctly
    %   generates cryptographically secure keys using OS-level CSPRNGs.

    % Copyright 2026 The MathWorks, Inc.

    properties (Constant, Access = private)
        ExpectedKeySize(1,1) uint8 = 24
    end

    methods (Test)
        function testDefaultSecureGenerator_Constructor_HappyPath(testCase)
            % Arrange
            [mockOSFacade, ~] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );
            [mockFSFacade, ~] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );

            % Act
            generator = mcpcoreserver.internal.connector.internal.apikeymanager.internal.securegen.DefaultSecureGenerator( ...
                OSFacade=mockOSFacade, ...
                FSFacade=mockFSFacade ...
            );

            % Assert
            testCase.verifyInstanceOf( ...
                generator, ...
                ?mcpcoreserver.internal.connector.internal.apikeymanager.internal.securegen.SecureGenerator, ...
                "DefaultSecureGenerator should be a SecureGenerator" ...
            );
        end

        function testDefaultSecureGenerator_GenerateKey_HappyPath_LinuxMac(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.DoNothing

            [mockOSFacade, osBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );
            [mockFSFacade, fsBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );

            expectedBytes = uint8(0:23);
            expectedKey = lower(strjoin(string(dec2hex(expectedBytes, 2)), ""));
            fid = 42;

            when( ...
                osBehavior.ispc().withExactInputs(), ...
                AssignOutputs(false) ...
            );
            when( ...
                osBehavior.ismac().withExactInputs(), ...
                AssignOutputs(true) ...
            );
            when( ...
                fsBehavior.fopen(fullfile("/", "dev", "urandom"), "r"), ...
                AssignOutputs(fid) ...
            );
            when( ...
                fsBehavior.fread(fid, testCase.ExpectedKeySize, "*uint8"), ...
                AssignOutputs(expectedBytes) ...
            );
            when( ...
                fsBehavior.fclose(fid), ...
                DoNothing ...
            );

            generator = mcpcoreserver.internal.connector.internal.apikeymanager.internal.securegen.DefaultSecureGenerator( ...
                OSFacade=mockOSFacade, ...
                FSFacade=mockFSFacade ...
            );

            % Act
            key = generator.generateKey();

            % Assert
            testCase.verifyEqual(key, expectedKey, ...
                "Key should be hex-encoded bytes from /dev/urandom");
        end

        function testDefaultSecureGenerator_GenerateKey_HappyPath_Windows(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            testCase.assumeTrue(ispc, ...
                "Test requires Windows for .NET interop");

            [mockOSFacade, osBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );
            [mockFSFacade, ~] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );

            when( ...
                osBehavior.ispc().withExactInputs(), ...
                AssignOutputs(true) ...
            );

            generator = mcpcoreserver.internal.connector.internal.apikeymanager.internal.securegen.DefaultSecureGenerator( ...
                OSFacade=mockOSFacade, ...
                FSFacade=mockFSFacade ...
            );

            % Act
            key = generator.generateKey();

            % Assert
            testCase.verifyTrue(strlength(key) == 2*testCase.ExpectedKeySize, ...
                sprintf("Key should be %d hex characters (%d bytes)", 2*testCase.ExpectedKeySize, testCase.ExpectedKeySize));
            testCase.verifyTrue( ...
                ~isempty(regexp(key, sprintf("^[0-9a-f]{%d}$", 2*testCase.ExpectedKeySize), "once")), ...
                "Key should contain only lowercase hexadecimal characters" ...
            );
        end

        function testDefaultSecureGenerator_GenerateKey_UnsupportedOS(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockOSFacade, osBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );
            [mockFSFacade, ~] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );

            expectedError = mcpcoreserver.internal.error.Errors.UnsupportedOS();

            when( ...
                osBehavior.ispc().withExactInputs(), ...
                AssignOutputs(false) ...
            );
            when( ...
                osBehavior.ismac().withExactInputs(), ...
                AssignOutputs(false) ...
            );
            when( ...
                osBehavior.isunix().withExactInputs(), ...
                AssignOutputs(false) ...
            );

            generator = mcpcoreserver.internal.connector.internal.apikeymanager.internal.securegen.DefaultSecureGenerator( ...
                OSFacade=mockOSFacade, ...
                FSFacade=mockFSFacade ...
            );

            % Act & Assert
            testCase.verifyError(@() generator.generateKey(), ...
                expectedError.identifier, ...
                "Unknown OS should throw UnsupportedOS error");
        end

        function testDefaultSecureGenerator_GenerateKey_FopenFails(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockOSFacade, osBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );
            [mockFSFacade, fsBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );

            expectedError = mcpcoreserver.internal.error.Errors.SecureKeyGenerationFailed();

            when( ...
                osBehavior.ispc().withExactInputs(), ...
                AssignOutputs(false) ...
            );
            when( ...
                osBehavior.ismac().withExactInputs(), ...
                AssignOutputs(true) ...
            );
            when( ...
                fsBehavior.fopen(fullfile("/", "dev", "urandom"), "r"), ...
                AssignOutputs(-1) ...
            );

            generator = mcpcoreserver.internal.connector.internal.apikeymanager.internal.securegen.DefaultSecureGenerator( ...
                OSFacade=mockOSFacade, ...
                FSFacade=mockFSFacade ...
            );

            % Act & Assert
            testCase.verifyError(@() generator.generateKey(), ...
                expectedError.identifier, ...
                "Failed fopen should throw SecureKeyGenerationFailed error");
        end
    end

end
