// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/tools/singlesession/custom/definition"
	mock "github.com/stretchr/testify/mock"
)

// NewMockValidatedTool creates a new instance of MockValidatedTool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockValidatedTool(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockValidatedTool {
	mock := &MockValidatedTool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockValidatedTool is an autogenerated mock type for the ValidatedTool type
type MockValidatedTool struct {
	mock.Mock
}

type MockValidatedTool_Expecter struct {
	mock *mock.Mock
}

func (_m *MockValidatedTool) EXPECT() *MockValidatedTool_Expecter {
	return &MockValidatedTool_Expecter{mock: &_m.Mock}
}

// Definition provides a mock function for the type MockValidatedTool
func (_mock *MockValidatedTool) Definition() definition.Tool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Definition")
	}

	var r0 definition.Tool
	if returnFunc, ok := ret.Get(0).(func() definition.Tool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(definition.Tool)
	}
	return r0
}

// MockValidatedTool_Definition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Definition'
type MockValidatedTool_Definition_Call struct {
	*mock.Call
}

// Definition is a helper method to define mock.On call
func (_e *MockValidatedTool_Expecter) Definition() *MockValidatedTool_Definition_Call {
	return &MockValidatedTool_Definition_Call{Call: _e.mock.On("Definition")}
}

func (_c *MockValidatedTool_Definition_Call) Run(run func()) *MockValidatedTool_Definition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockValidatedTool_Definition_Call) Return(tool definition.Tool) *MockValidatedTool_Definition_Call {
	_c.Call.Return(tool)
	return _c
}

func (_c *MockValidatedTool_Definition_Call) RunAndReturn(run func() definition.Tool) *MockValidatedTool_Definition_Call {
	_c.Call.Return(run)
	return _c
}

// Signature provides a mock function for the type MockValidatedTool
func (_mock *MockValidatedTool) Signature() definition.Signature {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Signature")
	}

	var r0 definition.Signature
	if returnFunc, ok := ret.Get(0).(func() definition.Signature); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(definition.Signature)
	}
	return r0
}

// MockValidatedTool_Signature_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Signature'
type MockValidatedTool_Signature_Call struct {
	*mock.Call
}

// Signature is a helper method to define mock.On call
func (_e *MockValidatedTool_Expecter) Signature() *MockValidatedTool_Signature_Call {
	return &MockValidatedTool_Signature_Call{Call: _e.mock.On("Signature")}
}

func (_c *MockValidatedTool_Signature_Call) Run(run func()) *MockValidatedTool_Signature_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockValidatedTool_Signature_Call) Return(signature definition.Signature) *MockValidatedTool_Signature_Call {
	_c.Call.Return(signature)
	return _c
}

func (_c *MockValidatedTool_Signature_Call) RunAndReturn(run func() definition.Signature) *MockValidatedTool_Signature_Call {
	_c.Call.Return(run)
	return _c
}
