// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockResourceLimitManager creates a new instance of MockResourceLimitManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResourceLimitManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResourceLimitManager {
	mock := &MockResourceLimitManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockResourceLimitManager is an autogenerated mock type for the ResourceLimitManager type
type MockResourceLimitManager struct {
	mock.Mock
}

type MockResourceLimitManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResourceLimitManager) EXPECT() *MockResourceLimitManager_Expecter {
	return &MockResourceLimitManager_Expecter{mock: &_m.Mock}
}

// CapOpenFilesLimit provides a mock function for the type MockResourceLimitManager
func (_mock *MockResourceLimitManager) CapOpenFilesLimit(limit uint64) (func() error, error) {
	ret := _mock.Called(limit)

	if len(ret) == 0 {
		panic("no return value specified for CapOpenFilesLimit")
	}

	var r0 func() error
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64) (func() error, error)); ok {
		return returnFunc(limit)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) func() error); ok {
		r0 = returnFunc(limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func() error)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = returnFunc(limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockResourceLimitManager_CapOpenFilesLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CapOpenFilesLimit'
type MockResourceLimitManager_CapOpenFilesLimit_Call struct {
	*mock.Call
}

// CapOpenFilesLimit is a helper method to define mock.On call
//   - limit uint64
func (_e *MockResourceLimitManager_Expecter) CapOpenFilesLimit(limit interface{}) *MockResourceLimitManager_CapOpenFilesLimit_Call {
	return &MockResourceLimitManager_CapOpenFilesLimit_Call{Call: _e.mock.On("CapOpenFilesLimit", limit)}
}

func (_c *MockResourceLimitManager_CapOpenFilesLimit_Call) Run(run func(limit uint64)) *MockResourceLimitManager_CapOpenFilesLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockResourceLimitManager_CapOpenFilesLimit_Call) Return(fn func() error, err error) *MockResourceLimitManager_CapOpenFilesLimit_Call {
	_c.Call.Return(fn, err)
	return _c
}

func (_c *MockResourceLimitManager_CapOpenFilesLimit_Call) RunAndReturn(run func(limit uint64) (func() error, error)) *MockResourceLimitManager_CapOpenFilesLimit_Call {
	_c.Call.Return(run)
	return _c
}
