// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/matlabmanager/matlabsessionclient/embeddedconnector"
	"github.com/matlab/matlab-mcp-core-server/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionDiscoverer creates a new instance of MockSessionDiscoverer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionDiscoverer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionDiscoverer {
	mock := &MockSessionDiscoverer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionDiscoverer is an autogenerated mock type for the SessionDiscoverer type
type MockSessionDiscoverer struct {
	mock.Mock
}

type MockSessionDiscoverer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionDiscoverer) EXPECT() *MockSessionDiscoverer_Expecter {
	return &MockSessionDiscoverer_Expecter{mock: &_m.Mock}
}

// DiscoverSessions provides a mock function for the type MockSessionDiscoverer
func (_mock *MockSessionDiscoverer) DiscoverSessions(logger entities.Logger) []embeddedconnector.ConnectionDetails {
	ret := _mock.Called(logger)

	if len(ret) == 0 {
		panic("no return value specified for DiscoverSessions")
	}

	var r0 []embeddedconnector.ConnectionDetails
	if returnFunc, ok := ret.Get(0).(func(entities.Logger) []embeddedconnector.ConnectionDetails); ok {
		r0 = returnFunc(logger)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]embeddedconnector.ConnectionDetails)
		}
	}
	return r0
}

// MockSessionDiscoverer_DiscoverSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DiscoverSessions'
type MockSessionDiscoverer_DiscoverSessions_Call struct {
	*mock.Call
}

// DiscoverSessions is a helper method to define mock.On call
//   - logger entities.Logger
func (_e *MockSessionDiscoverer_Expecter) DiscoverSessions(logger interface{}) *MockSessionDiscoverer_DiscoverSessions_Call {
	return &MockSessionDiscoverer_DiscoverSessions_Call{Call: _e.mock.On("DiscoverSessions", logger)}
}

func (_c *MockSessionDiscoverer_DiscoverSessions_Call) Run(run func(logger entities.Logger)) *MockSessionDiscoverer_DiscoverSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 entities.Logger
		if args[0] != nil {
			arg0 = args[0].(entities.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSessionDiscoverer_DiscoverSessions_Call) Return(connectionDetailss []embeddedconnector.ConnectionDetails) *MockSessionDiscoverer_DiscoverSessions_Call {
	_c.Call.Return(connectionDetailss)
	return _c
}

func (_c *MockSessionDiscoverer_DiscoverSessions_Call) RunAndReturn(run func(logger entities.Logger) []embeddedconnector.ConnectionDetails) *MockSessionDiscoverer_DiscoverSessions_Call {
	_c.Call.Return(run)
	return _c
}

// FromSessionDetails provides a mock function for the type MockSessionDiscoverer
func (_mock *MockSessionDiscoverer) FromSessionDetails(logger entities.Logger, sessionDetails []byte) (embeddedconnector.ConnectionDetails, error) {
	ret := _mock.Called(logger, sessionDetails)

	if len(ret) == 0 {
		panic("no return value specified for FromSessionDetails")
	}

	var r0 embeddedconnector.ConnectionDetails
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(entities.Logger, []byte) (embeddedconnector.ConnectionDetails, error)); ok {
		return returnFunc(logger, sessionDetails)
	}
	if returnFunc, ok := ret.Get(0).(func(entities.Logger, []byte) embeddedconnector.ConnectionDetails); ok {
		r0 = returnFunc(logger, sessionDetails)
	} else {
		r0 = ret.Get(0).(embeddedconnector.ConnectionDetails)
	}
	if returnFunc, ok := ret.Get(1).(func(entities.Logger, []byte) error); ok {
		r1 = returnFunc(logger, sessionDetails)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionDiscoverer_FromSessionDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FromSessionDetails'
type MockSessionDiscoverer_FromSessionDetails_Call struct {
	*mock.Call
}

// FromSessionDetails is a helper method to define mock.On call
//   - logger entities.Logger
//   - sessionDetails []byte
func (_e *MockSessionDiscoverer_Expecter) FromSessionDetails(logger interface{}, sessionDetails interface{}) *MockSessionDiscoverer_FromSessionDetails_Call {
	return &MockSessionDiscoverer_FromSessionDetails_Call{Call: _e.mock.On("FromSessionDetails", logger, sessionDetails)}
}

func (_c *MockSessionDiscoverer_FromSessionDetails_Call) Run(run func(logger entities.Logger, sessionDetails []byte)) *MockSessionDiscoverer_FromSessionDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 entities.Logger
		if args[0] != nil {
			arg0 = args[0].(entities.Logger)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionDiscoverer_FromSessionDetails_Call) Return(connectionDetails embeddedconnector.ConnectionDetails, err error) *MockSessionDiscoverer_FromSessionDetails_Call {
	_c.Call.Return(connectionDetails, err)
	return _c
}

func (_c *MockSessionDiscoverer_FromSessionDetails_Call) RunAndReturn(run func(logger entities.Logger, sessionDetails []byte) (embeddedconnector.ConnectionDetails, error)) *MockSessionDiscoverer_FromSessionDetails_Call {
	_c.Call.Return(run)
	return _c
}
