// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"io"

	"github.com/matlab/matlab-mcp-core-server/internal/facades/osfacade"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOSLayer creates a new instance of MockOSLayer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOSLayer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOSLayer {
	mock := &MockOSLayer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOSLayer is an autogenerated mock type for the OSLayer type
type MockOSLayer struct {
	mock.Mock
}

type MockOSLayer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOSLayer) EXPECT() *MockOSLayer_Expecter {
	return &MockOSLayer_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockOSLayer
func (_mock *MockOSLayer) Create(name string) (osfacade.File, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 osfacade.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (osfacade.File, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) osfacade.File); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(osfacade.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOSLayer_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOSLayer_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - name string
func (_e *MockOSLayer_Expecter) Create(name interface{}) *MockOSLayer_Create_Call {
	return &MockOSLayer_Create_Call{Call: _e.mock.On("Create", name)}
}

func (_c *MockOSLayer_Create_Call) Run(run func(name string)) *MockOSLayer_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOSLayer_Create_Call) Return(file osfacade.File, err error) *MockOSLayer_Create_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockOSLayer_Create_Call) RunAndReturn(run func(name string) (osfacade.File, error)) *MockOSLayer_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Stderr provides a mock function for the type MockOSLayer
func (_mock *MockOSLayer) Stderr() io.Writer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stderr")
	}

	var r0 io.Writer
	if returnFunc, ok := ret.Get(0).(func() io.Writer); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Writer)
		}
	}
	return r0
}

// MockOSLayer_Stderr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stderr'
type MockOSLayer_Stderr_Call struct {
	*mock.Call
}

// Stderr is a helper method to define mock.On call
func (_e *MockOSLayer_Expecter) Stderr() *MockOSLayer_Stderr_Call {
	return &MockOSLayer_Stderr_Call{Call: _e.mock.On("Stderr")}
}

func (_c *MockOSLayer_Stderr_Call) Run(run func()) *MockOSLayer_Stderr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOSLayer_Stderr_Call) Return(writer io.Writer) *MockOSLayer_Stderr_Call {
	_c.Call.Return(writer)
	return _c
}

func (_c *MockOSLayer_Stderr_Call) RunAndReturn(run func() io.Writer) *MockOSLayer_Stderr_Call {
	_c.Call.Return(run)
	return _c
}
