// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRetryStrategy creates a new instance of MockRetryStrategy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRetryStrategy(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRetryStrategy {
	mock := &MockRetryStrategy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRetryStrategy is an autogenerated mock type for the RetryStrategy type
type MockRetryStrategy struct {
	mock.Mock
}

type MockRetryStrategy_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRetryStrategy) EXPECT() *MockRetryStrategy_Expecter {
	return &MockRetryStrategy_Expecter{mock: &_m.Mock}
}

// C provides a mock function for the type MockRetryStrategy
func (_mock *MockRetryStrategy) C(ctx context.Context) <-chan time.Time {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for C")
	}

	var r0 <-chan time.Time
	if returnFunc, ok := ret.Get(0).(func(context.Context) <-chan time.Time); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan time.Time)
		}
	}
	return r0
}

// MockRetryStrategy_C_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'C'
type MockRetryStrategy_C_Call struct {
	*mock.Call
}

// C is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRetryStrategy_Expecter) C(ctx interface{}) *MockRetryStrategy_C_Call {
	return &MockRetryStrategy_C_Call{Call: _e.mock.On("C", ctx)}
}

func (_c *MockRetryStrategy_C_Call) Run(run func(ctx context.Context)) *MockRetryStrategy_C_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRetryStrategy_C_Call) Return(timeCh <-chan time.Time) *MockRetryStrategy_C_Call {
	_c.Call.Return(timeCh)
	return _c
}

func (_c *MockRetryStrategy_C_Call) RunAndReturn(run func(ctx context.Context) <-chan time.Time) *MockRetryStrategy_C_Call {
	_c.Call.Return(run)
	return _c
}

// lock provides a mock function for the type MockRetryStrategy
func (_mock *MockRetryStrategy) lock() {
	_mock.Called()
	return
}

// MockRetryStrategy_lock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'lock'
type MockRetryStrategy_lock_Call struct {
	*mock.Call
}

// lock is a helper method to define mock.On call
func (_e *MockRetryStrategy_Expecter) lock() *MockRetryStrategy_lock_Call {
	return &MockRetryStrategy_lock_Call{Call: _e.mock.On("lock")}
}

func (_c *MockRetryStrategy_lock_Call) Run(run func()) *MockRetryStrategy_lock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRetryStrategy_lock_Call) Return() *MockRetryStrategy_lock_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRetryStrategy_lock_Call) RunAndReturn(run func()) *MockRetryStrategy_lock_Call {
	_c.Run(run)
	return _c
}
