classdef DefaultPermissionManagerForWindowsTest < matlab.mock.TestCase
    %DefaultPermissionManagerForWindowsTest Tests for DefaultPermissionManager (Windows)
    %   This test class verifies that DefaultPermissionManager correctly
    %   manages file and folder permissions across platforms.

    % Copyright 2026 The MathWorks, Inc.

    properties (Constant, Access = private)
        % Well-known SIDs (must match DefaultPermissionManager constants)
        SYSTEM_SID = "S-1-5-18"
        ADMINISTRATORS_SID = "S-1-5-32-544"
    end

    methods (Test)
        function testDefaultPermissionManager_SetPermissionsToUserOnly_HappyPath_Windows_Folder(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.DoNothing

            [mockFS, fsBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockOS, osBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );
            [mockSecurity, securityBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.fs.internal.permissionmanager.internal.windowsacl.WindowsACLManager, ...
                Strict=true ...
            );

            expectedPath = fullfile("C:", "Users", "user", "AppData");
            expectedUserSid = "S-1-5-21-12345";
            expectedSids = [expectedUserSid, testCase.SYSTEM_SID, testCase.ADMINISTRATORS_SID];

            when( ...
                osBehavior.ispc().withExactInputs(), ...
                AssignOutputs(true) ...
            );
            when( ...
                fsBehavior.isfolder(expectedPath), ...
                AssignOutputs(true) ...
            );
            when( ...
                securityBehavior.getCurrentUserSid().withExactInputs(), ...
                AssignOutputs(expectedUserSid) ...
            );
            when( ...
                securityBehavior.setProtectedAcl(expectedPath, expectedSids, true), ...
                DoNothing ...
            );

            fs = mcpcoreserver.internal.fs.internal.permissionmanager.DefaultPermissionManager( ...
                FSFacade=mockFS, ...
                OSFacade=mockOS, ...
                WindowsACLManager=mockSecurity ...
            );

            % Act
            fs.setPermissionsToUserOnly(expectedPath);

            % Assert
            testCase.verifyCalled( ...
                securityBehavior.setProtectedAcl(expectedPath, expectedSids, true), ...
                "Should call setProtectedAcl with user, SYSTEM, and Administrators SIDs for directory" ...
            );
        end

        function testDefaultPermissionManager_SetPermissionsToUserOnly_HappyPath_Windows_File(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.DoNothing

            [mockFS, fsBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockOS, osBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );
            [mockSecurity, securityBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.fs.internal.permissionmanager.internal.windowsacl.WindowsACLManager, ...
                Strict=true ...
            );

            expectedPath = fullfile("C:", "Users", "user", "file.json");
            expectedUserSid = "S-1-5-21-12345";
            expectedSids = [expectedUserSid, testCase.SYSTEM_SID, testCase.ADMINISTRATORS_SID];

            when( ...
                osBehavior.ispc().withExactInputs(), ...
                AssignOutputs(true) ...
            );
            when( ...
                fsBehavior.isfolder(expectedPath), ...
                AssignOutputs(false) ...
            );
            when( ...
                securityBehavior.getCurrentUserSid().withExactInputs(), ...
                AssignOutputs(expectedUserSid) ...
            );
            when( ...
                securityBehavior.setProtectedAcl(expectedPath, expectedSids, false), ...
                DoNothing ...
            );

            fs = mcpcoreserver.internal.fs.internal.permissionmanager.DefaultPermissionManager( ...
                FSFacade=mockFS, ...
                OSFacade=mockOS, ...
                WindowsACLManager=mockSecurity ...
            );

            % Act
            fs.setPermissionsToUserOnly(expectedPath);

            % Assert
            testCase.verifyCalled( ...
                securityBehavior.setProtectedAcl(expectedPath, expectedSids, false), ...
                "Should call setProtectedAcl with user, SYSTEM, and Administrators SIDs for file" ...
            );
        end

        function testDefaultPermissionManager_SetPermissionsToUserOnly_Windows_SetAclFails(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.ThrowException

            [mockFS, fsBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockOS, osBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );
            [mockSecurity, securityBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.fs.internal.permissionmanager.internal.windowsacl.WindowsACLManager, ...
                Strict=true ...
            );

            expectedPath = fullfile("C:", "Users", "user", "AppData");
            expectedUserSid = "S-1-5-21-12345";
            expectedSids = [expectedUserSid, testCase.SYSTEM_SID, testCase.ADMINISTRATORS_SID];

            when( ...
                osBehavior.ispc().withExactInputs(), ...
                AssignOutputs(true) ...
            );
            when( ...
                fsBehavior.isfolder(expectedPath), ...
                AssignOutputs(true) ...
            );
            when( ...
                securityBehavior.getCurrentUserSid().withExactInputs(), ...
                AssignOutputs(expectedUserSid) ...
            );
            when( ...
                securityBehavior.setProtectedAcl(expectedPath, expectedSids, true), ...
                ThrowException(MException("test:error", "Access denied")) ...
            );

            fs = mcpcoreserver.internal.fs.internal.permissionmanager.DefaultPermissionManager( ...
                FSFacade=mockFS, ...
                OSFacade=mockOS, ...
                WindowsACLManager=mockSecurity ...
            );

            expectedError = mcpcoreserver.internal.error.Errors.FailedToSetPermissions( ...
                expectedPath ...
            );

            % Act & Assert
            testCase.verifyError( ...
                @() fs.setPermissionsToUserOnly(expectedPath), ...
                expectedError.identifier, ...
                "Should throw FailedToSetPermissions when setProtectedAcl fails" ...
            );
        end

        function testDefaultPermissionManager_CheckPermissionsIsUserOnly_HappyPath_Windows(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockFS, ~] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockOS, osBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );
            [mockSecurity, securityBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.fs.internal.permissionmanager.internal.windowsacl.WindowsACLManager, ...
                Strict=true ...
            );

            expectedPath = fullfile("C:", "Users", "user", "AppData");
            expectedUserSid = "S-1-5-21-12345";
            returnedSids = [expectedUserSid, testCase.SYSTEM_SID, testCase.ADMINISTRATORS_SID];

            when( ...
                osBehavior.ispc().withExactInputs(), ...
                AssignOutputs(true) ...
            );
            when( ...
                securityBehavior.getCurrentUserSid().withExactInputs(), ...
                AssignOutputs(expectedUserSid) ...
            );
            when( ...
                securityBehavior.getAllowedSids(expectedPath), ...
                AssignOutputs(returnedSids) ...
            );
            when( ...
                securityBehavior.isDaclProtected(expectedPath), ...
                AssignOutputs(true) ...
            );

            fs = mcpcoreserver.internal.fs.internal.permissionmanager.DefaultPermissionManager( ...
                FSFacade=mockFS, ...
                OSFacade=mockOS, ...
                WindowsACLManager=mockSecurity ...
            );

            % Act
            result = fs.checkPermissionsIsUserOnly(expectedPath);

            % Assert
            testCase.verifyTrue(result, ...
                "Should return true when only user, SYSTEM, and Administrators have access");
        end

        function testDefaultPermissionManager_CheckPermissionsIsUserOnly_Windows_UnexpectedAce(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockFS, ~] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockOS, osBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );
            [mockSecurity, securityBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.fs.internal.permissionmanager.internal.windowsacl.WindowsACLManager, ...
                Strict=true ...
            );

            expectedPath = fullfile("C:", "Users", "user", "AppData");
            expectedUserSid = "S-1-5-21-12345";
            unexpectedSid = "S-1-5-21-99999";
            returnedSids = [expectedUserSid, testCase.SYSTEM_SID, testCase.ADMINISTRATORS_SID, unexpectedSid];

            when( ...
                osBehavior.ispc().withExactInputs(), ...
                AssignOutputs(true) ...
            );
            when( ...
                securityBehavior.getCurrentUserSid().withExactInputs(), ...
                AssignOutputs(expectedUserSid) ...
            );
            when( ...
                securityBehavior.getAllowedSids(expectedPath), ...
                AssignOutputs(returnedSids) ...
            );
            when( ...
                securityBehavior.isDaclProtected(expectedPath), ...
                AssignOutputs(true) ...
            );

            fs = mcpcoreserver.internal.fs.internal.permissionmanager.DefaultPermissionManager( ...
                FSFacade=mockFS, ...
                OSFacade=mockOS, ...
                WindowsACLManager=mockSecurity ...
            );

            % Act
            result = fs.checkPermissionsIsUserOnly(expectedPath);

            % Assert
            testCase.verifyFalse(result, ...
                "Should return false when an unexpected SID has access");
        end

        function testDefaultPermissionManager_CheckPermissionsIsUserOnly_Windows_UserMissing(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockFS, ~] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockOS, osBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );
            [mockSecurity, securityBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.fs.internal.permissionmanager.internal.windowsacl.WindowsACLManager, ...
                Strict=true ...
            );

            expectedPath = fullfile("C:", "Users", "user", "AppData");
            expectedUserSid = "S-1-5-21-12345";
            returnedSids = [testCase.SYSTEM_SID, testCase.ADMINISTRATORS_SID];

            when( ...
                osBehavior.ispc().withExactInputs(), ...
                AssignOutputs(true) ...
            );
            when( ...
                securityBehavior.getCurrentUserSid().withExactInputs(), ...
                AssignOutputs(expectedUserSid) ...
            );
            when( ...
                securityBehavior.getAllowedSids(expectedPath), ...
                AssignOutputs(returnedSids) ...
            );
            when( ...
                securityBehavior.isDaclProtected(expectedPath), ...
                AssignOutputs(true) ...
            );

            fs = mcpcoreserver.internal.fs.internal.permissionmanager.DefaultPermissionManager( ...
                FSFacade=mockFS, ...
                OSFacade=mockOS, ...
                WindowsACLManager=mockSecurity ...
            );

            % Act
            result = fs.checkPermissionsIsUserOnly(expectedPath);

            % Assert
            testCase.verifyFalse(result, ...
                "Should return false when current user SID is not in the ACL");
        end

        function testDefaultPermissionManager_CheckPermissionsIsUserOnly_Windows_SystemMissing(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockFS, ~] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockOS, osBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );
            [mockSecurity, securityBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.fs.internal.permissionmanager.internal.windowsacl.WindowsACLManager, ...
                Strict=true ...
            );

            expectedPath = fullfile("C:", "Users", "user", "AppData");
            expectedUserSid = "S-1-5-21-12345";
            returnedSids = [expectedUserSid, testCase.ADMINISTRATORS_SID];

            when( ...
                osBehavior.ispc().withExactInputs(), ...
                AssignOutputs(true) ...
            );
            when( ...
                securityBehavior.getCurrentUserSid().withExactInputs(), ...
                AssignOutputs(expectedUserSid) ...
            );
            when( ...
                securityBehavior.getAllowedSids(expectedPath), ...
                AssignOutputs(returnedSids) ...
            );
            when( ...
                securityBehavior.isDaclProtected(expectedPath), ...
                AssignOutputs(true) ...
            );

            fs = mcpcoreserver.internal.fs.internal.permissionmanager.DefaultPermissionManager( ...
                FSFacade=mockFS, ...
                OSFacade=mockOS, ...
                WindowsACLManager=mockSecurity ...
            );

            % Act
            result = fs.checkPermissionsIsUserOnly(expectedPath);

            % Assert
            testCase.verifyFalse(result, ...
                "Should return false when SYSTEM SID is missing from the ACL");
        end

        function testDefaultPermissionManager_CheckPermissionsIsUserOnly_Windows_AdministratorsMissing(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockFS, ~] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockOS, osBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );
            [mockSecurity, securityBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.fs.internal.permissionmanager.internal.windowsacl.WindowsACLManager, ...
                Strict=true ...
            );

            expectedPath = fullfile("C:", "Users", "user", "AppData");
            expectedUserSid = "S-1-5-21-12345";
            returnedSids = [expectedUserSid, testCase.SYSTEM_SID];

            when( ...
                osBehavior.ispc().withExactInputs(), ...
                AssignOutputs(true) ...
            );
            when( ...
                securityBehavior.getCurrentUserSid().withExactInputs(), ...
                AssignOutputs(expectedUserSid) ...
            );
            when( ...
                securityBehavior.getAllowedSids(expectedPath), ...
                AssignOutputs(returnedSids) ...
            );
            when( ...
                securityBehavior.isDaclProtected(expectedPath), ...
                AssignOutputs(true) ...
            );

            fs = mcpcoreserver.internal.fs.internal.permissionmanager.DefaultPermissionManager( ...
                FSFacade=mockFS, ...
                OSFacade=mockOS, ...
                WindowsACLManager=mockSecurity ...
            );

            % Act
            result = fs.checkPermissionsIsUserOnly(expectedPath);

            % Assert
            testCase.verifyFalse(result, ...
                "Should return false when Administrators SID is missing from the ACL");
        end

        function testDefaultPermissionManager_CheckPermissionsIsUserOnly_Windows_DaclNotProtected(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockFS, ~] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockOS, osBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );
            [mockSecurity, securityBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.fs.internal.permissionmanager.internal.windowsacl.WindowsACLManager, ...
                Strict=true ...
            );

            expectedPath = fullfile("C:", "Users", "user", "AppData");
            expectedUserSid = "S-1-5-21-12345";
            returnedSids = [expectedUserSid, testCase.SYSTEM_SID, testCase.ADMINISTRATORS_SID];

            when( ...
                osBehavior.ispc().withExactInputs(), ...
                AssignOutputs(true) ...
            );
            when( ...
                securityBehavior.getCurrentUserSid().withExactInputs(), ...
                AssignOutputs(expectedUserSid) ...
            );
            when( ...
                securityBehavior.getAllowedSids(expectedPath), ...
                AssignOutputs(returnedSids) ...
            );
            when( ...
                securityBehavior.isDaclProtected(expectedPath), ...
                AssignOutputs(false) ...
            );

            fs = mcpcoreserver.internal.fs.internal.permissionmanager.DefaultPermissionManager( ...
                FSFacade=mockFS, ...
                OSFacade=mockOS, ...
                WindowsACLManager=mockSecurity ...
            );

            % Act
            result = fs.checkPermissionsIsUserOnly(expectedPath);

            % Assert
            testCase.verifyFalse(result, ...
                "Should return false when DACL is not protected (inheritance not blocked)");
        end

        function testDefaultPermissionManager_CheckPermissionsIsUserOnly_Windows_EmptyAcl(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockFS, ~] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockOS, osBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );
            [mockSecurity, securityBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.fs.internal.permissionmanager.internal.windowsacl.WindowsACLManager, ...
                Strict=true ...
            );

            expectedPath = fullfile("C:", "Users", "user", "AppData");
            expectedUserSid = "S-1-5-21-12345";
            returnedSids = string.empty;

            when( ...
                osBehavior.ispc().withExactInputs(), ...
                AssignOutputs(true) ...
            );
            when( ...
                securityBehavior.getCurrentUserSid().withExactInputs(), ...
                AssignOutputs(expectedUserSid) ...
            );
            when( ...
                securityBehavior.getAllowedSids(expectedPath), ...
                AssignOutputs(returnedSids) ...
            );
            when( ...
                securityBehavior.isDaclProtected(expectedPath), ...
                AssignOutputs(true) ...
            );

            fs = mcpcoreserver.internal.fs.internal.permissionmanager.DefaultPermissionManager( ...
                FSFacade=mockFS, ...
                OSFacade=mockOS, ...
                WindowsACLManager=mockSecurity ...
            );

            % Act
            result = fs.checkPermissionsIsUserOnly(expectedPath);

            % Assert
            testCase.verifyFalse(result, ...
                "Should return false when ACL has no entries");
        end

        function testDefaultPermissionManager_CheckPermissionsIsUserOnly_Windows_GetAclFails(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.ThrowException

            [mockFS, ~] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockOS, osBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );
            [mockSecurity, securityBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.fs.internal.permissionmanager.internal.windowsacl.WindowsACLManager, ...
                Strict=true ...
            );

            expectedPath = fullfile("C:", "Users", "user", "AppData");

            when( ...
                osBehavior.ispc().withExactInputs(), ...
                AssignOutputs(true) ...
            );
            when( ...
                securityBehavior.getCurrentUserSid().withExactInputs(), ...
                ThrowException(MException("test:error", "Access denied")) ...
            );

            fs = mcpcoreserver.internal.fs.internal.permissionmanager.DefaultPermissionManager( ...
                FSFacade=mockFS, ...
                OSFacade=mockOS, ...
                WindowsACLManager=mockSecurity ...
            );

            expectedError = mcpcoreserver.internal.error.Errors.FailedToGetFileAttributes( ...
                expectedPath ...
            );

            % Act & Assert
            testCase.verifyError( ...
                @() fs.checkPermissionsIsUserOnly(expectedPath), ...
                expectedError.identifier, ...
                "Should throw FailedToGetFileAttributes when security facade fails" ...
            );
        end
    end

end
