classdef DefaultPermissionManagerTest < matlab.mock.TestCase
    %DefaultPermissionManagerTest Tests for DefaultPermissionManager
    %   This test class verifies that DefaultPermissionManager correctly
    %   manages file and folder permissions across platforms.

    % Copyright 2026 The MathWorks, Inc.

    properties (Constant, Access = private)
        % Well-known SDDL SID abbreviations (must match DefaultPermissionManager constants)
        SYSTEM_SID = "S-1-5-18"
        ADMINISTRATORS_SID = "S-1-5-32-544"
    end

    methods (Test)
        function testDefaultPermissionManager_Constructor_HappyPath(testCase)
            % Arrange
            [mockFS, ~] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockOS, ~] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );
            [mockSecurity, ~] = testCase.createMock( ...
                ?mcpcoreserver.internal.fs.internal.permissionmanager.internal.windowsacl.WindowsACLManager, ...
                Strict=true ...
            );

            % Act
            fs = mcpcoreserver.internal.fs.internal.permissionmanager.DefaultPermissionManager( ...
                FSFacade=mockFS, ...
                OSFacade=mockOS, ...
                WindowsACLManager=mockSecurity ...
            );

            % Assert
            testCase.verifyInstanceOf(fs, ?mcpcoreserver.internal.fs.internal.permissionmanager.PermissionManager, ...
                "DefaultPermissionManager should be a PermissionManager");
        end
    end

end
