classdef DefaultAPIKeyManagerTest < matlab.mock.TestCase
    %DefaultAPIKeyManagerTest Tests for DefaultAPIKeyManager
    %   This test class verifies that DefaultAPIKeyManager correctly retrieves
    %   API keys based on MATLAB version.

    % Copyright 2026 The MathWorks, Inc.

    methods (Test)
        function testDefaultAPIKeyManager_Constructor_HappyPath(testCase)
            % Arrange
            [mockConnectorFacade, ~] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.connector.ConnectorFacade, ...
                Strict=true ...
            );
            [mockMATLABFacade, ~] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.matlab.MATLABFacade, ...
                Strict=true ...
            );
            [mockSecureGenerator, ~] = testCase.createMock( ...
                ?mcpcoreserver.internal.connector.internal.apikeymanager.internal.securegen.SecureGenerator, ...
                Strict=true ...
            );

            % Act
            manager = mcpcoreserver.internal.connector.internal.apikeymanager.DefaultAPIKeyManager( ...
                ConnectorFacade=mockConnectorFacade, ...
                MATLABFacade=mockMATLABFacade, ...
                SecureGenerator=mockSecureGenerator ...
            );

            % Assert
            testCase.verifyInstanceOf( ...
                manager, ...
                ?mcpcoreserver.internal.connector.internal.apikeymanager.APIKeyManager, ...
                "DefaultAPIKeyManager should be an APIKeyManager" ...
            );
        end

        function testDefaultAPIKeyManager_GetAPIKey_PreR2023a(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockConnectorFacade, ~] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.connector.ConnectorFacade, ...
                Strict=true ...
            );
            [mockMATLABFacade, matlabBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.matlab.MATLABFacade, ...
                Strict=true ...
            );
            [mockSecureGenerator, ~] = testCase.createMock( ...
                ?mcpcoreserver.internal.connector.internal.apikeymanager.internal.securegen.SecureGenerator, ...
                Strict=true ...
            );

            when( ...
                matlabBehavior.isMATLABReleaseOlderThan("R2023a"), ...
                AssignOutputs(true) ...
            );

            manager = mcpcoreserver.internal.connector.internal.apikeymanager.DefaultAPIKeyManager( ...
                ConnectorFacade=mockConnectorFacade, ...
                MATLABFacade=mockMATLABFacade, ...
                SecureGenerator=mockSecureGenerator ...
            );

            expectedError = mcpcoreserver.internal.error.Errors.UnsupportedMATLABVersion();

            % Act & Assert
            testCase.verifyError(@() manager.getAPIKey(), ...
                expectedError.identifier, ...
                "Pre-R2023a should throw UnsupportedMATLABVersion error");
        end

        function testDefaultAPIKeyManager_GetAPIKey_KeyExists(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockConnectorFacade, connectorBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.connector.ConnectorFacade, ...
                Strict=true ...
            );
            [mockMATLABFacade, matlabBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.matlab.MATLABFacade, ...
                Strict=true ...
            );
            [mockSecureGenerator, ~] = testCase.createMock( ...
                ?mcpcoreserver.internal.connector.internal.apikeymanager.internal.securegen.SecureGenerator, ...
                Strict=true ...
            );

            expectedApiKey = "existing-key";

            when( ...
                matlabBehavior.isMATLABReleaseOlderThan("R2023a"), ...
                AssignOutputs(false) ...
            );
            when( ...
                connectorBehavior.getConfig("apiKey"), ...
                AssignOutputs(expectedApiKey) ...
            );

            manager = mcpcoreserver.internal.connector.internal.apikeymanager.DefaultAPIKeyManager( ...
                ConnectorFacade=mockConnectorFacade, ...
                MATLABFacade=mockMATLABFacade, ...
                SecureGenerator=mockSecureGenerator ...
            );

            % Act
            apiKey = manager.getAPIKey();

            % Assert
            testCase.verifyEqual(apiKey, expectedApiKey, ...
                "API key should be returned without regeneration");
            testCase.verifyCalled( ...
                connectorBehavior.getConfig("apiKey"), ...
                "getConfig should be called with apiKey" ...
            );
        end

        function testDefaultAPIKeyManager_GetAPIKey_GenerateKey(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.DoNothing

            [mockConnectorFacade, connectorBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.connector.ConnectorFacade, ...
                Strict=true ...
            );
            [mockMATLABFacade, matlabBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.matlab.MATLABFacade, ...
                Strict=true ...
            );
            [mockSecureGenerator, secureGenBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.connector.internal.apikeymanager.internal.securegen.SecureGenerator, ...
                Strict=true ...
            );

            emptyKey = "";
            expectedKey = "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6";

            when( ...
                matlabBehavior.isMATLABReleaseOlderThan("R2023a"), ...
                AssignOutputs(false) ...
            );
            when( ...
                connectorBehavior.getConfig("apiKey"), ...
                AssignOutputs(emptyKey).then(AssignOutputs(expectedKey)) ...
            );
            when( ...
                secureGenBehavior.generateKey().withExactInputs(), ...
                AssignOutputs(expectedKey) ...
            );
            when( ...
                connectorBehavior.setConfig("apiKey", expectedKey), ...
                DoNothing ...
            );

            manager = mcpcoreserver.internal.connector.internal.apikeymanager.DefaultAPIKeyManager( ...
                ConnectorFacade=mockConnectorFacade, ...
                MATLABFacade=mockMATLABFacade, ...
                SecureGenerator=mockSecureGenerator ...
            );

            % Act
            apiKey = manager.getAPIKey();

            % Assert
            testCase.verifyEqual(apiKey, expectedKey, ...
                "API key should be generated and returned");
            testCase.verifyCalled( ...
                secureGenBehavior.generateKey().withExactInputs(), ...
                "generateKey should be called to generate a secure key" ...
            );
            testCase.verifyCalled( ...
                connectorBehavior.setConfig("apiKey", expectedKey), ...
                "setConfig should be called with the generated key" ...
            );
        end

    end

end
