// Code generated by cpi-go-message-catalog/v2. DO NOT EDIT.

package messages

type Error interface {
	marker()
	Error() string
}

// AddonManagerErrors_InstallFailed_Error defines an error corresponding to the "AddonManagerErrors_InstallFailed" message catalog message
type AddonManagerErrors_InstallFailed_Error struct {
	Attr0 string
}

// Error makes AddonManagerErrors_InstallFailed_Error satisfy the error interface.
func (e *AddonManagerErrors_InstallFailed_Error) Error() string {
	return "AddonManagerErrors_InstallFailed_Error"
}

func (*AddonManagerErrors_InstallFailed_Error) marker() {}

// New_AddonManagerErrors_InstallFailed_Error makes a new AddonManagerErrors_InstallFailed_Error error.
func New_AddonManagerErrors_InstallFailed_Error(
	attr0 string,
) *AddonManagerErrors_InstallFailed_Error {
	return &AddonManagerErrors_InstallFailed_Error{
		Attr0: attr0,
	}
}

// StartupErrors_ArgumentNotAllowedInSessionMode_Error defines an error corresponding to the "StartupErrors_ArgumentNotAllowedInSessionMode" message catalog message
type StartupErrors_ArgumentNotAllowedInSessionMode_Error struct {
	Attr0 string
	Attr1 string
}

// Error makes StartupErrors_ArgumentNotAllowedInSessionMode_Error satisfy the error interface.
func (e *StartupErrors_ArgumentNotAllowedInSessionMode_Error) Error() string {
	return "StartupErrors_ArgumentNotAllowedInSessionMode_Error"
}

func (*StartupErrors_ArgumentNotAllowedInSessionMode_Error) marker() {}

// New_StartupErrors_ArgumentNotAllowedInSessionMode_Error makes a new StartupErrors_ArgumentNotAllowedInSessionMode_Error error.
func New_StartupErrors_ArgumentNotAllowedInSessionMode_Error(
	attr0 string,
	attr1 string,
) *StartupErrors_ArgumentNotAllowedInSessionMode_Error {
	return &StartupErrors_ArgumentNotAllowedInSessionMode_Error{
		Attr0: attr0,
		Attr1: attr1,
	}
}

// StartupErrors_BadFlag_Error defines an error corresponding to the "StartupErrors_BadFlag" message catalog message
type StartupErrors_BadFlag_Error struct {
	Attr0 string
	Attr1 string
	Attr2 string
}

// Error makes StartupErrors_BadFlag_Error satisfy the error interface.
func (e *StartupErrors_BadFlag_Error) Error() string {
	return "StartupErrors_BadFlag_Error"
}

func (*StartupErrors_BadFlag_Error) marker() {}

// New_StartupErrors_BadFlag_Error makes a new StartupErrors_BadFlag_Error error.
func New_StartupErrors_BadFlag_Error(
	attr0 string,
	attr1 string,
	attr2 string,
) *StartupErrors_BadFlag_Error {
	return &StartupErrors_BadFlag_Error{
		Attr0: attr0,
		Attr1: attr1,
		Attr2: attr2,
	}
}

// StartupErrors_BadSyntax_Error defines an error corresponding to the "StartupErrors_BadSyntax" message catalog message
type StartupErrors_BadSyntax_Error struct {
	Attr0 string
	Attr1 string
	Attr2 string
}

// Error makes StartupErrors_BadSyntax_Error satisfy the error interface.
func (e *StartupErrors_BadSyntax_Error) Error() string {
	return "StartupErrors_BadSyntax_Error"
}

func (*StartupErrors_BadSyntax_Error) marker() {}

// New_StartupErrors_BadSyntax_Error makes a new StartupErrors_BadSyntax_Error error.
func New_StartupErrors_BadSyntax_Error(
	attr0 string,
	attr1 string,
	attr2 string,
) *StartupErrors_BadSyntax_Error {
	return &StartupErrors_BadSyntax_Error{
		Attr0: attr0,
		Attr1: attr1,
		Attr2: attr2,
	}
}

// StartupErrors_BadValue_Error defines an error corresponding to the "StartupErrors_BadValue" message catalog message
type StartupErrors_BadValue_Error struct {
	Attr0 string
	Attr1 string
}

// Error makes StartupErrors_BadValue_Error satisfy the error interface.
func (e *StartupErrors_BadValue_Error) Error() string {
	return "StartupErrors_BadValue_Error"
}

func (*StartupErrors_BadValue_Error) marker() {}

// New_StartupErrors_BadValue_Error makes a new StartupErrors_BadValue_Error error.
func New_StartupErrors_BadValue_Error(
	attr0 string,
	attr1 string,
) *StartupErrors_BadValue_Error {
	return &StartupErrors_BadValue_Error{
		Attr0: attr0,
		Attr1: attr1,
	}
}

// StartupErrors_BadValueForEnvVar_Error defines an error corresponding to the "StartupErrors_BadValueForEnvVar" message catalog message
type StartupErrors_BadValueForEnvVar_Error struct {
	Attr0 string
	Attr1 string
}

// Error makes StartupErrors_BadValueForEnvVar_Error satisfy the error interface.
func (e *StartupErrors_BadValueForEnvVar_Error) Error() string {
	return "StartupErrors_BadValueForEnvVar_Error"
}

func (*StartupErrors_BadValueForEnvVar_Error) marker() {}

// New_StartupErrors_BadValueForEnvVar_Error makes a new StartupErrors_BadValueForEnvVar_Error error.
func New_StartupErrors_BadValueForEnvVar_Error(
	attr0 string,
	attr1 string,
) *StartupErrors_BadValueForEnvVar_Error {
	return &StartupErrors_BadValueForEnvVar_Error{
		Attr0: attr0,
		Attr1: attr1,
	}
}

// StartupErrors_CustomToolNameConflict_Error defines an error corresponding to the "StartupErrors_CustomToolNameConflict" message catalog message
type StartupErrors_CustomToolNameConflict_Error struct {
	Attr0 string
	Attr1 string
}

// Error makes StartupErrors_CustomToolNameConflict_Error satisfy the error interface.
func (e *StartupErrors_CustomToolNameConflict_Error) Error() string {
	return "StartupErrors_CustomToolNameConflict_Error"
}

func (*StartupErrors_CustomToolNameConflict_Error) marker() {}

// New_StartupErrors_CustomToolNameConflict_Error makes a new StartupErrors_CustomToolNameConflict_Error error.
func New_StartupErrors_CustomToolNameConflict_Error(
	attr0 string,
	attr1 string,
) *StartupErrors_CustomToolNameConflict_Error {
	return &StartupErrors_CustomToolNameConflict_Error{
		Attr0: attr0,
		Attr1: attr1,
	}
}

// StartupErrors_DuplicateParameter_Error defines an error corresponding to the "StartupErrors_DuplicateParameter" message catalog message
type StartupErrors_DuplicateParameter_Error struct {
	Attr0 string
	Attr1 string
	Attr2 string
}

// Error makes StartupErrors_DuplicateParameter_Error satisfy the error interface.
func (e *StartupErrors_DuplicateParameter_Error) Error() string {
	return "StartupErrors_DuplicateParameter_Error"
}

func (*StartupErrors_DuplicateParameter_Error) marker() {}

// New_StartupErrors_DuplicateParameter_Error makes a new StartupErrors_DuplicateParameter_Error error.
func New_StartupErrors_DuplicateParameter_Error(
	attr0 string,
	attr1 string,
	attr2 string,
) *StartupErrors_DuplicateParameter_Error {
	return &StartupErrors_DuplicateParameter_Error{
		Attr0: attr0,
		Attr1: attr1,
		Attr2: attr2,
	}
}

// StartupErrors_DuplicateToolName_Error defines an error corresponding to the "StartupErrors_DuplicateToolName" message catalog message
type StartupErrors_DuplicateToolName_Error struct {
	Attr0 string
	Attr1 string
}

// Error makes StartupErrors_DuplicateToolName_Error satisfy the error interface.
func (e *StartupErrors_DuplicateToolName_Error) Error() string {
	return "StartupErrors_DuplicateToolName_Error"
}

func (*StartupErrors_DuplicateToolName_Error) marker() {}

// New_StartupErrors_DuplicateToolName_Error makes a new StartupErrors_DuplicateToolName_Error error.
func New_StartupErrors_DuplicateToolName_Error(
	attr0 string,
	attr1 string,
) *StartupErrors_DuplicateToolName_Error {
	return &StartupErrors_DuplicateToolName_Error{
		Attr0: attr0,
		Attr1: attr1,
	}
}

// StartupErrors_FailedToCreateDirectory_Error defines an error corresponding to the "StartupErrors_FailedToCreateDirectory" message catalog message
type StartupErrors_FailedToCreateDirectory_Error struct {
	Attr0 string
}

// Error makes StartupErrors_FailedToCreateDirectory_Error satisfy the error interface.
func (e *StartupErrors_FailedToCreateDirectory_Error) Error() string {
	return "StartupErrors_FailedToCreateDirectory_Error"
}

func (*StartupErrors_FailedToCreateDirectory_Error) marker() {}

// New_StartupErrors_FailedToCreateDirectory_Error makes a new StartupErrors_FailedToCreateDirectory_Error error.
func New_StartupErrors_FailedToCreateDirectory_Error(
	attr0 string,
) *StartupErrors_FailedToCreateDirectory_Error {
	return &StartupErrors_FailedToCreateDirectory_Error{
		Attr0: attr0,
	}
}

// StartupErrors_FailedToCreateFile_Error defines an error corresponding to the "StartupErrors_FailedToCreateFile" message catalog message
type StartupErrors_FailedToCreateFile_Error struct {
	Attr0 string
}

// Error makes StartupErrors_FailedToCreateFile_Error satisfy the error interface.
func (e *StartupErrors_FailedToCreateFile_Error) Error() string {
	return "StartupErrors_FailedToCreateFile_Error"
}

func (*StartupErrors_FailedToCreateFile_Error) marker() {}

// New_StartupErrors_FailedToCreateFile_Error makes a new StartupErrors_FailedToCreateFile_Error error.
func New_StartupErrors_FailedToCreateFile_Error(
	attr0 string,
) *StartupErrors_FailedToCreateFile_Error {
	return &StartupErrors_FailedToCreateFile_Error{
		Attr0: attr0,
	}
}

// StartupErrors_FailedToCreateLogFile_Error defines an error corresponding to the "StartupErrors_FailedToCreateLogFile" message catalog message
type StartupErrors_FailedToCreateLogFile_Error struct {
	Attr0 string
}

// Error makes StartupErrors_FailedToCreateLogFile_Error satisfy the error interface.
func (e *StartupErrors_FailedToCreateLogFile_Error) Error() string {
	return "StartupErrors_FailedToCreateLogFile_Error"
}

func (*StartupErrors_FailedToCreateLogFile_Error) marker() {}

// New_StartupErrors_FailedToCreateLogFile_Error makes a new StartupErrors_FailedToCreateLogFile_Error error.
func New_StartupErrors_FailedToCreateLogFile_Error(
	attr0 string,
) *StartupErrors_FailedToCreateLogFile_Error {
	return &StartupErrors_FailedToCreateLogFile_Error{
		Attr0: attr0,
	}
}

// StartupErrors_FailedToCreateSubdirectory_Error defines an error corresponding to the "StartupErrors_FailedToCreateSubdirectory" message catalog message
type StartupErrors_FailedToCreateSubdirectory_Error struct {
	Attr0 string
}

// Error makes StartupErrors_FailedToCreateSubdirectory_Error satisfy the error interface.
func (e *StartupErrors_FailedToCreateSubdirectory_Error) Error() string {
	return "StartupErrors_FailedToCreateSubdirectory_Error"
}

func (*StartupErrors_FailedToCreateSubdirectory_Error) marker() {}

// New_StartupErrors_FailedToCreateSubdirectory_Error makes a new StartupErrors_FailedToCreateSubdirectory_Error error.
func New_StartupErrors_FailedToCreateSubdirectory_Error(
	attr0 string,
) *StartupErrors_FailedToCreateSubdirectory_Error {
	return &StartupErrors_FailedToCreateSubdirectory_Error{
		Attr0: attr0,
	}
}

// StartupErrors_FailedToGetExecutablePath_Error defines an error corresponding to the "StartupErrors_FailedToGetExecutablePath" message catalog message
type StartupErrors_FailedToGetExecutablePath_Error struct {
}

// Error makes StartupErrors_FailedToGetExecutablePath_Error satisfy the error interface.
func (e *StartupErrors_FailedToGetExecutablePath_Error) Error() string {
	return "StartupErrors_FailedToGetExecutablePath_Error"
}

func (*StartupErrors_FailedToGetExecutablePath_Error) marker() {}

// New_StartupErrors_FailedToGetExecutablePath_Error makes a new StartupErrors_FailedToGetExecutablePath_Error error.
func New_StartupErrors_FailedToGetExecutablePath_Error() *StartupErrors_FailedToGetExecutablePath_Error {
	return &StartupErrors_FailedToGetExecutablePath_Error{}
}

// StartupErrors_FailedToParseExtensionFile_Error defines an error corresponding to the "StartupErrors_FailedToParseExtensionFile" message catalog message
type StartupErrors_FailedToParseExtensionFile_Error struct {
	Attr0 string
}

// Error makes StartupErrors_FailedToParseExtensionFile_Error satisfy the error interface.
func (e *StartupErrors_FailedToParseExtensionFile_Error) Error() string {
	return "StartupErrors_FailedToParseExtensionFile_Error"
}

func (*StartupErrors_FailedToParseExtensionFile_Error) marker() {}

// New_StartupErrors_FailedToParseExtensionFile_Error makes a new StartupErrors_FailedToParseExtensionFile_Error error.
func New_StartupErrors_FailedToParseExtensionFile_Error(
	attr0 string,
) *StartupErrors_FailedToParseExtensionFile_Error {
	return &StartupErrors_FailedToParseExtensionFile_Error{
		Attr0: attr0,
	}
}

// StartupErrors_FailedToReadExtensionFile_Error defines an error corresponding to the "StartupErrors_FailedToReadExtensionFile" message catalog message
type StartupErrors_FailedToReadExtensionFile_Error struct {
	Attr0 string
}

// Error makes StartupErrors_FailedToReadExtensionFile_Error satisfy the error interface.
func (e *StartupErrors_FailedToReadExtensionFile_Error) Error() string {
	return "StartupErrors_FailedToReadExtensionFile_Error"
}

func (*StartupErrors_FailedToReadExtensionFile_Error) marker() {}

// New_StartupErrors_FailedToReadExtensionFile_Error makes a new StartupErrors_FailedToReadExtensionFile_Error error.
func New_StartupErrors_FailedToReadExtensionFile_Error(
	attr0 string,
) *StartupErrors_FailedToReadExtensionFile_Error {
	return &StartupErrors_FailedToReadExtensionFile_Error{
		Attr0: attr0,
	}
}

// StartupErrors_FailedToStartWatchdogProcess_Error defines an error corresponding to the "StartupErrors_FailedToStartWatchdogProcess" message catalog message
type StartupErrors_FailedToStartWatchdogProcess_Error struct {
}

// Error makes StartupErrors_FailedToStartWatchdogProcess_Error satisfy the error interface.
func (e *StartupErrors_FailedToStartWatchdogProcess_Error) Error() string {
	return "StartupErrors_FailedToStartWatchdogProcess_Error"
}

func (*StartupErrors_FailedToStartWatchdogProcess_Error) marker() {}

// New_StartupErrors_FailedToStartWatchdogProcess_Error makes a new StartupErrors_FailedToStartWatchdogProcess_Error error.
func New_StartupErrors_FailedToStartWatchdogProcess_Error() *StartupErrors_FailedToStartWatchdogProcess_Error {
	return &StartupErrors_FailedToStartWatchdogProcess_Error{}
}

// StartupErrors_GenericInitializeFailure_Error defines an error corresponding to the "StartupErrors_GenericInitializeFailure" message catalog message
type StartupErrors_GenericInitializeFailure_Error struct {
}

// Error makes StartupErrors_GenericInitializeFailure_Error satisfy the error interface.
func (e *StartupErrors_GenericInitializeFailure_Error) Error() string {
	return "StartupErrors_GenericInitializeFailure_Error"
}

func (*StartupErrors_GenericInitializeFailure_Error) marker() {}

// New_StartupErrors_GenericInitializeFailure_Error makes a new StartupErrors_GenericInitializeFailure_Error error.
func New_StartupErrors_GenericInitializeFailure_Error() *StartupErrors_GenericInitializeFailure_Error {
	return &StartupErrors_GenericInitializeFailure_Error{}
}

// StartupErrors_InvalidDisplayMode_Error defines an error corresponding to the "StartupErrors_InvalidDisplayMode" message catalog message
type StartupErrors_InvalidDisplayMode_Error struct {
	Attr0 string
}

// Error makes StartupErrors_InvalidDisplayMode_Error satisfy the error interface.
func (e *StartupErrors_InvalidDisplayMode_Error) Error() string {
	return "StartupErrors_InvalidDisplayMode_Error"
}

func (*StartupErrors_InvalidDisplayMode_Error) marker() {}

// New_StartupErrors_InvalidDisplayMode_Error makes a new StartupErrors_InvalidDisplayMode_Error error.
func New_StartupErrors_InvalidDisplayMode_Error(
	attr0 string,
) *StartupErrors_InvalidDisplayMode_Error {
	return &StartupErrors_InvalidDisplayMode_Error{
		Attr0: attr0,
	}
}

// StartupErrors_InvalidLogLevel_Error defines an error corresponding to the "StartupErrors_InvalidLogLevel" message catalog message
type StartupErrors_InvalidLogLevel_Error struct {
	Attr0 string
}

// Error makes StartupErrors_InvalidLogLevel_Error satisfy the error interface.
func (e *StartupErrors_InvalidLogLevel_Error) Error() string {
	return "StartupErrors_InvalidLogLevel_Error"
}

func (*StartupErrors_InvalidLogLevel_Error) marker() {}

// New_StartupErrors_InvalidLogLevel_Error makes a new StartupErrors_InvalidLogLevel_Error error.
func New_StartupErrors_InvalidLogLevel_Error(
	attr0 string,
) *StartupErrors_InvalidLogLevel_Error {
	return &StartupErrors_InvalidLogLevel_Error{
		Attr0: attr0,
	}
}

// StartupErrors_InvalidMATLABSessionMode_Error defines an error corresponding to the "StartupErrors_InvalidMATLABSessionMode" message catalog message
type StartupErrors_InvalidMATLABSessionMode_Error struct {
	Attr0 string
}

// Error makes StartupErrors_InvalidMATLABSessionMode_Error satisfy the error interface.
func (e *StartupErrors_InvalidMATLABSessionMode_Error) Error() string {
	return "StartupErrors_InvalidMATLABSessionMode_Error"
}

func (*StartupErrors_InvalidMATLABSessionMode_Error) marker() {}

// New_StartupErrors_InvalidMATLABSessionMode_Error makes a new StartupErrors_InvalidMATLABSessionMode_Error error.
func New_StartupErrors_InvalidMATLABSessionMode_Error(
	attr0 string,
) *StartupErrors_InvalidMATLABSessionMode_Error {
	return &StartupErrors_InvalidMATLABSessionMode_Error{
		Attr0: attr0,
	}
}

// StartupErrors_InvalidParameterKey_Error defines an error corresponding to the "StartupErrors_InvalidParameterKey" message catalog message
type StartupErrors_InvalidParameterKey_Error struct {
	Attr0 string
}

// Error makes StartupErrors_InvalidParameterKey_Error satisfy the error interface.
func (e *StartupErrors_InvalidParameterKey_Error) Error() string {
	return "StartupErrors_InvalidParameterKey_Error"
}

func (*StartupErrors_InvalidParameterKey_Error) marker() {}

// New_StartupErrors_InvalidParameterKey_Error makes a new StartupErrors_InvalidParameterKey_Error error.
func New_StartupErrors_InvalidParameterKey_Error(
	attr0 string,
) *StartupErrors_InvalidParameterKey_Error {
	return &StartupErrors_InvalidParameterKey_Error{
		Attr0: attr0,
	}
}

// StartupErrors_InvalidParameterType_Error defines an error corresponding to the "StartupErrors_InvalidParameterType" message catalog message
type StartupErrors_InvalidParameterType_Error struct {
	Attr0 string
	Attr1 string
}

// Error makes StartupErrors_InvalidParameterType_Error satisfy the error interface.
func (e *StartupErrors_InvalidParameterType_Error) Error() string {
	return "StartupErrors_InvalidParameterType_Error"
}

func (*StartupErrors_InvalidParameterType_Error) marker() {}

// New_StartupErrors_InvalidParameterType_Error makes a new StartupErrors_InvalidParameterType_Error error.
func New_StartupErrors_InvalidParameterType_Error(
	attr0 string,
	attr1 string,
) *StartupErrors_InvalidParameterType_Error {
	return &StartupErrors_InvalidParameterType_Error{
		Attr0: attr0,
		Attr1: attr1,
	}
}

// StartupErrors_InvalidToolDefinition_Error defines an error corresponding to the "StartupErrors_InvalidToolDefinition" message catalog message
type StartupErrors_InvalidToolDefinition_Error struct {
	Attr0 string
}

// Error makes StartupErrors_InvalidToolDefinition_Error satisfy the error interface.
func (e *StartupErrors_InvalidToolDefinition_Error) Error() string {
	return "StartupErrors_InvalidToolDefinition_Error"
}

func (*StartupErrors_InvalidToolDefinition_Error) marker() {}

// New_StartupErrors_InvalidToolDefinition_Error makes a new StartupErrors_InvalidToolDefinition_Error error.
func New_StartupErrors_InvalidToolDefinition_Error(
	attr0 string,
) *StartupErrors_InvalidToolDefinition_Error {
	return &StartupErrors_InvalidToolDefinition_Error{
		Attr0: attr0,
	}
}

// StartupErrors_InvalidToolInputSchema_Error defines an error corresponding to the "StartupErrors_InvalidToolInputSchema" message catalog message
type StartupErrors_InvalidToolInputSchema_Error struct {
	Attr0 string
	Attr1 string
}

// Error makes StartupErrors_InvalidToolInputSchema_Error satisfy the error interface.
func (e *StartupErrors_InvalidToolInputSchema_Error) Error() string {
	return "StartupErrors_InvalidToolInputSchema_Error"
}

func (*StartupErrors_InvalidToolInputSchema_Error) marker() {}

// New_StartupErrors_InvalidToolInputSchema_Error makes a new StartupErrors_InvalidToolInputSchema_Error error.
func New_StartupErrors_InvalidToolInputSchema_Error(
	attr0 string,
	attr1 string,
) *StartupErrors_InvalidToolInputSchema_Error {
	return &StartupErrors_InvalidToolInputSchema_Error{
		Attr0: attr0,
		Attr1: attr1,
	}
}

// StartupErrors_InvalidToolSignature_Error defines an error corresponding to the "StartupErrors_InvalidToolSignature" message catalog message
type StartupErrors_InvalidToolSignature_Error struct {
	Attr0 string
	Attr1 string
}

// Error makes StartupErrors_InvalidToolSignature_Error satisfy the error interface.
func (e *StartupErrors_InvalidToolSignature_Error) Error() string {
	return "StartupErrors_InvalidToolSignature_Error"
}

func (*StartupErrors_InvalidToolSignature_Error) marker() {}

// New_StartupErrors_InvalidToolSignature_Error makes a new StartupErrors_InvalidToolSignature_Error error.
func New_StartupErrors_InvalidToolSignature_Error(
	attr0 string,
	attr1 string,
) *StartupErrors_InvalidToolSignature_Error {
	return &StartupErrors_InvalidToolSignature_Error{
		Attr0: attr0,
		Attr1: attr1,
	}
}

// StartupErrors_MissingToolSignature_Error defines an error corresponding to the "StartupErrors_MissingToolSignature" message catalog message
type StartupErrors_MissingToolSignature_Error struct {
	Attr0 string
	Attr1 string
}

// Error makes StartupErrors_MissingToolSignature_Error satisfy the error interface.
func (e *StartupErrors_MissingToolSignature_Error) Error() string {
	return "StartupErrors_MissingToolSignature_Error"
}

func (*StartupErrors_MissingToolSignature_Error) marker() {}

// New_StartupErrors_MissingToolSignature_Error makes a new StartupErrors_MissingToolSignature_Error error.
func New_StartupErrors_MissingToolSignature_Error(
	attr0 string,
	attr1 string,
) *StartupErrors_MissingToolSignature_Error {
	return &StartupErrors_MissingToolSignature_Error{
		Attr0: attr0,
		Attr1: attr1,
	}
}

// StartupErrors_MissingValue_Error defines an error corresponding to the "StartupErrors_MissingValue" message catalog message
type StartupErrors_MissingValue_Error struct {
	Attr0 string
}

// Error makes StartupErrors_MissingValue_Error satisfy the error interface.
func (e *StartupErrors_MissingValue_Error) Error() string {
	return "StartupErrors_MissingValue_Error"
}

func (*StartupErrors_MissingValue_Error) marker() {}

// New_StartupErrors_MissingValue_Error makes a new StartupErrors_MissingValue_Error error.
func New_StartupErrors_MissingValue_Error(
	attr0 string,
) *StartupErrors_MissingValue_Error {
	return &StartupErrors_MissingValue_Error{
		Attr0: attr0,
	}
}

// StartupErrors_ParseFailed_Error defines an error corresponding to the "StartupErrors_ParseFailed" message catalog message
type StartupErrors_ParseFailed_Error struct {
	Attr0 string
	Attr1 string
}

// Error makes StartupErrors_ParseFailed_Error satisfy the error interface.
func (e *StartupErrors_ParseFailed_Error) Error() string {
	return "StartupErrors_ParseFailed_Error"
}

func (*StartupErrors_ParseFailed_Error) marker() {}

// New_StartupErrors_ParseFailed_Error makes a new StartupErrors_ParseFailed_Error error.
func New_StartupErrors_ParseFailed_Error(
	attr0 string,
	attr1 string,
) *StartupErrors_ParseFailed_Error {
	return &StartupErrors_ParseFailed_Error{
		Attr0: attr0,
		Attr1: attr1,
	}
}

// StartupErrors_TelemetryInitializationFailed_Error defines an error corresponding to the "StartupErrors_TelemetryInitializationFailed" message catalog message
type StartupErrors_TelemetryInitializationFailed_Error struct {
}

// Error makes StartupErrors_TelemetryInitializationFailed_Error satisfy the error interface.
func (e *StartupErrors_TelemetryInitializationFailed_Error) Error() string {
	return "StartupErrors_TelemetryInitializationFailed_Error"
}

func (*StartupErrors_TelemetryInitializationFailed_Error) marker() {}

// New_StartupErrors_TelemetryInitializationFailed_Error makes a new StartupErrors_TelemetryInitializationFailed_Error error.
func New_StartupErrors_TelemetryInitializationFailed_Error() *StartupErrors_TelemetryInitializationFailed_Error {
	return &StartupErrors_TelemetryInitializationFailed_Error{}
}

// StartupErrors_WriteError_Error defines an error corresponding to the "StartupErrors_WriteError" message catalog message
type StartupErrors_WriteError_Error struct {
	Attr0 string
	Attr1 string
}

// Error makes StartupErrors_WriteError_Error satisfy the error interface.
func (e *StartupErrors_WriteError_Error) Error() string {
	return "StartupErrors_WriteError_Error"
}

func (*StartupErrors_WriteError_Error) marker() {}

// New_StartupErrors_WriteError_Error makes a new StartupErrors_WriteError_Error error.
func New_StartupErrors_WriteError_Error(
	attr0 string,
	attr1 string,
) *StartupErrors_WriteError_Error {
	return &StartupErrors_WriteError_Error{
		Attr0: attr0,
		Attr1: attr1,
	}
}
