// Code generated by cpi-go-message-catalog/v2. DO NOT EDIT.

package messages

type messageMap map[messageKey]string

type localeMap map[localeKey]messageMap

var messages_en_US = messageMap{
	AddonManagerErrors_InstallFailed:                        `Failed to install MATLAB Add-On. For details, see the server log in "%[1]s".`,
	CLIMessages_BaseDirDescription:                          `The folder where this MCP server stores log files. If not specified, the server uses the default temp folder of your operating system.`,
	CLIMessages_DisableTelemetryDescription:                 `This MCP server can collect fully anonymized information about your usage of the server and send it to MathWorks. This data collection helps MathWorks improve products and is on by default. To opt out of data collection, set the argument --disable-telemetry to true.`,
	CLIMessages_DisplayModeDescription:                      `Specify whether to show the MATLAB desktop. Use 'desktop' mode (default) to show the MATLAB desktop or 'nodesktop' mode to use MATLAB only from your AI application, without the MATLAB desktop. `,
	CLIMessages_ExtensionFileDescription:                    `Use custom MCP tools by providing the path to a JSON extension file that defines the tools. Each tool maps to a MATLAB function. You can use the argument multiple times to specify multiple extension files. If you do not specify an extension file, the MCP server does not load any custom tools.`,
	CLIMessages_HelpDescription:                             `Show this help text`,
	CLIMessages_InitializeMATLABOnStartupDescription:        `To initialize MATLAB as soon as you start the server, set this argument to true. By default, MATLAB only starts when the first tool is called. `,
	CLIMessages_InternalUseDescription:                      `INTERNAL USE ONLY`,
	CLIMessages_LogLevelDescription:                         `The log levels of this MCP server. Valid values, in order of decreasing verbosity, are 'debug', 'info', 'warn', and 'error'.`,
	CLIMessages_MATLABSessionModeDescription:                `Specify how MATLAB sessions are managed. Use 'new' (default) to launch new MATLAB sessions from a local installation, or 'existing' to connect to an already running MATLAB instance.`,
	CLIMessages_PreferredLocalMATLABRootDescription:         `Full path specifying which MATLAB to start. Do not include /bin in the path. By default, the server tries to find the first MATLAB on the system PATH.`,
	CLIMessages_PreferredMATLABStartingDirectoryDescription: `Specify the folder where MATLAB starts. If you do not provide the argument, MATLAB starts in these locations: Linux: /home/username, Windows: C:\Users\username\Documents, Mac: /Users/username/Documents.`,
	CLIMessages_SetupMATLABDescription:                      `Set up a MATLAB installation for use with the MATLAB MCP Core Server.`,
	CLIMessages_SuccessfullySetupMATLAB:                     `Successfully setup MATLAB.`,
	CLIMessages_UseSingleMATLABSessionDescription:           `By default, this MCP server starts a single MATLAB session, and stops the session when the server shuts down. To allow the server to manage multiple MATLAB sessions, set this argument to false. `,
	CLIMessages_VersionDescription:                          `Display the version of this MCP server.`,
	StartupErrors_ArgumentNotAllowedInSessionMode:           `Error with supplied arguments: option "%[1]s" is not compatible with MATLAB session mode set to "%[2]s".`,
	StartupErrors_BadFlag:                                   `Error with supplied arguments: non-existent option %[1]s.%[2]s%[3]s`,
	StartupErrors_BadSyntax:                                 `Error with supplied arguments: invalid syntax %[1]s.%[2]s%[3]s`,
	StartupErrors_BadValue:                                  `Error with supplied arguments: invalid value %[1]s for option %[2]s.`,
	StartupErrors_BadValueForEnvVar:                         `Error with supplied environment variable: invalid value %[1]s for environment variable %[2]s.`,
	StartupErrors_CustomToolNameCollisionAcrossFiles:        `Tool name "%[1]s" is defined in multiple extension files: "%[2]s", "%[3]s".`,
	StartupErrors_CustomToolNameConflict:                    `Custom tool name "%[1]s" in extension file "%[2]s" conflicts with a built-in tool. Choose a different name.`,
	StartupErrors_DuplicateParameter:                        `Found duplicate parameter "%[1]s": %[2]s with value "%[3]s" is already defined.`,
	StartupErrors_DuplicateToolName:                         `Duplicate tool name "%[1]s" in "%[2]s". Choose a different name.`,
	StartupErrors_FailedToCreateDirectory:                   `Failed to create directory "%[1]s".`,
	StartupErrors_FailedToCreateFile:                        `Failed to create file "%[1]s".`,
	StartupErrors_FailedToCreateLogFile:                     `Failed to create the log file "%[1]s".`,
	StartupErrors_FailedToCreateSubdirectory:                `Failed to create subdirectory in "%[1]s".`,
	StartupErrors_FailedToGetExecutablePath:                 `Failed to get executable path.`,
	StartupErrors_FailedToParseExtensionFile:                `Failed to parse extension file "%[1]s". File must contain valid JSON.`,
	StartupErrors_FailedToReadExtensionFile:                 `Failed to read extension file "%[1]s". Check that file is valid.`,
	StartupErrors_FailedToStartWatchdogProcess:              `Failed to start watchdog process.`,
	StartupErrors_GenericInitializeFailure:                  `Failed to initialize MCP Core Server. For details, see the MCP server log in your AI application.`,
	StartupErrors_InvalidDisplayMode:                        `Error with supplied arguments: invalid display mode %[1]s.`,
	StartupErrors_InvalidLogLevel:                           `Error with supplied arguments: invalid log level %[1]s.`,
	StartupErrors_InvalidMATLABSessionMode:                  `Error with supplied arguments: invalid MATLAB session mode %[1]s.`,
	StartupErrors_InvalidParameterKey:                       `Invalid key "%[1]s" in configuration.`,
	StartupErrors_InvalidParameterType:                      `Invalid type for key "%[1]s" in configuration, expected "%[2]s".`,
	StartupErrors_InvalidToolDefinition:                     `Invalid custom tool definition in "%[1]s". Tool must match the tool schema specified by MCP.`,
	StartupErrors_InvalidToolInputSchema:                    `Invalid input schema for tool "%[1]s" in "%[2]s".`,
	StartupErrors_InvalidToolSignature:                      `Invalid signature for tool "%[1]s" in "%[2]s".`,
	StartupErrors_MissingToolSignature:                      `Missing signature for tool "%[1]s" in "%[2]s".`,
	StartupErrors_MissingValue:                              `Error with supplied arguments: value required for option %[1]s.`,
	StartupErrors_ParseFailed:                               `Error with supplied arguments: parse failed.%[1]s%[2]s`,
	StartupErrors_TelemetryInitializationFailed:             `Failed to initialize telemetry.`,
	StartupErrors_WriteError:                                `Failed to display %[1]s information. Error: %[2]s`,
}

var all = localeMap{
	Locale_en_US: messages_en_US,
}

// Catalog provides access to the messages for a specific locale.
type Catalog struct {
	cache messageMap
}

// NewCatalog creates a Catalog corresponding to a specific locale.
func NewCatalog(key LocaleKey) *Catalog {
	return &Catalog{
		cache: all[key.unseal()],
	}
}

// Get returns the message corresponding to the provided key.
func (c *Catalog) Get(key MessageKey) string {
	return c.cache[key.unseal()]
}

// MultiLocaleCatalog provides access to messages across all locales.
type MultiLocaleCatalog struct{}

// NewMultiLocaleCatalog creates a new multi-locale catalog.
func NewMultiLocaleCatalog() *MultiLocaleCatalog {
	return &MultiLocaleCatalog{}
}

// Get returns the message corresponding to the provided key and locale.
func (c *MultiLocaleCatalog) Get(key MessageKey, locale LocaleKey) string {
	return all[locale.unseal()][key.unseal()]
}
