// Code generated by cpi-go-message-catalog/v2. DO NOT EDIT.

package messages

type messageKey string

const (
	AddonManagerErrors_InstallFailed                        messageKey = "AddonManagerErrors_InstallFailed"
	CLIMessages_BaseDirDescription                          messageKey = "CLIMessages_BaseDirDescription"
	CLIMessages_DisableTelemetryDescription                 messageKey = "CLIMessages_DisableTelemetryDescription"
	CLIMessages_DisplayModeDescription                      messageKey = "CLIMessages_DisplayModeDescription"
	CLIMessages_ExtensionFileDescription                    messageKey = "CLIMessages_ExtensionFileDescription"
	CLIMessages_HelpDescription                             messageKey = "CLIMessages_HelpDescription"
	CLIMessages_InitializeMATLABOnStartupDescription        messageKey = "CLIMessages_InitializeMATLABOnStartupDescription"
	CLIMessages_InternalUseDescription                      messageKey = "CLIMessages_InternalUseDescription"
	CLIMessages_LogLevelDescription                         messageKey = "CLIMessages_LogLevelDescription"
	CLIMessages_MATLABSessionModeDescription                messageKey = "CLIMessages_MATLABSessionModeDescription"
	CLIMessages_PreferredLocalMATLABRootDescription         messageKey = "CLIMessages_PreferredLocalMATLABRootDescription"
	CLIMessages_PreferredMATLABStartingDirectoryDescription messageKey = "CLIMessages_PreferredMATLABStartingDirectoryDescription"
	CLIMessages_SetupMATLABDescription                      messageKey = "CLIMessages_SetupMATLABDescription"
	CLIMessages_SuccessfullySetupMATLAB                     messageKey = "CLIMessages_SuccessfullySetupMATLAB"
	CLIMessages_UseSingleMATLABSessionDescription           messageKey = "CLIMessages_UseSingleMATLABSessionDescription"
	CLIMessages_VersionDescription                          messageKey = "CLIMessages_VersionDescription"
	StartupErrors_ArgumentNotAllowedInSessionMode           messageKey = "StartupErrors_ArgumentNotAllowedInSessionMode"
	StartupErrors_BadFlag                                   messageKey = "StartupErrors_BadFlag"
	StartupErrors_BadSyntax                                 messageKey = "StartupErrors_BadSyntax"
	StartupErrors_BadValue                                  messageKey = "StartupErrors_BadValue"
	StartupErrors_BadValueForEnvVar                         messageKey = "StartupErrors_BadValueForEnvVar"
	StartupErrors_CustomToolNameCollisionAcrossFiles        messageKey = "StartupErrors_CustomToolNameCollisionAcrossFiles"
	StartupErrors_CustomToolNameConflict                    messageKey = "StartupErrors_CustomToolNameConflict"
	StartupErrors_DuplicateParameter                        messageKey = "StartupErrors_DuplicateParameter"
	StartupErrors_DuplicateToolName                         messageKey = "StartupErrors_DuplicateToolName"
	StartupErrors_FailedToCreateDirectory                   messageKey = "StartupErrors_FailedToCreateDirectory"
	StartupErrors_FailedToCreateFile                        messageKey = "StartupErrors_FailedToCreateFile"
	StartupErrors_FailedToCreateLogFile                     messageKey = "StartupErrors_FailedToCreateLogFile"
	StartupErrors_FailedToCreateSubdirectory                messageKey = "StartupErrors_FailedToCreateSubdirectory"
	StartupErrors_FailedToGetExecutablePath                 messageKey = "StartupErrors_FailedToGetExecutablePath"
	StartupErrors_FailedToParseExtensionFile                messageKey = "StartupErrors_FailedToParseExtensionFile"
	StartupErrors_FailedToReadExtensionFile                 messageKey = "StartupErrors_FailedToReadExtensionFile"
	StartupErrors_FailedToStartWatchdogProcess              messageKey = "StartupErrors_FailedToStartWatchdogProcess"
	StartupErrors_GenericInitializeFailure                  messageKey = "StartupErrors_GenericInitializeFailure"
	StartupErrors_InvalidDisplayMode                        messageKey = "StartupErrors_InvalidDisplayMode"
	StartupErrors_InvalidLogLevel                           messageKey = "StartupErrors_InvalidLogLevel"
	StartupErrors_InvalidMATLABSessionMode                  messageKey = "StartupErrors_InvalidMATLABSessionMode"
	StartupErrors_InvalidParameterKey                       messageKey = "StartupErrors_InvalidParameterKey"
	StartupErrors_InvalidParameterType                      messageKey = "StartupErrors_InvalidParameterType"
	StartupErrors_InvalidToolDefinition                     messageKey = "StartupErrors_InvalidToolDefinition"
	StartupErrors_InvalidToolInputSchema                    messageKey = "StartupErrors_InvalidToolInputSchema"
	StartupErrors_InvalidToolSignature                      messageKey = "StartupErrors_InvalidToolSignature"
	StartupErrors_MissingToolSignature                      messageKey = "StartupErrors_MissingToolSignature"
	StartupErrors_MissingValue                              messageKey = "StartupErrors_MissingValue"
	StartupErrors_ParseFailed                               messageKey = "StartupErrors_ParseFailed"
	StartupErrors_TelemetryInitializationFailed             messageKey = "StartupErrors_TelemetryInitializationFailed"
	StartupErrors_WriteError                                messageKey = "StartupErrors_WriteError"
)

// MessageKey is a specific type to signify message catalog keys.
type MessageKey interface {
	unseal() messageKey
}

func (m messageKey) unseal() messageKey { return m }
