// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/tools"
	"github.com/matlab/matlab-mcp-core-server/internal/messages"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCustomToolFactory creates a new instance of MockCustomToolFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCustomToolFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCustomToolFactory {
	mock := &MockCustomToolFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCustomToolFactory is an autogenerated mock type for the CustomToolFactory type
type MockCustomToolFactory struct {
	mock.Mock
}

type MockCustomToolFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCustomToolFactory) EXPECT() *MockCustomToolFactory_Expecter {
	return &MockCustomToolFactory_Expecter{mock: &_m.Mock}
}

// LoadTools provides a mock function for the type MockCustomToolFactory
func (_mock *MockCustomToolFactory) LoadTools(filePath string) ([]tools.Tool, messages.Error) {
	ret := _mock.Called(filePath)

	if len(ret) == 0 {
		panic("no return value specified for LoadTools")
	}

	var r0 []tools.Tool
	var r1 messages.Error
	if returnFunc, ok := ret.Get(0).(func(string) ([]tools.Tool, messages.Error)); ok {
		return returnFunc(filePath)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []tools.Tool); ok {
		r0 = returnFunc(filePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tools.Tool)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) messages.Error); ok {
		r1 = returnFunc(filePath)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(messages.Error)
		}
	}
	return r0, r1
}

// MockCustomToolFactory_LoadTools_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadTools'
type MockCustomToolFactory_LoadTools_Call struct {
	*mock.Call
}

// LoadTools is a helper method to define mock.On call
//   - filePath string
func (_e *MockCustomToolFactory_Expecter) LoadTools(filePath interface{}) *MockCustomToolFactory_LoadTools_Call {
	return &MockCustomToolFactory_LoadTools_Call{Call: _e.mock.On("LoadTools", filePath)}
}

func (_c *MockCustomToolFactory_LoadTools_Call) Run(run func(filePath string)) *MockCustomToolFactory_LoadTools_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCustomToolFactory_LoadTools_Call) Return(tools1 []tools.Tool, error messages.Error) *MockCustomToolFactory_LoadTools_Call {
	_c.Call.Return(tools1, error)
	return _c
}

func (_c *MockCustomToolFactory_LoadTools_Call) RunAndReturn(run func(filePath string) ([]tools.Tool, messages.Error)) *MockCustomToolFactory_LoadTools_Call {
	_c.Call.Return(run)
	return _c
}
